### ISSUE TITLE
Does the current PPO support discrete actions?

### ISSUE THREAD

**Issue by minruixu** [thu-ml/tianshou#101]
Hi, how an exciting work you have done in tianshou! But there still some doubts while I use the code in my experiments. I have found that there are no different in the continues version PPO and discrete version PPO. However, your experimental results show that the discrete version PPO work well in CartPole-v0. But when I change the env to MountainCar and Acrobot it does not work at all.

**Comment by Trinkle23897** [comment]
Yes but both MountainCar and Acrobot need another set of hyperparameters. We are working on it.
We will release something like stable-baselines-zoo: https://github.com/araffin/rl-baselines-zoo, it's on our roadmap.

**Comment by Trinkle23897** [comment]
Hi, please use the newest version to run it. I think it works well.
#155
