### ISSUE TITLE
Async Sampling

### ISSUE THREAD

**Issue by magicly** [thu-ml/tianshou#103]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

hello~
In most envs, env `step` cost almost the same time, so `SubprocVectorEnv` and `RayVectorEnv` run almost linear scale up. However in my env， each `step` cost very different time， e.g. 90% step cost 1s, but 10% cost 10s. So when I run 10 `SubprocVectorEnv`，there are almost no speeding up, because almose envery step, there is a slow step cost 10s, and other 9 fast step cost 1s, but the step 'blocked' to wait for all 10 envs step finished.  I think if the 10 envs step independently, the total time can almost linear scale up.  But it seems that I have to change `collector` too much. Do you have any suggestion?  Thanks very much for you great work on tianshou~

**Comment by Trinkle23897** [comment]
Indeed it needs to change some code. I haven't figure out clearly on how to adapt async vector env, but there are some possible ways with current codebase (assume you have `n` envs):
- use `await` and `async` keywords in Python + use `n` collector (one for a single env), since current collector only supports sync sampling;
- increase `n` so that it will cover up the drawback.

I have added this feature request to our roadmap.

**Comment by duburcqa** [comment]
I think there is a simple solution: each thread could simply continuously accumulate samples instead of waiting each other at each step https://github.com/thu-ml/tianshou/blob/60cfc373f8afb0eaa8716a3d21f14f01af0d74dc/tianshou/data/collector.py#L281. It only requires to perform environment steps and the while loop of the collector asynchronously.

**Comment by magicly** [comment]
thanks for you reply so soon. In fact I test this method, but the results is worse. 
> * increase `n` so that it will cover up the drawback.

I think the reason is when `n` get large there is almost one env slow `step` in every `step`.

emm, maybe if `n` is much larger than `most slow time` / `quick time` (in my example, 10s / 1s == 10) , it can speed up.  But I don't know if large `n` will affect final performance.   And in some envs, the most slow step may be much larger than quick step, e.g. 1s vs 10ms.

**Comment by duburcqa** [comment]
> I think the reason is when n get large there is almost one env slow step in every step.

Yes, I have exactly the same issue. In the worst case, `most slow time` / `quick time` = 10e3 during by experiment. It redults in the same speed up using 8 threads or 56 threads (on a cpu having enough physical cores). The CPU is only used at about 5 or 10% in average.

**Comment by magicly** [comment]
@duburcqa yeah, that works for me. But I need to change a lot of code in collector.   In my cases, my network model is simple, so `self.policy(batch)` is much faster than a env step. And in this case, when a env step finishes, just call `self.policy(batch)`, (here batch has just one data) is ok.   

But I think may be sometimes the network model is large enough, so the `policy(batch)` cost much time, then maybe waiting for a batch data then feed to network is a better choice.  It seems that both have some advantage, and the API
is not compatible.  Do you have some ideas how to handle these 2 cases?

**Comment by magicly** [comment]
@duburcqa when you say thread, do you use SubprocVectorEnv and mean Process?

**Comment by duburcqa** [comment]
I was thinking of this https://stackoverflow.com/a/46499291/4820605. It is fairly easy to adapt the current code to make use of it. Just use VectorEnv (or a list of Env) instead of SubprocVectorEnv and call the block (step + append to batch) for each environment independently and asynchronously, then put this block in the while True loop using the same terminal condition. No big refactoring here.

**Comment by duburcqa** [comment]
If I have time I will post a mock here today or next day.

**Comment by duburcqa** [comment]
Here it is:

```
import asyncio
import random
import time
from tianshou.env import VectorEnv

from env import MyTestEnv


async def worker(worker_id, env, queue):
    while True:
        # Get a step request out of the queue.
        action = await queue.get()

        # Perform a single step
        env.step(action)
        await asyncio.sleep(random.random())

        # Notify the queue that a step has been performed
        queue.task_done()

        print(f"Worker {worker_id} has performed action {action}.")


async def main():
    # Create environment list
    vec_envs = VectorEnv([lambda size=10: MyTestEnv(size) for _ in range(3)])

    # Create a queue that we will use to store our "workload"
    queue = asyncio.Queue()

    # Generate step request and put them into the queue
    action_list = [1] * 5 + [0] * 10 + [1] * 10
    for i in action_list:
        queue.put_nowait(i)

    # Create three worker tasks to process the queue concurrently
    tasks = []
    for i, env in enumerate(vec_envs.envs):
        task = asyncio.ensure_future(worker(i, env, queue))
        tasks.append(task)

    # Wait until the queue is fully processed
    await queue.join()

    # Cancel our worker tasks.
    for task in tasks:
        task.cancel()
    await asyncio.gather(*tasks, return_exceptions=True)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

**Comment by magicly** [comment]
I think if we don't change collector code, we still have to wait for all envs step complete.
```py
    # Wait until the queue is fully processed
    await queue.join()
```

And it seems like that asyncio just fits for IO Bound program, and has just one thread, maybe doesn't work for cpu bound env.

**Comment by duburcqa** [comment]
>  I think if we don't change collector code, we still have to wait for all envs step complete.

No since here the queue gathers all the step request of every environment. Just run this example on your computer and see. And indeed of using a for loop to populate the queue once for all, just use the same While loop and terminal condition of the collector and populate continuously the queue.

**Comment by duburcqa** [comment]
> And it seems like that asyncio just fits for IO Bound program, and has just one thread, maybe doesn't work for cpu bound env.

It is true, but one can simply modify `SubprocVectorEnv` to enable specifying the worker (as it is already the case of `reset` method, but should be generalized to any method) and use `SubprocVectorEnv` over `VectorEnv`.

**Comment by Trinkle23897** [comment]
I'm thinking about this problem. Here it is:

First solution:
Maybe we can construct something like an asyncVectorEnv: the input is an action list, the output may be as `[None, result_1, None, result_3, ...]` where `None` indicates that step has not finished yet.
To be implemented: a timer on both sides (collector and VecEnv).

Second solution:
We can add a flag which indicates whether it should use the async mode: 
- if "no", the same as before;
- if "yes", we should manually copy all of the policy. The sampling procedures are independent of each other. The data will be collected to the cache buffer (current version) or one line of 2d-buffer (maybe the next version). (Btw, I think it still needs some cache buffers since it's hard to use the same buffer in different threads). On the collector side, it needs a timer to check if it meets the criteria.

So from the above two solutions, it seems that the cache buffer is a must. I don't know whether changing to the 2d-buffer is a must or not ( #105 ) since this cache-buffer version can also be refacted to an easier-maintain version.

**Comment by duburcqa** [comment]
I thing there is a third, better approch:

- Request N "step" samples to `asyncVectorEnv`. No matter what, it has to output N steps, but internally the same thread can generate multiple samples, while some other do not generate any.
- Then, for the next request, those having generated fewer samples are likely to catch up their delay and output more sample in turn. 

Doing this, it does not require to change the API of `collector` at all, just to add  `asyncVectorEnv`, and it does not rely on any timer. My [example](https://github.com/thu-ml/tianshou/issues/103#issuecomment-650949489) just above is doing exactly this.

**Comment by duburcqa** [comment]
If you need, perhaps I can manage to find some time to implement it.

**Comment by Trinkle23897** [comment]
> I thing there is a third, better approch:
> 
> * Request N "step" samples to `asyncVectorEnv`. No matter what, it has to output N steps, but internally the same thread can generate multiple samples, while some other do not generate any.

I haven't got it. Does it mean that the cached obs and other things are implemented in asyncVectorEnv? But how about the policy's action? I haven't figure out the process.

> * Then, for the next request, those having generated fewer samples are likely to catch up their delay and output more sample in turn.
> 
> Doing this, it does not require to change the API of `collector` at all, just to add `asyncVectorEnv`, and it does not rely on any timer. My [example](https://github.com/thu-ml/tianshou/issues/103#issuecomment-650949489) just above is doing exactly this.

> If you need, perhaps I can manage to find some time to implement it.

Thanks in advance and much appreciated!!!

**Comment by duburcqa** [comment]
After working on the implementation, I realize I completely missed the requirement that consecutive steps must the executed by the same environment, so it is necessary to keep track of this. It cannot be done at `asyncVectorEnv` level transparently and it is necessary to modify the collector. My going for something close to your second solution:
> We can add a flag which indicates whether it should use the async mode.

But doing the minimal modifications. I think it is possible to avoid having to rely on a timer, and to use the exact same mechanism of cached buffer. I'll let you know.

**Comment by Trinkle23897** [comment]
As mentioned in https://github.com/thu-ml/tianshou/pull/134#discussion_r460499684, the vecenv can be all refactored into the async version and the collector can only handle the async branch.

**Comment by youkaichao** [comment]
@magicly  #134 is a working version with async simulation of environment. You just need to replace SubprocVectorEnv with AsyncVectorEnv, and provide an additional ``wait_num`` parameter (1 <= wait_num <= env_num). 

1. With a larger wait_num, you enjoy the speedup of parallel simulation, but may suffer from delay when some environments are slow;

2. With a small wait_num, the benefit of parallel simulation goes down but slow environments will not lag behind the whole procedure.

The best value for ``wait_num`` parameter should be tuned and is highly dependent on your configuration. Feel welcome to report your speedup when using AsyncVectorEnv!

A last notice: in the future we may make async simulation an inherent ability of all vector environments and the interface may change. Keep yourself informed!

**Comment by magicly** [comment]
thanks very much.  Recently I spend some time on Ray, and find sth similar:

https://docs.ray.io/en/latest/package-ref.html?highlight=wait#ray.wait


I'll test the AsyncVectorEnv and report some results~

**Comment by youkaichao** [comment]
> Recently I spend some time on Ray, and find sth similar

Yeah, we are planning to make async simulation an inherent ability of all vector environments. After that, RayVectorEnv can be used in async simulation, too (by using exactly the function you point out).

Stay tuned!

**Comment by magicly** [comment]
cool, thanks~

**Comment by Trinkle23897** [comment]
No, it should not be closed since we haven't finished it yet :)

**Comment by Trinkle23897** [comment]
@magicly Kaichao proposes a draft version of integrating async mode in all vector env in #179. Please have a look if you have time, and we are waiting for your insightful comment! (all vector environments support async simulation with just an additional ``wait_num`` parameter)!

**Comment by magicly** [comment]
@Trinkle23897 sorry for my delayed comments. I check the code #179  , very nice work~

I find the `wait` method doesn't have a `timeout` parameter,  so collector must wait for the exactly `wait_num` env finished before next `step`.  However, in some envs, different `step` time may vary so much that it's very hard to set a proper `wait_num`. And the network forward time for a batch seems to be nearly constant,  so I think it may be easier to set a proper `timeout` parameter. 

`wait` method of both `subproc` and `ray` have support for `timeout` parameter, so I think it needs just a little more work to match the semantics of `ray.wait`.

https://docs.ray.io/en/latest/package-ref.html?highlight=wait#ray.wait

> If timeout is set, the function returns either when the requested number of IDs are ready or when the timeout is reached, whichever occurs first. If it is not set, the function simply waits until that number of objects is ready and returns that exact number of object IDs.

**Comment by Trinkle23897** [comment]
Could you please directly comment on #179? Thanks!
