### ISSUE TITLE
Advance slicing method of Batch

### ISSUE THREAD

**Issue by Trinkle23897** [thu-ml/tianshou#104]
In recurrent-style training, it stores data in the format of `[batch_size, stack_num, ...]`. And if we want to get the first hidden state, `batch[:, 0]` is the best way instead of manually and recursively get the value in the batch. (#19)

Also with the multi-agent training scenario (someone is working on it), the batch-data will store in the format of `[env_num, agent_num, ...]`. If we want to get data from a specific agent's perspective, the best way is `batch[:, agent_id]`.

@duburcqa

**Comment by Trinkle23897** [comment]
Should the original `size` property be redirected to `shape`? I'd like to submit a new pr.

**Comment by duburcqa** [comment]
As you want. It is clear that `size` is no longer valid as is for multidimensional Batch, and not necessary if `shape` is available since `batch.size == 0` becomes `len(batch.shape) == 0` even though it is slightly less clear.
