### ISSUE TITLE
pong_dqn.py doesn't achieve high scores

### ISSUE THREAD

**Issue by davide97l** [thu-ml/tianshou#107]
I tried to run pong_dqn.py for 100 and 200 epochs but the agent never achieves a positive score, both using the default hyper-parameters or changing some of them doesn't lead to better performance.

**Comment by Trinkle23897** [comment]
I know. You can see #54.
@Mehooz has recently updated the atari result. He will push them into the repo these days.

**Comment by davide97l** [comment]
thank you for your fast reply! I will wait for the results.

**Comment by Trinkle23897** [comment]
Thanks. I'd like to briefly describe what we have done yet not pushed:
- remove atari_wrapper
- tune ppo on nearly all atari games
- tune dqn on some of atari games
- more things to do...
