### ISSUE TITLE
Batch code regression

### ISSUE THREAD

**Issue by duburcqa** [thu-ml/tianshou#118]
Why bound checking of `getitem` method have been removed ?
https://github.com/thu-ml/tianshou/blob/e0f4862d01e39e3f1fc6d3c90e7c705b2eef9b7e/tianshou/data/batch.py#L271

It leads to several issues, including the need of custom `__iter__`, which shouldn't be necessary:
https://github.com/thu-ml/tianshou/blob/481015932c78ed1eee991d1d7b1ac57545a11f83/tianshou/data/batch.py#L436

It was not the original plan https://github.com/thu-ml/tianshou/issues/104#issuecomment-651033749 and I'm not OK with changes made in commit f58358e2e9654c4c8ca3542e240b7b6545cd239a .

Performance issue was discussed [here](https://github.com/thu-ml/tianshou/pull/106#issuecomment-651589598), and it appears not to be an issue [here](https://github.com/thu-ml/tianshou/pull/106#issuecomment-651596000) as far as I remember. 

By standard, `__getitem__` is supposed to fail when invalid item is requested, and it is no longer the case.

So, unless it is turns out to have a significant impact on the performances, I suggest rolling back whose changes.

Plus, 10 minutes to review a PR https://github.com/thu-ml/tianshou/pull/117 feels a bit demanding...

**Comment by Trinkle23897** [comment]
> Plus, 10 minutes to review a PR #117 feels a bit demanding...

Okay, it's my fault. I'm pair-coding with Kaichao.

**Comment by Trinkle23897** [comment]
> By standard, __getitem__ is supposed to fail when an invalid item is requested, and it is no longer the case.

Yes, but in the current case, it still does the same thing.
```python
In [2]: d = Batch(a=[1,2,3])

In [3]: d[4]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-31c4f4ce9503> in <module>
----> 1 d[4]

~/github/tianshou-new/tianshou/data/batch.py in __getitem__(self, index)
    328                 b.__dict__[k] = Batch()
    329             else:
--> 330                 b.__dict__[k] = v[index]
    331         return b
    332 

IndexError: index 4 is out of bounds for axis 0 with size 3
```
In short, the IndexError will raise on other place rather than Batch (for example, in a torch.Tensor or np.ndarray).

**Comment by duburcqa** [comment]
Indeed, I suggest working on a proper fix https://github.com/thu-ml/tianshou/pull/119

For now this patch is not working because of some limitations of our usecases. Feel free to commit changes on top of it.
