### ISSUE TITLE
Can running and training be separated? 

### ISSUE THREAD

**Issue by kikikio** [thu-ml/tianshou#13]
Can running and training be separated? For example, we deploy on the cloud, send data to the cloud for training, and issue policies to local hosts intermittently or in real time. Local is only responsible for operation.

**Comment by Trinkle23897** [comment]
Our code currently does not support this method. But we will consider your suggestion.

**Comment by szrlee** [comment]
> Can running and training be separated? For example, we deploy on the cloud, send data to the cloud for training, and issue policies to local hosts intermittently or in real time. Local is only responsible for operation.

This is basically Actor-Learner architecture for distributed training.

**Comment by MischaPanch** [comment]
Not the core focus of tianshou and would likely require massive changes. Since there is not much activity on this issue, I'm gonna close it.
