### ISSUE TITLE
Remove some useless kwargs or not

### ISSUE THREAD

**Issue by youkaichao** [thu-ml/tianshou#131]
For some functions (like ``Collector.__init__``), @Trinkle23897 keep ``**kwargs`` arguments for api stability, so that adding a new argument with default values can work with older versions of tianshou.

However, I tend to remove these unused ``kwargs`` because they may hide some bugs and make it difficult for IDE to report unexpected arguments.

We need some discussions to determine what to do next. Suggestions are welcome especially by @duburcqa . Must we keep the ability of old versions of tianshou to work with code written for new versions of tianshou?

**Comment by duburcqa** [comment]
I tend to think it is essential to move forward. Api stability and  backward compatibility is very nice, and it is worth the effort, but it must not be an obstacle for refactoring the existing code base or adding new features. In my opinion, full backward compatibility is what is making Tensorflow less and less competitive wrt Pytorch over time https://towardsdatascience.com/is-pytorch-catching-tensorflow-ca88f9128304 .For example, offering different workflows to get the same result must be avoided at all cost.

If a new release breaks many things legitimately, for example to significantly improve performances, or add new highly requested features such as distributed computation capability, asynchronous sampling... then the users are usually willing to make some effort to port their code to be compatibility with the new API if it is clear how to do so, Pytorch offers migration guides to this end https://pytorch.org/blog/pytorch-0_4_0-migration-guide/.

In this case, I do prefer remove unused `kwargs`. I only use them in some particular cases where I expect the user to derive the class without overloading `__init__` or `__new__` method. I find it less error prone and less confusing for the user. But both are fine for me, it is not a big deal in this particular case.

**Comment by youkaichao** [comment]
solved in 3710b33 .
