### ISSUE TITLE
nstep return issue

### ISSUE THREAD

**Issue by yywe** [thu-ml/tianshou#135]
It seems that both the document and calculation of nstep reward is problematic.

(a). Document wise, 
G_t = \sum_{i = t}^{t + n - 1} \gamma^{i - t}(1 - d_i)r_i +
            \gamma^n (1 - d_{t + n}) Q_{\mathrm{target}}(s_{t + n})
Here, if d_i is a terminate state, the reward of this state will be cleared to 0. (the last step reward is ignored)

(b). For implementation, the 'now' variable tracks the 'nstep' indices, however, when the buffer is not full, say the buffer capacity is 10000, and there is only one episode in the buffer. say the length of the buffer is  just 10. then if n_step + indice will look for old data due to the '%' operator. which is not really the future n-step reward.

This part is not quite clear.  Thanks if I can get some help to understand!

**Comment by Trinkle23897** [comment]
Hi, what’s your question?

**Comment by yywe** [comment]
just edited and updated. the nstep calculation seems tricky (for the special case when the buffer is not full with the '%' operator).

**Comment by yywe** [comment]
I think the straightforward way to calculate nstep reward is to calculate it separately for each episode. Otherwise, if use a buffer and calculate as a batch, it needs to address one issue, i.e, search for the nearest terminate location. 

Consider an example,  I have a buffer with capacity 10000, and the buffer has two episodes, each has a length of say 3.
then the terminate status can be [non-term, non-term, terminal], [non-term, non-term, terminal].
and in the buffer this is just [non-term, non-term, terminal, non-term, non-term, terminal].

I can arbitrarily define nstep with any value, possibly >= 3, which equals to monte-carol case if nstep>=3. In this case,
'now = (indice + n) % buf_len'  can be any value. depending on 'n', since 'n' can be any value. also the buffer is not full. take %buf_len can be value of other old episodes. (nstep  return should based on the same episode)

**Comment by Trinkle23897** [comment]
> (b). For implementation, the 'now' variable tracks the 'nstep' indices, however, when the buffer is not full, say the buffer capacity is 10000, and there is only one episode in the buffer. say the length of the buffer is just 10. then if n_step + indice will look for old data due to the '%' operator. which is not really the future n-step reward.

This case does not exist since the collector will only use the policy to play a full episode and add the "full episode" data into the buffer (for most cases, except for single env). Here we assume all the data in the buffer has the terminal episode, in other words, it always ends by a done flag:
```
Index 0 1 2 3 4 5 6 7 8 9
Done  0 1 0 0 1 0 0 0 1 /
```
Since the current implementation calculates the n-step returns and terminates in the done flag, e.g., N=4 and indice=7 for example:
```
# buf_len == 9
iter 1 (n = 3, now = 1): G = r[1]
iter 2 (n = 2, now = 0): G = r[0] + gamma * G = r[0] + gamma * r[1]
iter 3 (n = 1, now = 8): G = r[8] * (1 - done) * gamma * G = r[8]  # since done == True, we eliminate the previous result of G ("returns[done[now] > 0] = 0" do this thing)
iter 4 (n = 0, now = 7): G = r[7] + gamma * G = r[7] + gamma * r[8]
```
And finally, it adds the last term (target_q) based on whether these N-step has terminal frames or not. This is finished by `gammas[done[now] > 0] = n` and `target_q[gammas != n_step] = 0`.

**Comment by Trinkle23897** [comment]
> (a). Document wise,
> G_t = \sum_{i = t}^{t + n - 1} \gamma^{i - t}(1 - d_i)r_i +
> \gamma^n (1 - d_{t + n}) Q_{\mathrm{target}}(s_{t + n})
> Here, if d_i is a terminate state, the reward of this state will be cleared to 0. (the last step reward is ignored)

Yes. I did not show the special case for simplicity in the documentation.

**Comment by Trinkle23897** [comment]
> I think the straightforward way to calculate nstep reward is to calculate it separately for each episode. Otherwise, if use a buffer and calculate as a batch, it needs to address one issue, i.e, search for the nearest terminate location.

This is done by `gammas`. It records this thing. You can refer to my explanation above.

> Consider an example, I have a buffer with capacity 10000, and the buffer has two episodes, each has a length of say 3.
> then the terminate status can be [non-term, non-term, terminal], [non-term, non-term, terminal].
> and in the buffer this is just [non-term, non-term, terminal, non-term, non-term, terminal].
> 
> I can arbitrarily define nstep with any value, possibly >= 3, which equals to monte-carol case if nstep>=3. In this case,
> 'now = (indice + n) % buf_len' can be any value. depending on 'n', since 'n' can be any value. also the buffer is not full. take %buf_len can be value of other old episodes. (nstep return should based on the same episode)

**Comment by yywe** [comment]
I understand the whole logic flow of the calculation. basically it calculates the reward part and Q_target part and sum up.
I need to digest some details.  especially for position of 'now'.

How about when nstep is any arbitrarily large value greater than episode length?

Thanks for your timely reply.

**Comment by Trinkle23897** [comment]
Let’s use the same buffer above:
```
Index 0 1 2 3 4 5 6 7 8 9
Done  0 1 0 0 1 0 0 0 1 /
```
If we want to calculate index=7 and N=8, the order of calculation is: 5 4 3 2 1 0 8 7
In index=4, the result of G (contains 5) will set 0; in index=1, the result of G (contains 2,3,4) will remove too. Same as index=8 (clear 0,1). So when it arrives to index=7, the G only contains 7,8.

**Comment by yywe** [comment]
I'll walk through some simple examples. Thanks for you kind explanation. I understand the idea behind nstep return, previously I used to calculate it episode by episode since it is more straightforward. I'm just looking for an efficient implementation and happened to find this repo.

BTW, your guys did a great job.  I've stared this project.

**Comment by Trinkle23897** [comment]
Thanks! By the way, GAE can be done efficiently just like this method. We can compute multiple episodes’ returns simultaneously too.

**Comment by yywe** [comment]
close now. many thanks for your quick and detailed explanation, man.
