### ISSUE TITLE
The length of empty Batch

### ISSUE THREAD

**Issue by youkaichao** [thu-ml/tianshou#138]
Currently, ``len(Batch())`` will raise an error.

The numpy behavior is:
```python
a = np.array([])
len(a) # 0
b = np.array(3)
len(b) # exception
```

So, len of an empty Batch should be 0. len of a Batch with scalars should raise an error.

Besides, if we want to support ``cat`` with empty Batches, we should also make ``len(Batch()) == 0``, otherwise we cannot tell ``Batch()`` from ``Batch(a=1)``, where ``Batch()`` can be used in ``cat`` but the scalar ``Batch(a=1)`` cannot.

@Trinkle23897  @duburcqa

**Comment by youkaichao** [comment]
@Trinkle23897  mentioned something in [here](https://github.com/thu-ml/tianshou/pull/137#discussion_r454178620), but the concept of empty goes beyond ``Batch()``. We need to identify empty Batch like ``Batch(a=Batch(), b=Batch(c=Batch()))``.

**Comment by duburcqa** [comment]
I don't think `np.array([])` and `Batch()` are equivalent.  For instance, `np.array([])` is a 1d-array whereas `Batch()` has no dim. Besides, `np.array(3)` is a 0-dim array. It is not comparable to `np.array([])`. Emptyness is a behavior specific to `Batch`, not provided by numpy: it would be `np.array()`. So our own `is_empty` method must be used to determine if a Batch is empty, or scalar.

**Comment by duburcqa** [comment]
Talking about Batch, another issue: `Batch(a=0).shape` should not fail but return `[]`, as for `Batch().shape`.

**Comment by duburcqa** [comment]
@youkaichao  closing ?

**Comment by Trinkle23897** [comment]
> @youkaichao closing ?

merge to `dev` will not auto-close, merge to `master` will.

**Comment by duburcqa** [comment]
> merge to dev will not auto-close, merge to master will.

And I like it this way personnally

**Comment by youkaichao** [comment]
Okay. The conclusion is: 

empty batch has the shape of any, like the tensorflow '?' shape. So it has no length.

**Comment by youkaichao** [comment]
I think we can discuss about the shape / length of empty Batches here, before closing it.

The conclusion for length is clear: empty batches (both direct Batch() and recurse empty batches) have no length.

But how about the shape?

> Talking about Batch, another issue: Batch(a=0).shape should not fail but return [], as for Batch().shape.

I think ``Batch(a=0).shape`` should return [], and Batch().shape should fail or return something like tensorflow '?' if we indeed want to return something.

**Comment by duburcqa** [comment]
> I think Batch(a=0).shape should return [], and Batch().shape should fail or return something like tensorflow '?' if we indeed want to return something.

I don't know. But why to make it fail ? For me [] is fine since is_empty can be used to check for actual emptiness. But both are fine to me.

**Comment by youkaichao** [comment]
> Batch(a=0).shape should return []

Supported in #142 .
