### ISSUE TITLE
Please consider Hydra

### ISSUE THREAD

**Issue by omry** [thu-ml/tianshou#145]
Hi @thu-ml.
tianshou looks awesome.

I am the author of [Hydra](https://hydra.cc). I think you should definitely check it out. It can probably make your life much easier when dealing with the configuration/command line complexity.
It also supports many other relevant things out of the box (launching remotely, parameter sweeps, hyper parameter optimizations and more).

[This](https://hydra.cc/docs/next/intro) is a good intro blog post.
If you check it out, be sure to read the docs for 1.0 which is right around the corner (there is already a release candidate out).

A trivia detail: the origin of Hydra is in an internal model based RL framework I built at FAIR.

**Comment by Trinkle23897** [comment]
Wow, that's great!
Sure, we will consider to provide some example scripts using Hydra. Thanks for your sharing!

**Comment by omry** [comment]
Awesome!
Taking full advantage of Hydra would probably involve more than just examples (an example is that argparse does not support hierarchical config with dynamic structure (decided at run time)), even a few examples would go a long way though.
Feel free to jump into the [Hydra chat](https://hydra-framework.zulipchat.com/) if you have any questions!
