### ISSUE TITLE
How to support high dimensional action space?

### ISSUE THREAD

**Issue by ryanhuang1014** [thu-ml/tianshou#146]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request

As mentioned in the title, does Tianshou support high dimensional action spaces? For instance, if I want a neural network to output an action, which is composed of 8 independent actions and each action is sampled from a discrete distribution (1, 2, 3, ..., 100).  For DQN, I have to use a NN with an output size of $100^8$. This makes the NN hard to train and lacks scalability.

Thus, I'd like to ask if Tianshou supports high dimensional action spaces, e.g., the **MultiDiscrete** action in gym?  or how to modify Tianshou to support this?

**Comment by Trinkle23897** [comment]
> As mentioned in the title, does Tianshou support high dimensional action spaces? For instance, if I want a neural network to output an action, which is composed of 8 independent actions and each action is sampled from a discrete distribution (1, 2, 3, ..., 100). For DQN, I have to use a NN with an output size of $100^8$. This makes the NN hard to train and lacks scalability.

I think it is better to use other algorithms rather than DQN in this scenario. Since DQN's representation ability is conditioned on the action space, indeed through a naive way it should memorize 100^8 Q function.
You can have a look at other algorithms such as PPO or SAC-discrete. They can directly model the whole action space instead of memorizing each Q.

> Thus, I'd like to ask if Tianshou supports high dimensional action spaces, e.g., the **MultiDiscrete** action in gym? or how to modify Tianshou to support this?

Yes, it is supported without any modification. The action could be a scalar, a np.ndarray, or a dict in our library, same as state.

**Comment by ryanhuang1014** [comment]
> I think it is better to use other algorithms rather than DQN in this scenario. Since DQN's representation ability is conditioned on the action space, indeed through a naive way it should memorize 100^8 Q function.
> You can have a look at other algorithms such as PPO or SAC-discrete. They can directly model the whole action space instead of memorizing each Q.

Thx, I find that the policy-based algorithms are suitable for my problem.

> Yes, it is supported without any modification. The action could be a scalar, a np.ndarray, or a dict in our library, same as state.

I just refer to the implementation in the stable-baselines lib and find that it uses the  **MultiCategoricalProbabilityDistribution** to sample multiple actions simultaneously. However, I do not find such distribution in Tianshou, the **dist.py** only has the Diaguassian dist, so how to solve my problem?  Can you give some examples in the source code or should I develop new dist myself?

**Comment by Trinkle23897** [comment]
> I just refer to the implementation in the stable-baselines lib and find that it uses the **MultiCategoricalProbabilityDistribution** to sample multiple actions simultaneously. However, I do not find such distribution in Tianshou, the **dist.py** only has the Diaguassian dist, so how to solve my problem? Can you give some examples in the source code or should I develop new dist myself?

No need to implemented it. The `torch.distributions.Categorical` has provided this thing:

```python
In [6]: import torch

In [7]: d = torch.distributions.Categorical(torch.rand([64, 8, 100]))

In [8]: d.sample()
Out[8]: 
tensor([[14, 62, 84, 76, 57, 34, 82, 33],
        [57, 12, 42, 38, 65, 54,  4, 14],
        [73, 36, 52, 22, 23, 81, 71, 23],
        [27, 48, 87, 94, 49,  4, 62, 95],
        [94, 99, 42, 91, 29, 82, 49, 35],
...

In [9]: d.sample().shape
Out[9]: torch.Size([64, 8])
```
So the only thing you need to do is to pass a tensor with shape [batch_size, 8, 100] into the Categorical distribution.

**Comment by ryanhuang1014** [comment]
> No need to implemented it. The `torch.distributions.Categorical` has provided this thing:
> 
> ```python
> In [6]: import torch
> 
> In [7]: d = torch.distributions.Categorical(torch.rand([64, 8, 100]))
> 
> In [8]: d.sample()
> Out[8]: 
> tensor([[14, 62, 84, 76, 57, 34, 82, 33],
>         [57, 12, 42, 38, 65, 54,  4, 14],
>         [73, 36, 52, 22, 23, 81, 71, 23],
>         [27, 48, 87, 94, 49,  4, 62, 95],
>         [94, 99, 42, 91, 29, 82, 49, 35],
> ...
> 
> In [9]: d.sample().shape
> Out[9]: torch.Size([64, 8])
> ```
> 
> So the only thing you need to do is to pass a tensor with shape [batch_size, 8, 100] into the Categorical distribution.

I get your point. My real problem is how to get multiple actions simultaneously. For instance, a neural network gets an input tensor which is shaped in (24,). Then how to get an action vector shaped of (8, ) and each action element is sampled from a categorical distribution from 0 to 100. 

As the input batch_size is 1 in this example, I have no idea how to use Tianshou to get the desired output or how to set the network architecture to get the desired output?  I am not sure how to set the output size of the neural network?

**Comment by Trinkle23897** [comment]
Just construct a mapping: (bsz, 24) -> (bsz, 8, 100).
I think this is trivial if you have tried to use PyTorch to construct a network, (and this is not related to Tianshou), for example:
```python
m = torch.nn.Linear(24, 800)
input = torch.rand(64, 24)
out = m(input)  # here, (bsz, 800)
out = out.reshape([out[0], 8, 100])  # here is what you want, (bsz, 8, 100)
# and use dist = torch.distributions.Categorical(out); action = dist.sample() to get the action, with action.shape == (64, 8)
```
Maybe I misunderstand something you've mentioned?

**Comment by ryanhuang1014** [comment]
I think this is what I want. I am new to DRL and Tianshou.
Thanks very much.

> Just construct a mapping: (bsz, 24) -> (bsz, 8, 100).
> I think this is trivial if you have tried to use PyTorch to construct a network, (and this is not related to Tianshou), for example:
> 
> ```python
> m = torch.nn.Linear(24, 800)
> input = torch.rand(64, 24)
> out = m(input)  # here, (bsz, 800)
> out = out.reshape([out[0], 8, 100])  # here is what you want, (bsz, 8, 100)
> # and use dist = torch.distributions.Categorical(out); action = dist.sample() to get the action, with action.shape == (64, 8)
> ```
> 
> Maybe I misunderstand something you've mentioned?
