### ISSUE TITLE
assignment with heterogeneous batches

### ISSUE THREAD

**Issue by youkaichao** [thu-ml/tianshou#163]
In #142 , we specify the standard behavior of aggregating heterogeneous batches. Here we discuss assignment with heterogeneous batches.

In Tianshou 0.2.5, batch assignment ``b0[index] = b1`` requires that b0 and b1 are homogeneous (they have the same [structure](https://tianshou.readthedocs.io/en/latest/tutorials/batch.html#hierarchical-named-tensors)), but sometimes we need to deal with assignment with heterogeneous batches.

Consider the following examples with reserved keys:

```python
x = Batch(a=[1, 2, 3, 4], b=Batch())
y = Batch(a=Batch(), b=[5, 8])
x[np.array([0, 1])] = y
```

```python
x = Batch(a=[1, 2, 3, 4], b=Batch())
y = Batch(b=[5, 8])
x[np.array([0, 1])] = y
```

```python
x = Batch(a=[1, 2, 3, 4])
y = Batch(a=Batch(), b=[5, 8])
x[np.array([0, 1])] = y
```

What are the natural answers to these code snippets?

Just raising exceptions is a possible solution, but I think it is not enough.  From the rationale of reserved keys, I think assignment with heterogeneous batches should be allowed when they have clear meaning.

An example of usage is in async simulation: I reset all environments and gather the initial observation & actions, but do not know about the reward & info, so I have a ``data = Batch(obs=xxx, act=xxx, info=Batch())``. After one round of async simulation, environments 1 and 3 returned their next observations, so I have ``stepped_data = Batch(obs_next=xxx, info=xxx, rew=xxx)``. Then I have to set them back to the data, by ``data[np.array([1, 3])] = stepped_data``.

For any [key chain](https://tianshou.readthedocs.io/en/latest/tutorials/batch.html#aggregation-of-heterogeneous-batches) k, there are 3 cases:

1. data[k] is non-reserved but stepped_data[k] is reserved or does not exist (e.g. k='obs'), then I expect that data[k] is not changed after the assignment ``data[index] = stepped_data``

2. data[k] is reserved or does not exist but stepped_data[k] is non-reserved (e.g. k='obs_next'), then I expect that data[k] will be filled with zeros first, and then ``data[k][index] = stepped_data[k]`` works.

3. both data[k] and stepped_data[k] are non-reserved, this is easy, just do the assignment ``data[k][index] = stepped_data[k]``.

**Comment by youkaichao** [comment]
For case 2, when data[k] needs to be filled with zeros, we need to know the length. This can be achieved just like ``Batch.cat_`` with an internal version ``Batch.cat__`` to work with length hints.

**Comment by duburcqa** [comment]
Just to clarify, you are not really discussing assignment, since assignment only consist in setting of the value of a reference (a view of the original data), in this case a slice. Here, you are hijacking the operator not to get a view but to do some fancy stuff such as memory allocation.

I'm not saying it must not be done, but that is very far from numpy standard.

I'm waiting for @Trinkle23897 's opinion before giving mine.

**Comment by youkaichao** [comment]
It is about slicing and setting items. Slicing a Batch will return a view and no memory allocation is needed. But when assigning (setting) items with heterogeneous structures, conversions are needed and sometimes memory allocation is necessary, e.g. in c++ when we use ``a[0] = b`` but b needs to be converted to a compatible type, a temporary object is created ``c = sometype(b); a[0] = c``, and it is ok if constructing ``c`` needs memory allocation.

**Comment by duburcqa** [comment]
> It is about slicing and setting items. Slicing a Batch will return a view and no memory allocation is needed. But when assigning (setting) items with heterogeneous structures, conversions are needed and sometimes memory allocation is necessary, e.g. in c++ when we use a[0] = b but b needs to be converted to a compatible type, a temporary object is created c = sometype(b); a[0] = c, and it is ok if constructing c needs memory allocation.

Yes, but here we are talking of memory allocation for a[0], which is a completely different story.

**Comment by Trinkle23897** [comment]
```python
x = Batch(a=[1, 2, 3, 4], b=Batch())
y = Batch(a=Batch(), b=[5, 8])
x[np.array([0, 1])] = y

x == Batch(a=[?, ?, 3, 4], b=[5, 8, 0, 0])
```
```python
x = Batch(a=[1, 2, 3, 4], b=Batch())
y = Batch(b=[5, 8])
x[np.array([0, 1])] = y

x == Batch(a=[?, ?, 3, 4], b=[5, 8, 0, 0])
```
```python
x = Batch(a=[1, 2, 3, 4])
y = Batch(a=Batch(), b=[5, 8])
x[np.array([0, 1])] = y

x == Batch(a=[?, ?, 3, 4], b=[5, 8, 0, 0])
```

I'm not sure whether to keep `?` as original or set to 0. Just my first thought, I tend to set `?` to 0. Because when you extract x[0] from x, x[0].a should be None or 0 instead of previous "garbage" data.

My proposal:
1. check if \_\_setitem\_\_(index) -- isinstance(index, np.ndarray (1-dim))
2. use Batch.empty_(index)
3. do assignment

Btw, this seems unnatural in some way.

**Comment by Trinkle23897** [comment]
> I'm not saying it must not be done, but that is very far from numpy standard.

I think it's okay because we cannot limit ourselves inside numpy or pytorch since we want to support more. My first concern is usability.

**Comment by duburcqa** [comment]
> I think it's okay because we cannot limit ourselves inside numpy or pytorch since we want to support more. My first concern is usability.

I don't agree. If big tech company like facebook with a lot of human resources decided to use the same standard for pytorch than numpy, I don"t see why a small project like Tianshou would have the need to do fancy stuff. For me, doing something unexpected for the user is what killed tensorflow. Following the standard is the key of usability.

I would rather implement another dedicated class inheriting from Batch to add exotic features.

**Comment by youkaichao** [comment]
> Because when you extract x[0] from x, x[0].a should be None or 0 instead of previous "garbage" data.

previous data are not garbage data, e.g. in the async environment example, they are actual observations and must be kept. I think we should keep as much information as possible. If they are garbage data, keep them is ok; if they are not, they must be kept. So why not keep them as they are?

**Comment by Trinkle23897** [comment]
> For me, doing something unexpected for the user is what killed tensorflow. Following the standard is the key of usability.

I'd like to hear more stories.

> I would rather implement another dedicated class inheriting from Batch to add exotic features.

This is a practical way. I agree.

**Comment by duburcqa** [comment]
> previous data are not garbage data, e.g. in the async environment example, they are actual observations and must be kept. I think we should keep as much information as possible. If they are garbage data, keep them is ok; if they are not, they must be kept. So why not keep them as they are?

Why not rather allow multidimensional slicing like `a[0, [1,2,4]]` ? I think it is way more natural, follow the standard, and is flexible enough.

**Comment by youkaichao** [comment]
> I don"t see why a small project like Tianshou would have the need to do fancy stuff

For Batch with non-reserved keys, Batch is compatible with numpy standard even after adding these features. Reserved keys are features of Tianshou Batch, and there are no mature standards to follow.

**Comment by duburcqa** [comment]
> Reserved keys are features of Tianshou Batch, and there are no mature standards to follow.

Indeed, and regarding this point we can do whatever we want, but the modifications you are proposing are going beyond this.

**Comment by youkaichao** [comment]
> Why not rather allow multidimensional slicing like a[0, [1,2,4]] ?

How to use multidimensional slicing to support the requirement of async simulation as mentioned in [the first note of this issue](https://github.com/thu-ml/tianshou/issues/163#issue-665103186)?

**Comment by youkaichao** [comment]
> but the modifications you are proposing are going beyond this.

Can you elaborate on that? To me it seems I'm only proposing a specific behavior for slicing and assignment with heterogeneous batches, which is not in the scope of numpy or pytorch 🤔

**Comment by duburcqa** [comment]
> How to use multidimensional slicing to support the requirement of async simulation as mentioned in the first note of this issue?

I don't see what is troubling who. You get the first observation, since you know `envs_num` you can reserve the memory as usual, doing `_create_value`, then you can use `batch.obs[cur_iter, envs_ready_id] = obs_from_async_env`. Am I missing something ?

**Comment by youkaichao** [comment]
> batch.obs[cur_iter, envs_ready_id] = obs_from_async_env

What is the ``cur_iter``?

**Comment by duburcqa** [comment]
> Can you elaborate on that? 

Slicing is suppose to be a view, so combining it with assignment is not supposed to create data (for the left side term), otherwise it is not a view by definition.

**Comment by duburcqa** [comment]
> What is the cur_iter?

Can you provide a snippet of what you are doing in collector that requires the features we are discussing ?

**Comment by Trinkle23897** [comment]
~~what about these results~~ @youkaichao 
```python
In [11]: x = Batch(a=torch.tensor([1, 2, 3, 4]), b=Batch()) 
    ...: y = Batch(a=[5, 8]) 
    ...: x[np.array([0, 1])] = y 
```
```python
In [11]: x = Batch(a=np.array([1, 2, 3, 4]), b=Batch()) 
    ...: y = Batch(a=['a', 'b']) 
    ...: x[np.array([0, 1])] = y
```

~~More corner cases to be added.~~

**Comment by duburcqa** [comment]
> More corner cases to be added.

I don't think this case is likely to happen. I don't think it is necessary to handle them explicitly.

**Comment by Trinkle23897** [comment]
> > More corner cases to be added.
> 
> I don't think this case is likely to happen. I don't think it is necessary to handle them explicitly.

Yes, after a second thought, this is not related to this topic... my bad

**Comment by Trinkle23897** [comment]
> > What is the cur_iter?
> 
> Can you provide a snippet of what you are doing in collector that requires the features we are discussing ?

I think this is the example:

> An example of usage is in async simulation: I reset all environments and gather the initial observation & actions, but do not know about the reward & info, so I have a `data = Batch(obs=xxx, act=xxx, info=Batch())`. After one round of async simulation, environments 1 and 3 returned their next observations, so I have `stepped_data = Batch(obs_next=xxx, info=xxx, rew=xxx)`. Then I have to set them back to the data, by `data[np.array([1, 3])] = stepped_data`.

I think there is another way: we can use the original format of Batch per env ([Batch0, Batch1, Batch2, ...]), and once we want to perform batch-process, we concat them to one Batch. This is somewhat time-consuming and memory-consuming but can be implemented without any other extra code.

**Comment by youkaichao** [comment]
I have cleaned up the code snippet to make it more clear:

```python
# _ready_env_ids holds the ids of ready environments
# data holds transitions in _ready_env_ids, finished (obs_next, rew, done, act, obs) or unfinished (just obs and act)
# whole_data holds transitions in all environments, finished or unfinished

data = whole[_ready_env_ids] # readily handled, done once

# loop:
data.act = policy(data.obs) # get act
whole[_ready_env_ids] = data # ****  store obs and act for ready environments, slice and setitem simultaneously ******
obs_next, rew, done, info = env.step(data.act, _ready_env_ids)
_ready_env_ids = np.array([i['env_id'] for i in info]) # update ready env ids
data = whole[_ready_env_ids] # get data for returned environments to fill the obs_next, rew, done, info, readily handled
data.obs_next = obs_next ... # update data
whole[_ready_env_ids] = data # ****  store obs_next, rew, done, info for ready environments, slice and setitem simultaneously ******

```

**Comment by duburcqa** [comment]
> I think this is the example:

I would simply loop over available fields, as for a dict: 
```
for k, v in stepped_data.items():
    data[k][np.array([1, 3])] = v
```

**Comment by youkaichao** [comment]
> I would simply loop over available fields, as for a dict:

The situation is far more complicated. For the ``obs_next `` field, ``data[k]`` is initially empty.

**Comment by duburcqa** [comment]
> The situation is far more complicated. For the obs_next field, data[k] is initially empty.

Not really, just `try/except` + `_create_value` as usual.

**Comment by youkaichao** [comment]
Yeah, actually we can make every function of Batch outside of Batch so that users can customize their behavior, but if users need to manipulate Batch in such a fine-grained level, we should consider whether the design of Batch is good enough.

Clearly, ``_create_value `` is an internal method for Batch, and we should rethink the implementation when we ever try to import ``_create_value `` elsewhere.

**Comment by duburcqa** [comment]
> Yeah, actually we can make every function of Batch outside of Batch so that users can customize their behavior, but if users need to manipulate Batch in such a fine-grained level, we should consider whether the design of Batch is good enough.

That's make no sense. `np.ndarray` class is good enough, though it is never used alone...

> Clearly, _create_value is an internal method for Batch, and we should rethink the implementation when we ever try to import _create_value elsewhere.

I don't think so. It is an internal method for something more powerful than Batch itself. Adding a new class on top of it having the features you mentioned, including _create_value is the way to go, not making Batch itself more complicated than it already is. So I would rather make of more generic `buffer` class, having those features, and inherits the other buffer classes from it.

**Comment by youkaichao** [comment]
> Slicing is suppose to be a view

That's not always true. [here](https://stackoverflow.com/questions/46308370/views-and-copies-confusion-with-numpy-arrays-when-combining-index-operations) is an example.

**Comment by Trinkle23897** [comment]
> I don't think so. It is an internal method for something more powerful than Batch itself. Adding a new class on top of it having the features you mentioned, including _create_value is the way to go, not making Batch itself more complicated than it already is. So I would rather make of more generic `buffer` class, having those features, and inherits the other buffer classes from it.

I tend to agree with a half since the implementation of ListReplayBuffer uses some hacks to bypass the auto-convert. It's the same as _create_value to use the internal structure or method, but if _create_value is needed in other places, it should not be an internal method.

**Comment by duburcqa** [comment]
> That's not always true. here is an example.

That's not making your point. It is still a view. A view of a copy, but still of view. To see it differently, you are always dealing the a reference of the left side of the assign by standard. Here you are proposing to do something else. It is the same of "a.transpose() = b". This is not allowed, but you enable it through overloading of attribute assignment.

**Comment by youkaichao** [comment]
> Adding a new class on top of it having the features you mentioned, including _create_value is the way to go, not making Batch itself more complicated than it already is.

I don't agree. If we add this feature, users who do not rely on it will never notice it, but users who rely on it will need it. It is totally backward-compatible.

As for creating a new class, if we have three classes with inheritance A -> B -> C with more and more features, why not just keep a C class, then? Inheritance works when we have to branch several different behavior / implementations, for example have a generic ReplayBuffer class and several implementations. Adding new features like this should not be achieved by creating new classes.

**Comment by youkaichao** [comment]
> Slicing is suppose to be a view, so combining it with assignment is not supposed to create data (for the left side term), otherwise it is not a view by definition.

I think this does not make your point, either. Slicing is suppose to be a view, and **we can modify the data through its view**. This is allowed. Why to restrict ourselves to not creating data? 

I checked the [manual of numpy](https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html#What-is-a-view-of-a-NumPy-array?) and the definition of view is as follows:

> As its name is saying, it is simply another way of viewing the data of the array. Technically, that means that the data of both objects is shared.

So views just mean they share the same underlying data with original ndarrays.

**Comment by duburcqa** [comment]
> I think this does not make your point, either. Slicing is suppose to be a view, and we can modify the data through its view. This is allowed. Why to restrict ourselves to not creating data?

Because modifying as nothing to do with creating. That's the whole point. Reference to part of an object, while you are modifying the whole object, does not make any sense.

**Comment by duburcqa** [comment]
> So views just mean they share the same underlying data with original ndarrays.

Precisely, that's why you should not modify the whole object, when manipulating part of it.It is a non-sense in a programming point of view. And allocating memory is doing it. Internally, usually all the original memory is wiped out, and a new allocation is created. So you break the sharing principal since the memory has changed before and after assignment.

**Comment by youkaichao** [comment]
> Reference to part of an object, while you are modifying the whole object, does not make any sense.

I don't agree. Reserved keys are new features in Batch and you cannot expect everything in ndarray to happen in Batch. For example, ``x=Batch(a=[1, 2, 3, 4], b=Batch()); y=x[np.asarray([0, 1])];``, y is actually not a view of x, because we cannot modify x.a by using y.a, i.e. **views of Batch are different from views of ndarray**.

We are not changing the behavior with regard to ndarray anyway, we are proposing new behaviors for reserved keys. Since reserved keys are not ndarrays, users can expect that they have some specific behavior.

**Comment by Trinkle23897** [comment]
> > So views just mean they share the same underlying data with original ndarrays.
> 
> Precisely, that's why you should not modify the whole object, when manipulating part of it.It is a non-sense in a programming point of view. And allocating memory is doing it. Internally, usually all the original memory is wiped out, and a new allocation is created. So you break the sharing principal since the memory has changed before and after assignment.

I think giving a code snippet of this behavior is much more helpful to our discussion.

**Comment by duburcqa** [comment]
> We are not changing the behavior with regard to ndarray anyway, we are proposing new behaviors for reserved keys. Since reserved keys are not ndarrays, users can expect that they have some specific behavior.

I'm not talking about reserved keys but already allocated memory.

Anyway, I'm giving up. Do whatever you want. I still spend to much time discussing this and I think my point is clear enough. We are going in circle now.

**Comment by youkaichao** [comment]
> I'm not talking about reserved keys but already allocated memory.

But memory allocation only occurs when the batch has reserved keys.

> Anyway, I'm giving up. Do whatever you want.

Maybe that's not a good way to cooperate. Discussion is needed to settle the dispute. I'm not pursuing this feature by any means. We just need to discuss until it is clear.

Or maybe we can keep it aside and discuss later, a common way for dealing with dispute.

**Comment by duburcqa** [comment]
> Maybe that's not a good way to cooperate. Discussion is needed to settle the dispute. I'm not pursuing this feature by any means. We just need to discuss until it is clear.
Or maybe we can keep it aside and discuss later, a common way for dealing with dispute.

Indeed, but I need to compromise between discussing Tianshou's issues and make a living.

I'm here to help you making good choices. Once I made my point, you can do as you please, since it is not my project but yours. You are the ones responsible for making Tianshou great, not me (even if I contribute sometimes on small PR, I would rather avoid it). So if in the hand we don't agree on a design choice, you are free to do as you want. I just want you to be aware of the consequences of each of them. 

I don't think I'm here to take part of disputes, but rather to share my knowledge on specific point. Keep in mind Tianshou is not my work, and I don't rely on it to do my job, I'm just happy to help you on my spare time.

**Comment by youkaichao** [comment]
> Tianshou is not my work, and I don't rely on it to do my job, I'm just happy to help you on my spare time.

I think that's the point of open-source projects, we cooperate to create a project with the help of everyone interested, and meet friends who we never met before. Dispute will arise sometimes, but cooperation is our main theme.

Tianshou is not my work, either. I just wanted to learn reinforcement learning and discovered this elegant framework. So the decision is left to @Trinkle23897 after we have stated our respective opinions.

I'll try my best to improve Tianshou when I have time, but in fact I have some research to do and not a full-time developer of Tianshou. After #134 , I will not code so often, either.

Anyway, happy open-sourcing!

**Comment by duburcqa** [comment]
>  I will not code so often, either.

Ok so are contribution is similar, and you can understand I have very little time for disputes. I'm working for a company, pursuing a phd, and on the first stage of running my own, so my schedule is already kinda overbooked.

**Comment by Trinkle23897** [comment]
I think making `_create_value` to a public static method like `Batch.create` can resolve the things above.

**Comment by youkaichao** [comment]
> I think making _create_value to a public static method like Batch.create can resolve the things above.

The function name is not the point. Now I solve #134 with minimal modification: leave Batch unchanged, and add a function in collector.
