### ISSUE TITLE
speed testing in case of parallel/distributed computation 

### ISSUE THREAD

**Issue by AlessandroZavoli** [thu-ml/tianshou#164]
- [ x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

Does tianshou support distributed computation (e.g., on a cluster) for collecting experience?
Is there any test I can run to understand how the computation scale with multiple cores available?
 
Alessandro

**Comment by Trinkle23897** [comment]
> Does tianshou support distributed computation (e.g., on a cluster) for collecting experience?

Currently we mainly support a single node of small-medium size of experiment, but you can use `RayVectorEnv` for distributed sampling.

> Is there any test I can run to understand how the computation scale with multiple cores available?

PR #143 is our first step. More to be added.

**Comment by p-veloso** [comment]
Hi @Trinkle23897,

I am running an experiment with Tianshou in a computer with multiple CPU cores and 2 GPUs. Is it possible to take advantage of that with RayVectorEnv?

Thanks.

**Comment by Trinkle23897** [comment]
> Hi @Trinkle23897,
> 
> I am running an experiment with Tianshou in a computer with multiple CPU cores and 2 GPUs. Is it possible to take advantage of that with RayVectorEnv?
> 
> Thanks.

Of course yes. It is very similar to SubprocVectorEnv (same API, including wait_num and timeout) under the single node config.

**Comment by p-veloso** [comment]
Nice. I have no experience on that. 
By changing from VectorEnv to RayVectorEnv and using the specific arguments will Tianshou take care of the optimization? 
Or do I have to explicitly describe who is responsible for each environments?
If possible, send me some references or tutorials for this topic. 
Thanks.

**Comment by Trinkle23897** [comment]
> By changing from VectorEnv to RayVectorEnv and using the specific arguments will Tianshou take care of the optimization?

VectorEnv is not optimized. It uses the for-loop (typically for debugging). SubprocVectorEnv, ShmemVectorEnv and RayVectorEnv are truly parallel executed. All of these three are optimized.

> Or do I have to explicitly describe who is responsible for each environment?

Nope.

> If possible, send me some references or tutorials for this topic.

https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#parallel-sampling
