### ISSUE TITLE
SubprocVectorEnv is not released when collector is closed

### ISSUE THREAD

**Issue by ChenDRAG** [thu-ml/tianshou#166]
```
env_subproc_init = SubprocVectorEnv(
        [lambda: SimpleEnv() for _ in range(8)])
for _ in range(2000):
        c = Collector(policy, env_subproc_ini, buffer)
        c.close()
```
A broken pipe error will be reported. Seems that SubprocVectorEnv is not actually released and cannot be reused once assigned to a collector. I don't know if this can be counted as a bug.
`BrokenPipeError: [Errno 32] Broken pipe
`

**Comment by ChenDRAG** [comment]
I think we should at least give users a hint once the closed subprocvec is used again. Or move function in init() to reset().

**Comment by Trinkle23897** [comment]
`collector.close` is going to be removed in #179 so this issue will close.
