### ISSUE TITLE
why is the value of `collect_per_step` passed into `n_episode`?

### ISSUE THREAD

**Issue by wiljohnhong** [thu-ml/tianshou#167]
https://github.com/thu-ml/tianshou/blob/bd9c3c7f8d144448c44a350828b2c5222298bd8e/tianshou/trainer/onpolicy.py#L87

I see that the parameter `collect_per_step` in `onpolicy_trainer()` function refers to "the number of frames the collector would collect before the network update", but its value is finally passed into the `n_episode` parameter in `collect()`, I get quite confused about this. Do I misunderstand anything?

**Comment by Trinkle23897** [comment]
Sorry. Indeed it should be "the number of episodes the collector would collect before the network update". It's my fault and I'll fix it right now. Thank you for pointing out!

**Comment by wiljohnhong** [comment]
thanks

**Comment by wiljohnhong** [comment]
thanks, and I recommend that tianshou can allow us to choose whether to collect a fixed num of episodes or a fixed num of timesteps to collect in `collect()`, since in some environments an episode may consist of a large num of timesteps and we do not want to train after finishing the whole episode, and in some other cases the length of an episode could vary greatly.

**Comment by Trinkle23897** [comment]
> I recommend that tianshou can allow us to choose whether to collect a fixed num of episodes or a fixed num of timesteps to collect in `collect()`, since in some environments an episode may consist of a large num of timesteps and we do not want to train after collect the whole episode, and in some other cases the length of an episode could vary greatly.

If I have time I'll fix it.

**Comment by youkaichao** [comment]
> in some environments an episode may consist of a large num of timesteps and we do not want to train after finishing the whole episode

I think there is an easy workaround without modifying Tianshou: you can truncate the environment to finish after a certain amount of steps. However, in many cases, the reward is very sparse (only available when the episode finishes) and training with partial episodes makes no sense (the rewards are all zero). Therefore, I think only allowing collecting full episodes works in most cases. If one indeed needs to train with partial episodes, they can wrap the environment to finish after a certain amount of steps.
