### ISSUE TITLE
Shared preprocess_net for actor and critic network

### ISSUE THREAD

**Issue by wuchlei** [thu-ml/tianshou#169]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
```
import tianshou, torch, sys
print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
0.2.5 1.3.1 3.7.5 (default, Apr 19 2020, 20:18:17) 
[GCC 9.2.1 20191008] linux
```
Thanks for the good work!

So I've just migrated my envrionment from the repo [pytorch-a2c-ppo-acktr-gail](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail) to Tianshou. My code uses a2c for agent decision.
What I found out is that, even after tuning the hyper-parameters, Tianshou is still almost two-times slower than that simple implementation. The reason I can think of is that Tianshou uses separated preprocessing network for actor and critic network, which will embed the same state twice. However, the other repo only embeds state once.
Are there any other reasons you can think of? Thanks.

The fps of two repos are attached below.

[pytorch-a2c-ppo-acktr-gail](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail) 
![批注 2020-07-28 001139](https://user-images.githubusercontent.com/3911539/88576416-ff3b8d80-d077-11ea-856e-63f4c0e35752.png)

Tianshou
![批注 2020-07-28 020406](https://user-images.githubusercontent.com/3911539/88576419-01055100-d078-11ea-822b-bd1f394c481b.png)

**Comment by Trinkle23897** [comment]
Thanks! The issue you mentioned is indeed a reason, but you can change this network to the desired style, something like:

```python
actor.forward(s) -> (logits, preprocess_state)
critic.forward(preprocess_state) -> V(s)
```

And there's another thing: In order to store the data chronologically in one buffer with multi-envs, we use many cache-buffer. That is to say, a data frame is stored twice but save once. In #105 we have discussed this issue but we are willing to hear if you have a better solution.

**Comment by wuchlei** [comment]
The cache-buffer problem may be because you have a hard constraint on collecting a full episode, while the other repo simply stops after collecting enough steps, which doesn't really hurt the performance, from my experience.
