### ISSUE TITLE
Inverse reinforcement learning

### ISSUE THREAD

**Issue by AlessandroZavoli** [thu-ml/tianshou#173]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:

  ```
Do you think tianshou may support inverse reinforcement learning? 
https://ai.stanford.edu/~ang/papers/icml04-apprentice.pdf
http://martin.zinkevich.org/publications/maximummarginplanning.pdf

**Comment by Trinkle23897** [comment]
Yes, it is in our plan. Other algorithms include HER/Rainbow/GAIL/...

**Comment by trsh** [comment]
Gail is implemented or Wip?

**Comment by Trinkle23897** [comment]
> Gail is implemented or Wip?

In todo list
