### ISSUE TITLE
Meaning of infos during training ?

### ISSUE THREAD

**Issue by Jogima-cyber** [thu-ml/tianshou#175]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
  ```
  0.2.5 1.4.0 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
  [GCC 7.5.0] linux
  ```
Hi, what's the meaning of each info given during training ? I mean during the execution of this code :
```python
result = ts.trainer.offpolicy_trainer(
    policy, train_collector, test_collector,
    max_epoch=10, step_per_epoch=400, collect_per_step=50,
    episode_per_test=1, batch_size=32,
    train_fn=lambda e: policy.set_eps(max(1 - e / 9, 0.01)),
    test_fn=lambda e: policy.set_eps(0),
    writer=None)
```
```
[00:23, 16.90it/s, len=151.00, loss=470.232574, n/ep=1.00, n/st=151.00, rew=1364.00, v/ep=19.29, v/st=2089.12]
```
What is n/ep, n/st, rew, v/ep and v/st ?

**Comment by Trinkle23897** [comment]
https://tianshou.readthedocs.io/en/latest/api/tianshou.data.html#tianshou.data.Collector.collect
