### ISSUE TITLE
What does test_collector in trainer stand for ?

### ISSUE THREAD

**Issue by Jogima-cyber** [thu-ml/tianshou#181]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
  ```
  0.2.5 1.4.0 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) [GCC 7.5.0] linux
  ```
I'd like to clear something about test_collector in tianshou.trainer.offpolicy_trainer. I think it is used to test the policy trained on train_collector, which means that the policy isn't trained on test_collector at all and epsilon of test_collector should be set on 0. I'm I right ?

**Comment by Trinkle23897** [comment]
Yes, you are right. But from my experience, DQN with eps=0 will sometimes stack in some corner case and small epsilon helps.

**Comment by Jogima-cyber** [comment]
Thanks !
