### ISSUE TITLE
PPO for distributions without entropy

### ISSUE THREAD

**Issue by youkaichao** [thu-ml/tianshou#186]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__)
  0.2.5
  ```

Some distributions like ``torch.distributions.Binomial`` has no entropy function. PPO should work for them when the entropy weight is 0.

**Comment by Trinkle23897** [comment]
Should be all policy using entropy instead of ppo

**Comment by Trinkle23897** [comment]
But I think it is better to wrap the `distribution` to create an `entropy` method which returns 0 without changing any lines of our existing code.

**Comment by youkaichao** [comment]
> it is better to wrap the distribution to create an entropy method which returns 0 without changing any lines of our existing code.

Good idea. If users met this error, they can find this issue and try to wrap the distribution.

```python
    from torch.distributions import Binomial
    def entropy(self):
        return torch.zeros(self._batch_shape)
    Binomial.entropy = entropy # Binomial does not have entropy
```

In addition, I don't know why pytorch thinks Binomial has not entropy :(
