### ISSUE TITLE
The best practice using Tianshou for offline RL?

### ISSUE THREAD

**Issue by szrlee** [thu-ml/tianshou#188]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
What might be a best practice using Tianshou for offline RL?
Save to the buffer and pickle it to storage and then use it as an offline replay buffer (no further data gathering) for algorithm training?

![offline-RL](https://user-images.githubusercontent.com/6252426/90718133-c3e15700-e2e3-11ea-99ac-3424abe438b8.png)

This issue has some relevant discussion but I am not talking about TPU. https://github.com/thu-ml/tianshou/issues/24#issuecomment-614466071

**Comment by Trinkle23897** [comment]
> What might be a best practice using Tianshou for offline RL?
> Save to the buffer and pickle it to storage and then use it as an offline replay buffer (no further data gathering) for algorithm training?

I think so. The buffer save/load has been supported in #182. Other parts of the code are similar to imitation learning.
