### ISSUE TITLE
TRPO policy support

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [thu-ml/tianshou#190]
Is there a plan to support TRPO algorithm?

**Comment by Trinkle23897** [comment]
Possibly it will, but why not PPO first :)

**Comment by GIS-PuppetMaster** [comment]
> Possibly it will, but why not PPO first :)

Thanks for replying, I'm trying to use RL on stock trading, and according my experiment, TRPO can achieve much higher reward than PPO on this problem.

**Comment by ChenDRAG** [comment]
@GIS-PuppetMaster Will support this shortly, in 2 weeks maybe.
