### ISSUE TITLE
How to call env.render() after testing an episode?

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [thu-ml/tianshou#192]
In another word, how should I call collector.collect() in trainer with 'test_fun'

**Comment by Trinkle23897** [comment]
I don't quite understand. Could you please provide your pseudocode for the desired feature?

**Comment by GIS-PuppetMaster** [comment]
> I don't quite understand. Could you please provide your pseudocode for the desired feature?

My env only need to render the last step when the env.done == True, I noticed that the parameter 'test_fun' will be executed after one episode. So what I'm hoping is to set test_fun=env.render(), but it seems impossible because there is no way to get the reference of the env in Collector. So I'm wondering is there any way I can achieve this without change my env? For now, I achieved this by detecting if the self.done==True at the end of the env.step(), and if it's True then call self.render(), which is a verbose method.

**Comment by GIS-PuppetMaster** [comment]
I used the framework 'stableBaseline' ,which you can find in github, and I believe the Callback function class design in that framework is worth to be implemented in Tianshou.

**Comment by Trinkle23897** [comment]
> I'm wondering is there any way I can achieve this without changing my env? For now, I achieved this by detecting if the self.done==True at the end of the env.step(), and if it's True then call self.render(), which is a verbose method.

I think the same thing (like callback) is done by `preprocess_fn` of collector, you can take a look at https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#handle-batched-data-stream-in-collector

**Comment by GIS-PuppetMaster** [comment]
> > I'm wondering is there any way I can achieve this without changing my env? For now, I achieved this by detecting if the self.done==True at the end of the env.step(), and if it's True then call self.render(), which is a verbose method.
> 
> I think the same thing (like callback) is done by `preprocess_fn` of collector, you can take a look at https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#handle-batched-data-stream-in-collector

If I understand the doc right, preprocess_fun can only handle Batch data, which is limited when user want to call some customized function of env

**Comment by Trinkle23897** [comment]
Emm, you are right. I also think this can be done by a gym.wrapper:
```python
class RenderWhenDone(gym.Wrapper):
    def __init__(self, env):
        super().__init__(env)
    def step(self, action):
        obs, rew, done, info = self.env.step(action)
        if done:
            self.env.render()
        return obs, rew, done, info

env = RenderWhenDone(MyEnv())
```

And I don't think it is trivial with VectorEnv, since these environments may be terminated in different steps, which needs more lines of code when writing callbacks.

**Comment by GIS-PuppetMaster** [comment]
> Emm, you are right. I also think this can be done by a gym.wrapper:
> 
> ```python
> class RenderWhenDone(gym.Wrapper):
>     def __init__(self, env):
>         super().__init__(env)
>     def step(self, action):
>         obs, rew, done, info = self.env.step(action)
>         if done:
>             self.env.render()
>         return obs, rew, done, info
> 
> env = RenderWhenDone(MyEnv())
> ```
> 
> And I don't think it is trivial with VectorEnv, since these environments may be terminated in different steps, which needs more lines of code when writing callbacks.

Yes, maybe with the VectorEnv situation, just modify the env or use wrapper is better. Thanks for reply!
