### ISSUE TITLE
Noisy network implementation

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [thu-ml/tianshou#194]
My expected action is a tensor with softmax activation. However, when I use TD3, the current implementation will add this action_bias to the softmax-activated tensor, which breaks the action distribution.

**Comment by Trinkle23897** [comment]
I think you can pass the action_range with (-1, 1) manually so that `self._action_bias` is 0 and `self._action_scale` is 1. 
By the way, I'm going to refactor this part of the code :)

**Comment by GIS-PuppetMaster** [comment]
> I think you can pass the action_range with (-1, 1) manually so that `self._action_bias` is 0 and `self._action_scale` is 1.
> By the way, I'm going to refactor this part of the code :)

I tried but found out there is still some noise added to the action, so I use softmax in my env rather than in the ActorNet.
And I suggest to add noise to the actor network , which called 'noisy net' mentioned in a paper or blog of OpenAI, I believe I saw it on Google. According to their research, adding noise to network is better than add noise directly to the action.

**Comment by GIS-PuppetMaster** [comment]
Here is the link: https://openai.com/blog/better-exploration-with-parameter-noise/

**Comment by Trinkle23897** [comment]
> I tried but found out there is still some noise added to the action, so I use softmax in my env rather than in the ActorNet.

related to #80, I'll refactor it.

> And I suggest adding noise to the actor-network, which called 'noisy net' mentioned in a paper or blog of OpenAI, I believe I saw it on Google. According to their research, adding noise to the network is better than add noise directly to the action.

I'll consider it. Thanks for pointing out!

**Comment by GIS-PuppetMaster** [comment]
> > I tried but found out there is still some noise added to the action, so I use softmax in my env rather than in the ActorNet.
> 
> related to #80, I'll refactor it.
> 
> > And I suggest adding noise to the actor-network, which called 'noisy net' mentioned in a paper or blog of OpenAI, I believe I saw it on Google. According to their research, adding noise to the network is better than add noise directly to the action.
> 
> I'll consider it. Thanks for pointing out!

You're welcome!

**Comment by Trinkle23897** [comment]
No, since the code-refactor has not been finished yet, this cannot be closed.
