### ISSUE TITLE
I wander if there exist a doc for all the environments tianshou has implemented

### ISSUE THREAD

**Issue by garyzhang99** [thu-ml/tianshou#199]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

Hi, thank you for bring us such thorough documentation and tutorials, it really helped a lot.
When i am trying to use tianshou to implement a RL algorithm for experiment, naturally I would like use tianshou's environment.  But I can only find documentation for env's interface, so I think it would be better if there exist a doc for all the environment tianshou has already implemented.
In particular, I am interested in Go(Weiqi) environment. I noticed that right now the development of "MCTS & 7x7 Go" is still in progress, so I wander if you can **release the 7x7 Go environment tianshou used and implemented**. If writing a doc for a developing progress is too much trouble, a link to the environment's source code is good enough for me.
Thank you !

**Comment by Trinkle23897** [comment]
> When i am trying to use tianshou to implement a RL algorithm for experiment, naturally I would like use tianshou's environment. But I can only find documentation for env's interface, so I think it would be better if there exist a doc for all the environment tianshou has already implemented.

I personally do not like other platforms that wrap every environment (like rlpyt has a specific env class for Atari games), which will cause further confusion for users. In fact, it supports almost all environments following OpenAI gym's API.

> In particular, I am interested in Go(Weiqi) environment. I noticed that right now the development of "MCTS & 7x7 Go" is still in progress, so I wander if you can **release the 7x7 Go environment tianshou used and implemented**. If writing a doc for a developing progress is too much trouble, a link to the environment's source code is good enough for me.

Sure. This will release in the future. Currently, @sproblvem is creating `modelbase/MCTSPolicy` with 7x7 Go game. This has been evaluated in the previous version of tianshou (<=0.1.1, in tensorflow-version), the things to do is to migrate into the current version. But unfortunately, this part of the code is in a private repo and somewhat messy.

**Comment by Trinkle23897** [comment]
https://github.com/aigagror/GymGo
