### ISSUE TITLE
How to sample an entire epoch?

### ISSUE THREAD

**Issue by xzymustbexzy** [thu-ml/tianshou#20]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, sys
  print(tianshou.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

Hello, I'am going to implement an algorithm called [Episodic Backward Update](https://github.com/suyoung-lee/Episodic-Backward-Update), which requires sampling an entire trajectory during an epoch rather than sampling transitions randomly. So, I wonder if there is any  mechanism to achieve this feature in tianshou?

**Comment by Trinkle23897** [comment]
Just use batch_size=0, I will push the documentation in the next commit.

**Comment by Trinkle23897** [comment]
[https://tianshou.readthedocs.io/en/latest/api/tianshou.data.html#tianshou.data.Collector.sample](https://tianshou.readthedocs.io/en/latest/api/tianshou.data.html#tianshou.data.Collector.sample) 
and [https://tianshou.readthedocs.io/en/latest/api/tianshou.data.html#tianshou.data.ReplayBuffer.sample](https://tianshou.readthedocs.io/en/latest/api/tianshou.data.html#tianshou.data.ReplayBuffer.sample)

You can close this issue if it solves your question.

**Comment by xzymustbexzy** [comment]
Wow! That's awesome!!! Thanks.
