### ISSUE TITLE
Use '__slots__' to improve performance and memory usage

### ISSUE THREAD

**Issue by duburcqa** [thu-ml/tianshou#201]
I think many classes of Tianshou seem to be especially appropriate for the use of `__slots__` instead of `__dict__`. Have a look at this [stackoverflow post](https://stackoverflow.com/questions/472000/usage-of-slots) for more information. It should dramatically reduce memory usage, and reduce the access time for attributes.

**Comment by Trinkle23897** [comment]
Today it is not a good plan to use `__slot__`. I'd recommend using [treevalue](https://github.com/opendilab/treevalue).

**Comment by duburcqa** [comment]
Treevalue seems indeed a very interesting lib ! Personally I hate dm-tree and I will be more than happy to switch to your lib if it is easy to do so !

**Comment by duburcqa** [comment]
By the way, I said I would be free to work again on tianshou months ago (year?). Actually it took me more time than I would like to admit to write down my PhD manuscript (13 months!). But I submitted last Friday so it should finally happen ! Sorry about that x)

**Comment by Trinkle23897** [comment]
Huge congrats!

**Comment by duburcqa** [comment]
Thank you ! Still the defence to pass :) 

By the way, are you sure `treevalue` is a one-to-one replacement for `__slots__` ? You can use it to store class attribute easily ?

**Comment by Trinkle23897** [comment]
I'm not totally sure, but 
- from the experiments of [envpool](https://github.com/sail-sg/envpool/pull/206), it can reduce the execution time from ~400us to 2us
- they have one page benchmark result: https://opendilab.github.io/treevalue/main/comparison/dmtree.result.html

**Comment by duburcqa** [comment]
Yes I saw the benchmark ! You use it for anything else than storing and manipulating the observations and actions ?

**Comment by Trinkle23897** [comment]
Not yet

**Comment by duburcqa** [comment]
Ok but it is already terrific. I have been looking for a lib like your for years x)

**Comment by duburcqa** [comment]
What do you think about planning a zoom meeting or something together ? I would like to talk with you about how I could go back to using your tools and helping on it. I have several needs and first I would like to make sure if your suite fit my needs. I'm also interesting in discussing the relevance of envpool for me and the vision I have about what I'm try to achieve.

**Comment by Trinkle23897** [comment]
to be clear: treevalue is not "my tool". I'm also a user. But I can include @PaParaZz1 together

> planning a zoom meeting

would love to!

**Comment by PaParaZz1** [comment]
> What do you think about planning a zoom meeting or something together ? I would like to talk with you about how I could go back to using your tools and helping on it. I have several needs and first I would like to make sure if your suite fit my needs. I'm also interesting in discussing the relevance of envpool for me and the vision I have about what I'm try to achieve.

Thanks for your interest about treevalue. We are constantly developing and updating treevalue and related modules. Maybe we can discuss in our [slack channel](https://join.slack.com/t/opendilab/shared_invite/zt-v9tmv4fp-nUBAQEH1_Kuyu_q4plBssQ) first.
