### ISSUE TITLE
mujoco examples' result mismatch

### ISSUE THREAD

**Issue by zouzhene** [thu-ml/tianshou#209]
With all of ddpg, sac and td3, I get similar results like this:
![image](https://user-images.githubusercontent.com/17318149/92572185-adad3200-f2b6-11ea-842b-46df723a0098.png)

But the official results like this:
![image](https://user-images.githubusercontent.com/17318149/92572379-f1a03700-f2b6-11ea-9d21-8f2b493110f0.png)

**Comment by Trinkle23897** [comment]
This will be updated (it is the first version (v0.2.0) result). I'll take a look. Thanks!
