### ISSUE TITLE
Questions about non-identifiable episodes and limited interaction steps.

### ISSUE THREAD

**Issue by Ethanwl** [thu-ml/tianshou#221]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
Thank you for your awesome work!

Question 1:
In many cases the agent–environment interaction does not break naturally into identifiable episodes, but goes on continually without limit.(This description is from Sutton‘s book.)
This means that 'done' is always 'False'. Can I use tianshou in this situation? How should I do?

Question 2:
I want to solve a problem which can be formulated as reinforcement learning, but there are only about 1000 interactions between the agent and the environment. Can this problem be solved with any reinforcement learning algorithm? Is there any suggestion?

**Comment by Trinkle23897** [comment]
> In many cases the agent–environment interaction does not break naturally into identifiable episodes but goes on continually without limit. (This description is from Sutton‘s book.)
> This means that 'done' is always 'False'. Can I use tianshou in this situation? How should I do it?

You can add a timelimit environment wrapper, for example, 
```python
from gym import wrappers
env = wrappers.TimeLimit(your_env, max_episode_steps=1000)
```
and pass this wrapped env to the training process.

> I want to solve a problem that can be formulated as reinforcement learning, but there are only about 1000 interactions between the agent and the environment. Can this problem be solved with any reinforcement learning algorithm? Is there any suggestion?

Do you mean the overall number of interactions is 1000? I don't think there is any RL algorithm that can handle it since it needs a very very low-sample-complexity algorithm but currently, no one can do this, to the best of my knowledge.

**Comment by Ethanwl** [comment]
Thank you for your answering. I think that at least the rational number of interactions is about 100,000 to 1,000,000. Is that right?

**Comment by Trinkle23897** [comment]
Yup
