### ISSUE TITLE
Double DQN - infeasible actions

### ISSUE THREAD

**Issue by Jogima-cyber** [thu-ml/tianshou#222]
Hello there ! I’ve seen that it is possible to handle infeasible action when using a DQN policy when selecting next action. But in my opinion it doesn’t handle infeasible actions when computing the target q-value of a state action when using double DQN. Is this implemented ?

**Comment by Trinkle23897** [comment]
Could you please give an example of "infeasible action"?

**Comment by Jogima-cyber** [comment]
Take for example the 2048 game, action space is UP, LEFT, RIGHT, DOWN. But in some case the agent cannot swipe in one particular direction, that's an infeasible action.

**Comment by Jogima-cyber** [comment]
We don't want the agent to select the action with the best Q-value when this action is infeasible. But also, when updating in a double Q-network the target network, we don't want to update it with the Q-value of an infeasible action.

**Comment by Trinkle23897** [comment]
> Take for example the 2048 game, action space is UP, LEFT, RIGHT, DOWN. But in some case the agent cannot swipe in one particular direction, that's an infeasible action.

Aha, this can be done by adding a mask. U can refer to the example in `test/multiagent/`, in short, add a 0-1 array as mask into the observation.

**Comment by Jogima-cyber** [comment]
Ok, I think this mask prevents target Q network to update with a target Q-value of an infeasible action. But how do we prevent agent to select an infeasible action ?

**Comment by Jogima-cyber** [comment]
I mean in epsilon greedy strategy, how do we prevent agent to select an infeasible action ?

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/blob/eec0826fd3a7c3066f68a5cc8b0b7ac145a6f1ac/tianshou/policy/modelfree/dqn.py#L107-L165
Here, we add a -inf into the Q value if the corresponding action is masked.

**Comment by Jogima-cyber** [comment]
> I mean in epsilon greedy strategy, how do we prevent agent to select an infeasible action ?

And for this question ?

**Comment by Jogima-cyber** [comment]
Thanks for your answers by the way ! You're always super fast and super relevant !

**Comment by Trinkle23897** [comment]
> > I mean in epsilon greedy strategy, how do we prevent agent to select an infeasible action?
> 
> And for this question?

This is the same. See the code here:
https://github.com/thu-ml/tianshou/blob/eec0826fd3a7c3066f68a5cc8b0b7ac145a6f1ac/tianshou/policy/modelfree/dqn.py#L158-L164

**Comment by Jogima-cyber** [comment]
Okay, so in my custom env I have to add a mask to the observation. Thanks I've seen in https://github.com/thu-ml/tianshou/blob/master/test/multiagent/tic_tac_toe_env.py how to do that.
