### ISSUE TITLE
Some atari envs use 30GB of RAM

### ISSUE THREAD

**Issue by imoneoi** [thu-ml/tianshou#225]
YarsRevenge atari env uses 30GB of RAM (with 1M replay buffer), as other envs usually use 8~10GB ram with the same setting. Also, BattleZone uses 20GB and NameThisGame uses 48GB.

**Comment by Trinkle23897** [comment]
These games may encounter an infinite-loop and reach the max episode step (typically 100000 or 400000). Since our collector needs to collect a full-length episode at each time currently, this issue cannot be avoided and the temporal solution is to add another `gym.wrappers.TimeLimit`.

**Comment by Trinkle23897** [comment]
This is resolved by #280. After v0.4.0 we no longer use ListReplayBuffer, so that there will be no memory leak issues in the future.
