### ISSUE TITLE
Can't install the library

### ISSUE THREAD

**Issue by wanghui589** [thu-ml/tianshou#226]
- [ +] I have marked all applicable categories:
    + [ +] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ +] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [+ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [+ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
I want to install this library, but it appears
ERROR: Could not find a version that satisfies the requirement torch>=1.4.0 (from tianshou==0.3.0rc0) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.4.0 (from tianshou==0.3.0rc0)
Can someone tell me how to solve it, thanks
I have tried to install from source, but it didn't work
 import tianshou
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\19395\Downloads\tianshou\tianshou\__init__.py", line 1, in <module>
    from tianshou import data, env, utils, policy, trainer, exploration
  File "C:\Users\19395\Downloads\tianshou\tianshou\data\__init__.py", line 1, in <module>
    from tianshou.data.batch import Batch
  File "C:\Users\19395\Downloads\tianshou\tianshou\data\batch.py", line 1, in <module>
    import torch
  File "C:\Anaconda3\envs\tianshou\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: 找不到指定的程序。

**Comment by Trinkle23897** [comment]
It seems like your pip cannot install torch>=1.4.0. I need more info: what’s the python version, pip version, and do you use anaconda?
You can try to install torch first by `pip install torch` or other methods.

**Comment by wanghui589** [comment]
In fact, I am using conda and have installed torch=1.4.0, python=3.6, pip=20.2.3.thank you for your reply



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "n+e"<notifications@github.com&gt;; 
发送时间: 2020年9月24日(星期四) 中午11:42
收件人: "thu-ml/tianshou"<tianshou@noreply.github.com&gt;; 
抄送: "王惠"<1939563058@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thu-ml/tianshou] Can&#39;t install the library (#226)





 
It seems like your pip cannot install torch&gt;=1.4.0. I need more info: what’s the python version, pip version, and do you use anaconda?

**Comment by Trinkle23897** [comment]
So try to re-create your anaconda env first. The user marks the issue resolved.
