### ISSUE TITLE
Question about asynchronous sampling

### ISSUE THREAD

**Issue by BlackDeal** [thu-ml/tianshou#232]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

```python
0.2.6 1.4.0 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] linux
```
When done = true, the agent and the environment stop interacting. Are you sure this is completely asynchronous?

```python
if done[j]:
         if not (list_n_episode and
                  episode_count[i] >= n_episode[i]):
               episode_count[i] += 1
               reward_total += np.sum(self._cached_buf[i].rew, axis=0)
               step_count += len(self._cached_buf[i])
               if self.buffer is not None:
               self.buffer.update(self._cached_buf[i])
               if list_n_episode and \
                             episode_count[i] >= n_episode[i]:
                    # env i has collected enough data, it has finished
                  finished_env_ids.append(i)
                  self._cached_buf[i].reset()
                  self._reset_state(j)
```
I changed the first line to if len(self._cached_buf[i])>3000: ,the agent can interact with the environment all the time, but when the following print appears,
```
Epoch #1:   0%|          | 2/3000 [05:27<272:32:34, 327.27s/it, len=3001.00, loss/actor=10.625942, loss/critic1=33.596956, loss/critic2=63.114598, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 30
Epoch #1:   0%|          | 3/3000 [05:27<272:27:07, 327.27s/it, len=3001.00, loss/actor=7.902750, loss/critic1=28.038447, loss/critic2=45.226332, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20] global_step: 40
Epoch #1:   0%|          | 4/3000 [05:27<272:21:39, 327.27s/it, len=3001.00, loss/actor=6.376198, loss/critic1=43.434847, loss/critic2=59.782637, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 50
Epoch #1:   0%|          | 5/3000 [05:27<190:35:54, 229.10s/it, len=3001.00, loss/actor=6.174948, loss/critic1=50.664899, loss/critic2=66.535709, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 60
Epoch #1:   0%|          | 6/3000 [05:27<190:32:05, 229.10s/it, len=3001.00, loss/actor=6.482226, loss/critic1=49.286624, loss/critic2=65.503024, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 70
Epoch #1:   0%|          | 7/3000 [05:27<190:28:16, 229.10s/it, len=3001.00, loss/actor=7.120704, loss/critic1=48.146372, loss/critic2=59.419871, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 80
Epoch #1:   0%|          | 8/3000 [05:27<190:24:27, 229.10s/it, len=3001.00, loss/actor=7.356705, loss/critic1=49.742595, loss/critic2=57.619016, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 90
Epoch #1:   0%|          | 9/3000 [05:27<133:14:51, 160.38s/it, len=3001.00, loss/actor=7.604189, loss/critic1=47.720844, loss/critic2=57.506350, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 100
Epoch #1:   0%|          | 10/3000 [05:27<133:12:11, 160.38s/it, len=3001.00, loss/actor=7.344016, loss/critic1=46.574332, loss/critic2=58.542535, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 110
Epoch #1:   0%|          | 11/3000 [05:27<133:09:31, 160.38s/it, len=3001.00, loss/actor=6.921362, loss/critic1=43.604113, loss/critic2=54.484068, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 120
Epoch #1:   0%|          | 12/3000 [05:27<93:11:20, 112.28s/it, len=3001.00, loss/actor=6.645770, loss/critic1=43.161759, loss/critic2=51.544634, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 130
Epoch #1:   0%|          | 13/3000 [05:27<93:09:28, 112.28s/it, len=3001.00, loss/actor=6.192375, loss/critic1=42.233424, loss/critic2=50.953825, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 140
Epoch #1:   0%|          | 14/3000 [05:27<93:07:36, 112.28s/it, len=3001.00, loss/actor=5.906689, loss/critic1=41.608822, loss/critic2=51.192688, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 150
Epoch #1:   0%|          | 15/3000 [05:27<93:05:43, 112.28s/it, len=3001.00, loss/actor=5.910126, loss/critic1=41.555110, loss/critic2=50.109602, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 160
Epoch #1:   1%|          | 16/3000 [05:27<65:09:12, 78.60s/it, len=3001.00, loss/actor=6.166273, loss/critic1=40.316944, loss/critic2=48.356224, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 170
Epoch #1:   1%|          | 17/3000 [05:27<65:07:54, 78.60s/it, len=3001.00, loss/actor=6.121465, loss/critic1=39.493898, loss/critic2=46.909860, n/ep=1.00, n/st=3001.00, rew=-538.93, v/ep=0.00, v/st=9.20]global_step: 180
Epoch #1:   1%|          | 18/3000 [05:27<65:06:35, 78.60s/it, len=3001.00, loss/actor=6.243852, loss/critic1=38.676919, 
```
the interaction stops again, and it is normal again after printing
I don't understand why.,Can you explain it？Thank you very much!

**Comment by Trinkle23897** [comment]
Currently, the async mode is only for the environment simulation, i.e., set VectorEnv(wait_num=x, timeout=y) will result in reducing the time consuming of some long-step env. You can refer to https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#parallel-sampling

Here you are in sync mode and we do not provide A3C-style training pipeline since it is resource-consuming in a single node, without any improvements for performance (comparing with A2C). In other words, the collecting and training phase are not executed simultaneously.

**Comment by BlackDeal** [comment]
Yes, I refer to the documentation as follows：

  train_envs = SubprocVectorEnv([lambda: envs[0],lambda:envs[1]], wait_num=1, timeout=0.05)
  test_envs = SubprocVectorEnv([lambda: envs[0],lambda:envs[1]], wait_num=1, timeout=0.05)

**Comment by Trinkle23897** [comment]
The pipeline is: collecting data - training nn - collecting data - training nn - ...

Since we implemented all algorithms under the assumption of a single buffer, we use several cache buffers to maintain the main buffer to keep it chronologically. (https://tianshou.readthedocs.io/en/master/tutorials/concepts.html#collector) 

The first iteration may cause a lot of time because it needs to fill all cache buffers and wait for at least one episode to finish, but once it has done, the second "collecting data" only needs a little time because it can use the previously unused data in the cache buffers to construct another full-length episode data to the main buffer.

**Comment by Trinkle23897** [comment]
> Yes, I refer to the documentation as follows：
> 
> train_envs = SubprocVectorEnv([lambda: envs[0],lambda:envs[1]], wait_num=1, timeout=0.05)
> test_envs = SubprocVectorEnv([lambda: envs[0],lambda:envs[1]], wait_num=1, timeout=0.05)

I think more envs may help resolve this low-training-speed issue, depending on your machine configure. Could you please provide the profile of the distribution of a single env step time? More information about your env is welcomed to pin.
