### ISSUE TITLE
How to count steps?

### ISSUE THREAD

**Issue by d3sm0** [thu-ml/tianshou#234]
Hello,
Thanks for the awesome work. It seems that number of samples are counted only if at least one env is done. if an env is never done this will cause a loop until the "timeout" condition is met. 
Furthermore, even if one env is done, the counting is imprecise because it might be larger than the requested number of samples.

https://github.com/thu-ml/tianshou/blob/710966eda7308fe3d17e08cd9a2676f350b9b5e6/tianshou/data/collector.py#L315

**Comment by Trinkle23897** [comment]
You are right. 

> Thanks for the awesome work. It seems that number of samples are counted only if at least one env is done. if an env is never done this will cause a loop until the "timeout" condition is met.

You can refer to https://tianshou.readthedocs.io/en/master/tutorials/concepts.html#collector and #221. In short, only maintain a single 1-dim buffer makes some implementations simpler.

> Furthermore, even if one env is done, the counting is imprecise because it might be larger than the requested number of samples.

That's true, and the solution is to add some approximation approaches in trainer: if we only want to collect 100 frames per gradient step and the collector gives us 1000, we then perform 10 gradient steps. Something like
https://github.com/thu-ml/tianshou/blob/master/tianshou/trainer/offpolicy.py#L107-L108

**Comment by d3sm0** [comment]
I think gradient steps and number of samples are two hyperparams and to the best of my knoweldge i haven't seen any work linking the two things. And as a designer i would tweak the two things separetely cause one concern the quality of the approximation, and the diversity of the sample.

Probably one can put the count before the done for reporting purposes, so that you actually count the number of frames and be happy with the approximation in the terminal condition.

Or push it in the "env" as a wrapper, maybe with other stats in the info, and forget about it in the rest of the code.

**Comment by Trinkle23897** [comment]
Wrapper is a good way, in my opinion, as pointed out in https://github.com/thu-ml/tianshou/issues/221#issuecomment-694796288.

**Comment by d3sm0** [comment]
ack thx.
