### ISSUE TITLE
DQN with rare events

### ISSUE THREAD

**Issue by Jogima-cyber** [thu-ml/tianshou#237]
Hi ! I've got an environment (gfootball) with very few rewarded episodes (only when goals). I was wondering how to deal with that with DQN and tianshou.

**Comment by Trinkle23897** [comment]
1. Hindsight experience replay (HER), will be implemented
2. Hierarchical DQN
3. Curiosity, will be implemented by @danagi
4. Reward shaping (which is environment-specific), need an extra wrapper to handle

**Comment by Jogima-cyber** [comment]
Thanks very much !

**Comment by pengpeng1997** [comment]
> 1. Hindsight experience replay (HER), will be implemented
> 2. Hierarchical DQN
> 3. Curiosity, will be implemented by @danagi
> 4. Reward shaping (which is environment-specific), need an extra wrapper to handle

@Trinkle23897 Hi there. I've got a similar problem with sparse reward and I'd like to try hierarchical reinforcement learning. But I have no idea how to implement a hierarchical RL algorithm like hierarchical DQN with tianshou. Could you please provide me with any instructions or example?

**Comment by pengpeng1997** [comment]
> 1. Hindsight experience replay (HER), will be implemented
> 2. Hierarchical DQN
> 3. Curiosity, will be implemented by @danagi
> 4. Reward shaping (which is environment-specific), need an extra wrapper to handle

Hi there. I've got a similar problem with sparse reward and I'd like to try hierarchical reinforcement learning. But I have no idea how to implement a hierarchical RL algorithm like hierarchical DQN with tianshou. Could you please provide me with any instructions or example?

**Comment by Trinkle23897** [comment]
Have you tried reward-shaping first?

**Comment by pengpeng1997** [comment]
> Have you tried reward-shaping first?

Yes. And after that and with other reasons (trying a new research idea) we want to build a hierarchical algorithm.

**Comment by Trinkle23897** [comment]
@pengpeng1997 please go to #403. I'm thinking of it.
