### ISSUE TITLE
Multi-agent env requires several actions selected

### ISSUE THREAD

**Issue by Jogima-cyber** [thu-ml/tianshou#239]
I'm trying to build a multi-agent DQN (with two agents) for the gfootball environment. One agent for the left team and another for the right team. Problem is env requires then two actions to be sent to step function when there are two agents, plus it doesn't support natively the agent attribute in observations. I've read https://tianshou.readthedocs.io/en/master/tutorials/tictactoe.html but I still don't know if it's possible with tianshou to implement multi agent with gfootball environment and how to do it.

**Comment by Trinkle23897** [comment]
You can simply use only one abstract Policy to deal with both left and right team's action, and directly send it to the gfootball env.
In other words, this new abstract policy receives full observation (both left and right) and dispatch them to subpolicy (left and right), then gather their actions and send back to the original env. Other things are the same as single-agent.

**Comment by Jogima-cyber** [comment]
Thanks for your very quick answer. So if I make a class inherited from BasePolicy, I'm not entirely sure which function I should rewrite in order to implement your ideas : process_fn, forward, learn ?

**Comment by Trinkle23897** [comment]
I think you can refer to the MultiAgentPolicyManager. The only thing to do is to change the forward function ~(but I'm not sure, maybe the MultiAgentPolicyManager can handle your case directly without changing any code)~

**Comment by Jogima-cyber** [comment]
I think I just have to call the forward function of the two agents in the forward function of the abstract policy, am I right ? But I don't understand why there isn't any call of the forward functions in here : https://github.com/thu-ml/tianshou/blob/b364f1a26f1b8528b01a445a488160ce2d910a1c/tianshou/policy/multiagent/mapolicy.py#L62

**Comment by Trinkle23897** [comment]
Because in pytorch nn.Module, the `__call__` will be redirected to `forward()`
