### ISSUE TITLE
Traditional step collector implementation is needed

### ISSUE THREAD

**Issue by ChenDRAG** [thu-ml/tianshou#245]
For now, when the collect() method of Tianshou's collector is called, it returns a batch result of the whole episode, regardless of the value of collect_per_step.

`result = train_collector.collect(n_step=collect_per_step)`

This is inevitable because the collector uses buffers to concatenate history from multiple envs, and experiments show that this way of collecting data does not affect the results too much. However, a step collector is still needed (even though it might be of low efficiency) because for now, in most papers agents still collect the info by step. Lacking step collector might make it uneasy to determine what's wrong with the scripts once statistics look bad.

**Comment by ChenDRAG** [comment]
#280 will take care of this

**Comment by stg1205** [comment]
> For now, when the collect() method of Tianshou's collector is called, it returns a batch result of the whole episode, regardless of the value of collect_per_step.
> 
> `result = train_collector.collect(n_step=collect_per_step)`
> 
> This is inevitable because the collector uses buffers to concatenate history from multiple envs, and experiments show that this way of collecting data does not affect the results too much. However, a step collector is still needed (even though it might be of low efficiency) because for now, in most papers agents still collect the info by step. Lacking step collector might make it uneasy to determine what's wrong with the scripts once statistics look bad.

Can you provide some references of how collecting episodes of data affect results? I experimented with collector and it supports step collection now but I notice that most statistics, like step count and reward are based on episodes. The problem of mine is that my environments (songs) may have totally different lengths so it may be a problem to collect episodes of data in parallel env sampling. @Trinkle23897

**Comment by Trinkle23897** [comment]
> The problem of mine is that my environments (songs) may have totally different lengths so it may be a problem to collect episodes of data in parallel env sampling.

The different lengths are totally fine.

> Can you provide some references of how collecting episodes of data affect results?

You can treat them with a slight difference, or even no difference in performance.

**Comment by stg1205** [comment]
Thanks for reply. 

> The different lengths are totally fine.

My concern is that some long songs may not be collected for one whole episode while the other may be collected a few episodes to meet the n_episode. 

> You can treat them with a slight difference, or even no difference in performance.

But in this way, the buffer size should be great larger than the average step of an episode, right? Otherwise, some data may be ignored.

**Comment by Trinkle23897** [comment]
> some long songs may not be collected for one whole episode while the other may be collected a few episodes to meet the n_episode.

But this issue is in both step-based and episode-based collector.

> the buffer size should be great larger than the average step of an episode, right?

This is the basic assumption.

**Comment by stg1205** [comment]
I see. For the first problem I think I should have a more proper way to stop collection. Thanks for answering.
