### ISSUE TITLE
Different state and action data type in Fetch_env 

### ISSUE THREAD

**Issue by HeegerGao** [thu-ml/tianshou#25]
Hello, I am using FetchPickAndPlace-v1 env. The 'obs', 'action' and reward_threshold(There seems no reward_threshold in this env) data type are different from normal gym env. For example, the 'obs' of FetchPickAndPlace-v1 is a dict. This leads to some problems when I run the collector in your code, because the collector seems to assume the 'obs' is a list. So it will come out an error.

**Comment by Trinkle23897** [comment]
Can you add an environment wrapper (e.g. gym.Wrapper) to change the dict obs to numpy?

**Comment by HeegerGao** [comment]
Oh, it's the first time I know there is a wrapper function to do such kind of things. I'll try it. Thank you!

**Comment by Trinkle23897** [comment]
Btw, the collector supports storing a dictionary. On my side, the network will receive a np.array which includes a list of dict. You can extract your desired data like `x = np.array([d['observation'] for d in s])` in your network forwarding. It works fine on my side.

**Comment by ChenyangRan** [comment]
> 顺便说一句，收集器支持存储字典。在我这边，网络将收到一个包含字典列表的np.array。您可以像`x = np.array([d['observation'] for d in s])`在网络转发中一样提取所需的数据。它在我这边工作正常。

Hi, could you please tell me how to save the dic in collect?
I read the guides online, but don't know how to realize. 
Because the states and rewards come from collector, I cannot save the desired key into buffer.

**Comment by Trinkle23897** [comment]
@ChenyangRan I add this feature yesterday. Please refer to #38
