### ISSUE TITLE
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

### ISSUE THREAD

**Issue by yanghu819** [thu-ml/tianshou#250]
For I run it with ssh on remote gpu, there is no way to visulize on jupyter, could you provide a version to save the video to mp3 or use matplotlib to show? That will be awsome if that is ok.

**Comment by Trinkle23897** [comment]
Do you run CarRacing environment or something like this? You can install xvfb to solve this issue.
If you want to save the video, you can add extra arguments in env.render()

**Comment by yanghu819** [comment]
I save them using a wrapper to mp4, it's ok

**Comment by gugugu-469** [comment]
> I save them using a wrapper to mp4, it's ok

How to save it to mp4?I use the code   `env = wrappers.Monitor(env, "/tmp/SpaceInvaders-v0")`，but I get the same error.

**Comment by Trinkle23897** [comment]
Could you please paste the error here to see what's actually going wrong?

A simple workaround is to save each image as png by cv2 via wrapper, and then use ffmpeg to put them into a video.

**Comment by gugugu-469** [comment]
I run the code：  case one:Run DQN algorithm in CartPole-v0 environment,the same as "tianshou-docs-zh_CN/docs/5-example.rst"
For I run it with ssh on remote gpu,and I get error in the code "collector.collect(n_episode=1, render=1 / 35)"
"NoSuchDisplayException: Cannot connect to "None""
Then I try to save them to video,I add the code "env = wrappers.Monitor(env, "/tmp/SpaceInvaders-v0")" after "env = gym.make(task)",but I get the same error
I'm not able to install xvfb.How can I get each image?It seems all the work is done in the function collector.collect()

**Comment by Trinkle23897** [comment]
It is because you run the code on a remote GPU server and use ssh to connect it. 

One solution: https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely

And here is another solution: install it in your local environment (either windows or mac), fetch the weight from remote server, and run it locally.
