### ISSUE TITLE
a bug in collector.py (line 311 to line 324)

### ISSUE THREAD

**Issue by shengxiang19** [thu-ml/tianshou#252]
The original code is：
 if not (isinstance(n_episode, list) and episode_count[i] >= n_episode[i])：
 ... do A
 ... if isinstance(n_episode, list) and episode_count[i] >= n_episode[i]:
 ... ... do B
This means that event B will never be executed. In addition, case that isinstance(n_episode, int) was not considered.
I think: this bug leads to a lot of meaningless environment samplings under on-policy trainer case, which seriously reduces the performance of the algorithms.

**Comment by danagi** [comment]
No, it's not a bug. The original code is：
```
if not (isinstance(n_episode, list) and episode_count[i] >= n_episode[i])：
    episode_count[i] += 1
    do A
    if isinstance(n_episode, list) and episode_count[i] >= n_episode[i]:
        do B
```
So B could be executed.

**Comment by shengxiang19** [comment]
Thank you, it's my fault.
Maybe，we shoud add the case isinstance(n_episode, int)?

**Comment by shengxiang19** [comment]
I think: (isinstance(n_episode, list) and episode_count[i] >= n_episode[i]) can change to：((isinstance(n_episode, list) and episode_count[i] >= n_episode[i]) or (isinstance(n_episode, int) and np.sum(episode_count) >= n_episode)).

**Comment by danagi** [comment]
Sorry, I didn't get you. What code do you want to add under this case ? It has been handled by line 348-349.

**Comment by danagi** [comment]
No need to add this case. line 348-349 can handle this.

**Comment by shengxiang19** [comment]
Thank you, I got it.
