### ISSUE TITLE
Something confused when running test_ppo.py

### ISSUE THREAD

**Issue by shengxiang19** [thu-ml/tianshou#253]
When running test_ppo.py, I print the finished_env_ids in collector.py (line 231),  and find that it is always [] in train_collector.

**Comment by Trinkle23897** [comment]
When you use the normal vecenv (without async setting) or `n_episode` is not a list of int, `finished_env_ids` is always `[]`.

**Comment by shengxiang19** [comment]
But, ppo with n_episode that is not a list of int, is still sync mode.

**Comment by Trinkle23897** [comment]
Sure, so that `finished_env_ids` is always `[]`. This variable is only for the async mode or `n_episode` is a list of int (used in test phase).
