### ISSUE TITLE
Question regarding episodic returns

### ISSUE THREAD

**Issue by nsarang** [thu-ml/tianshou#256]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates

Hello.
I have a question regarding the way the discounted returns are calculated for policy gradients algorithms in this library.
As I've looked into the source code, it seems that after the specified number of policy-env interactions, the observations, rewards, ... are inserted into the ReplayBuffer by the Collector. Then the policy takes a batch of **random** samples from the buffer and **then** computes the episodic returns. Isn't it fundamentally wrong that the returns are calculated on the unordered, random samples that could potentially belong to different episodes?

**Comment by Trinkle23897** [comment]
Nope. The on-policy algorithms extract frames from replay buffer with `batch_size=0`, that is, extract **all** of the data from the buffer in the order of timestamp.
