### ISSUE TITLE
question about atari_dqn with SubprocVectorEnv

### ISSUE THREAD

**Issue by shengxiang19** [thu-ml/tianshou#259]
When running atari_dqn with SubprocVectorEnv, I found the memory occupied by each EnvWorker increases gradually when training, e.g. from 115MB to 500MB,  what causes this?

**Comment by Trinkle23897** [comment]
Could you please provide the task name so that I can have a look?

**Comment by shengxiang19** [comment]
the task name is PongNoFrameskip-v4

**Comment by Trinkle23897** [comment]
I ran 15 epochs and didn't see any memory increase in each worker. They all kept with 132M. I use the command `python3 examples/atari/atari_dqn.py --task "PongNoFrameskip-v4" --batch-size 64`.

Possible explanations:
- the wrapper takes up some memory
- the SubprocVectorEnv takes up some memory

But both of them seem impossible to triple their own memory consumption.

**Comment by shengxiang19** [comment]
Can you tell me how much memory atari_dqn.py needs? And how do you monitor the memory of each worker? Thank you very much and I run it in windows system.

**Comment by Trinkle23897** [comment]
I use Linux. The total memory should not be greater than 5GB (about 3~4G). I use `htop` to monitor memory usage.

**Comment by shengxiang19** [comment]
I try again, the total memory of running atari_dqn.py is at least 8GB, it puzzles me. Maybe something wrong happens in windows？

**Comment by Trinkle23897** [comment]
Hmm...I'm not sure. Could you please do the followings (one by one, not together) to see what happens? 
1. set `--training-num 1`
2. set `--test-num 1`
3. change SubprocVectorEnv to DummyVectorEnv

**Comment by shengxiang19** [comment]
when I set --training-num 1，the total memory is 4GB.

**Comment by shengxiang19** [comment]
I find the reason: NumPy 1.16.0 can cause severe memory leak with SubprocVectorEnv. See https://github.com/numpy/numpy/issues/12793 for details. Maybe you can add a tip about this.

**Comment by shengxiang19** [comment]
Thank you very much, this problem is too difficult to find out.

**Comment by Trinkle23897** [comment]
Interesting. Thanks for your report.
