### ISSUE TITLE
Can't install ray>=1.0.0

### ISSUE THREAD

**Issue by zhujl1991** [thu-ml/tianshou#262]
```
(zjlenv) xxx:~/Desktop/tianshou$ pip install  -i https://pypi.org/simple -e ".[dev]" --use-deprecated legacy-resolver
Obtaining file:///Users/jialu.zhu/Desktop/tianshou
Collecting gym>=0.15.4
  Using cached gym-0.17.3.tar.gz (1.6 MB)
Collecting tqdm
  Using cached tqdm-4.54.1-py2.py3-none-any.whl (69 kB)
Requirement already satisfied: numpy in ./zjlenv/lib/python3.7/site-packages (from tianshou==0.3.0) (1.19.4)
Collecting tensorboard
  Using cached tensorboard-2.4.0-py3-none-any.whl (10.6 MB)
Collecting torch>=1.4.0
  Using cached torch-1.7.1-cp37-none-macosx_10_9_x86_64.whl (108.8 MB)
Collecting numba>=0.51.0
  Using cached numba-0.52.0.tar.gz (2.1 MB)
Collecting Sphinx
  Using cached Sphinx-3.3.1-py3-none-any.whl (2.9 MB)
Collecting sphinx_rtd_theme
  Using cached sphinx_rtd_theme-0.5.0-py2.py3-none-any.whl (10.8 MB)
Collecting sphinxcontrib-bibtex
  Using cached sphinxcontrib_bibtex-2.0.0-py3-none-any.whl (18 kB)
Collecting flake8
  Using cached flake8-3.8.4-py2.py3-none-any.whl (72 kB)
Requirement already satisfied: pytest in ./zjlenv/lib/python3.7/site-packages (from tianshou==0.3.0) (6.2.0)
Collecting pytest-cov
  Using cached pytest_cov-2.10.1-py2.py3-none-any.whl (19 kB)
ERROR: Could not find a version that satisfies the requirement ray>=1.0.0 (from tianshou==0.3.0) (from versions: 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.8.0, 0.8.1)
ERROR: No matching distribution found for ray>=1.0.0 (from tianshou==0.3.0)
(zjlenv) xxx:~/Desktop/tianshou$ python --version
Python 3.7.3
(zjlenv) xxx:~/Desktop/tianshou$ pip --version
pip 20.3.1 from /Users/jialu.zhu/Desktop/tianshou/zjlenv/lib/python3.7/site-packages/pip (python 3.7)
```

Looks like pip can't find the ray version after 0.8.1 while it is actually on pypi https://pypi.org/project/ray/0.8.2/#history

**Comment by Trinkle23897** [comment]
I'm not quite sure what happened in MacOS. Because https://pypi.org/project/ray/#history shows that the version of 1.0.0/1.0.1 are available on the public service.
If you do want to use `RayVectorEnv`, you can still install `ray>=0.8`; otherwise, no need to install ray and you can simply comment out the related line in `setup.py`: https://github.com/thu-ml/tianshou/blob/cd481423dc4e63efda83f10213cfbe8680e71b76/setup.py#L63

**Comment by zhujl1991** [comment]
> I'm not quite sure what happened in MacOS. Because https://pypi.org/project/ray/#history shows that the version of 1.0.0/1.0.1 are available on the public service.
> If you do want to use `RayVectorEnv`, you can still install `ray>=0.8`; otherwise, no need to install ray and you can simply comment out the related line in `setup.py`:
> 
> https://github.com/thu-ml/tianshou/blob/cd481423dc4e63efda83f10213cfbe8680e71b76/setup.py#L63

Yes, that's actually what I did. Thanks.

**Comment by Trinkle23897** [comment]
https://github.com/ray-project/ray/issues/12501
