### ISSUE TITLE
Difference between on and off policy trainer

### ISSUE THREAD

**Issue by zhujl1991** [thu-ml/tianshou#264]
I compared the onpolicy_trainer vs offpolicy_trainer: https://www.diffchecker.com/JAQuHhDZ . I can't see any substantial difference. AFAIU, *off policy* means the policy being trained is different from the policy being used to collect the data. That is, as long as the policy passed into the offpolicy trainer is different than the policy used to initialized train_collector, then it's offpolicy. https://github.com/thu-ml/tianshou/blob/cd481423dc4e63efda83f10213cfbe8680e71b76/tianshou/trainer/offpolicy.py#L13-L14

Can anyone help me have a better understanding of the difference here? Thanks.

**Comment by Trinkle23897** [comment]
L87 and L120 are the major difference. On-policy will collect some episodes, use **all** of the data in the buffer and `policy.update` to train the policy, and **reset the buffer**.

**Comment by zhujl1991** [comment]
> L87 and L120 are the major difference. On-policy will collect some episodes, use **all** of the data in the buffer and `policy.update` to train the policy, and **reset the buffer**.

@Trinkle23897  I noticed there's only one input arg that is different between [onpolicy](https://github.com/thu-ml/tianshou/blob/f528131da1de604f8158a1fe132e1fada71950e0/tianshou/trainer/onpolicy.py#L20) and [offpolicy](https://github.com/thu-ml/tianshou/blob/f528131da1de604f8158a1fe132e1fada71950e0/tianshou/trainer/offpolicy.py#L22) trainer. Why does the difference between onpolicy vs offpolicy result in this input arg difference here?

**Comment by Trinkle23897** [comment]
The difference between arguments cannot tell anything. I mean, you can write a trainer with the same function but totally different arguments...
