### ISSUE TITLE
Can I save the replay in episode (trajectory) format in memory, and sample episodes to train the model ?

### ISSUE THREAD

**Issue by fuxianh** [thu-ml/tianshou#265]
Hello, I want to train the DQN with episodes, is it possible to use  tianshou  to finish this goal without modifying the framework? Or how should I modify it? Is there any suggestion. Thank you.

**Comment by Trinkle23897** [comment]
Maybe change `offpolicy_trainer` to `onpolicy_trainer`? Some arguments need to be changed accordingly.

**Comment by fuxianh** [comment]
That is a good idea. But if I want to do it in offpolicy_trainer, I have to modify the buffer.py to provide a episodic buffer which can store trajectories, is it right?

**Comment by Trinkle23897** [comment]
I think you can overwrite the sampling method in the buffer. All of the data stored in buffer (with current implementation) is ordered by episode and timestamp:
```
[ep0_step1 ep0_step2 ... ep0_stepN ep1_step1 ep1_step2 ... ep1_stepN ep2_step1 ...]
```

**Comment by fuxianh** [comment]
Thank you very much. I will try this way.

**Comment by Moirai7** [comment]
@fuxianh Have you made it? Will it possible to share your code?

**Comment by Moirai7** [comment]
> I think you can overwrite the sampling method in the buffer. All of the data stored in buffer (with current implementation) is ordered by episode and timestamp:
> 
> ```
> [ep0_step1 ep0_step2 ... ep0_stepN ep1_step1 ep1_step2 ... ep1_stepN ep2_step1 ...]
> ```

@Trinkle23897  How do we know which index is the end of episode?

**Comment by Trinkle23897** [comment]
buffer.done stores the flag, you can do something like `index[buffer.done[index]]`

**Comment by Moirai7** [comment]
> buffer.done stores the flag, you can do something like `index[buffer.done[index]]`

@Trinkle23897  but if I have updated the buffer. The result could be incorrect.
