### ISSUE TITLE
A2C : impossible actions

### ISSUE THREAD

**Issue by Jogima-cyber** [thu-ml/tianshou#268]
Hi there, I'm trying A2C module of tianshou, and I've got some impossible actions for some states. In DQN with tianshou I'm using a mask, but it doesn't work for A2C. I'm just beginning to familiarize myself with Gradient Policy methods, and I don't even know if it's really useful to tell your model which actions are impossible for each state. So my question is : is it necessary to tell a A2C model which action are impossible for each state and if yes, how to do it with tianshou ?

**Comment by Trinkle23897** [comment]
Assume you are using A2C with discrete action (categorical distribution), so that you can do something like
https://github.com/tensorflow/agents/blob/b2ed02d20c43a4b789a4711f4653e8421f8ba526/tf_agents/distributions/masked.py#L21-L32
