### ISSUE TITLE
 module 'tianshou.env' has no attribute 'DummyVectorEnv'

### ISSUE THREAD

**Issue by LpLegend** [thu-ml/tianshou#269]
When I run the code in the documentation online
```
train_envs = ts.env.DummyVectorEnv([lambda: gym.make('CartPole-v0') for _ in range(8)])
test_envs = ts.env.DummyVectorEnv([lambda: gym.make('CartPole-v0') for _ in range(100)])
```
it says
```
AttributeError                            Traceback (most recent call last)
<ipython-input-9-f2a452c010ce> in <module>()
----> 1 train_envs = ts.env.DummyVectorEnv([lambda: gym.make('CartPole-v0') for _ in range(8)])
      2 test_envs = ts.env.DummyVectorEnv([lambda: gym.make('CartPole-v0') for _ in range(100)])

AttributeError: module 'tianshou.env' has no attribute 'DummyVectorEnv'
```
Why?

**Comment by Trinkle23897** [comment]
1. How did you install tianshou?
2. What's the current path?
3. Which code has been executed before this line?

**Comment by LpLegend** [comment]
> 1. How did you install tianshou?
> 2. What's the current path?
> 3. Which code has been executed before this line?

1. `pip install --upgrade tianshou`: `Successfully installed tianshou-0.3.0.post1`
2. The current dir is in anaconda's jupyterlab, D:/
3. 
```
import gym
import tianshou as ts
```

**Comment by LpLegend** [comment]
like this
![image](https://user-images.githubusercontent.com/31556153/103875976-08905200-510e-11eb-88a4-6fb6c431cdb2.png)

**Comment by Trinkle23897** [comment]
So could you please execute `python test/discrete/test_dqn.py` instead of jupyter labs to see what happens?
Also, you can create a file that includes
```python
import gym
import tianshou as ts
print(ts.env.DummyVectorEnv)
```
and execute that file, I want to see what happens.

**Comment by Trinkle23897** [comment]
And please run the following command in jupyter lab:
```python
import os
print(os.path.abspath('.'))
print(ts)
from tianshou.env import *
```

**Comment by LpLegend** [comment]
It is because tianshou needs `h5py>=0.3.x` but my current environment use `h5py 0.2.x` in order to support tf2.x
After I upgraded h5py, everything looks fine for both jlab and pycharm :)

![image](https://user-images.githubusercontent.com/31556153/103877223-bb14e480-510f-11eb-8bf4-88ec2f726804.png)

![image](https://user-images.githubusercontent.com/31556153/103876941-4b065e80-510f-11eb-8f63-a625b7b63696.png)

**Comment by LpLegend** [comment]
十分感谢您的不吝细心回复

**Comment by Trinkle23897** [comment]
Okay.
