### ISSUE TITLE
process obs(image + state)

### ISSUE THREAD

**Issue by ChenyangRan** [thu-ml/tianshou#27]
Hi, I want to process the obs, which include images and numerical states. 
How can I add these info into buf?

**Comment by Trinkle23897** [comment]
Could you please try an environment wrapper, e.g. `gym.Wrapper`? You can refer to #25

**Comment by ChenyangRan** [comment]
> 
> 
> Could you please try an environment wrapper, e.g. `gym.Wrapper`? You can refer to #25

The env is made by myself, the return is image and numerical  states separately.
You means that I can use the dic to store them?

**Comment by Trinkle23897** [comment]
Sure, that's a possible solution. But I'd like to mention that there is another way to handle it better: use `info` in the return of `env.step`, for example:
```python
def step(action, ...):
    some code
    return your_images, reward, done_flag, your_numerical_states
    # or return your_images, reward, done_flag, {'num_state': your_numerical_states}
```
and in your self-defined network:
```python
class Net(nn.Module):
    def forward(self, s, state=None, info={}):
        # here s is your images, info is your numerical states, both stored in numpy.ndarray
```

**Comment by ChenyangRan** [comment]
> 
> 
> Sure, that's a possible solution. But I'd like to mention that there is another way to handle it better: use `info` in the return of `env.step`, for example:
> 
> ```python
> def step(action, ...):
>     some code
>     return your_images, reward, done_flag, your_numerical_states
>     # or return your_images, reward, done_flag, {'num_state': your_numerical_states}
> ```
> 
> and in your self-defined network:
> 
> ```python
> class Net(nn.Module):
>     def forward(self, s, state=None, info={}):
>         # here s is your images, info is your numerical states, both stored in numpy.ndarray
> ```

Oh, I'll try it, thanks.
