### ISSUE TITLE
TypeError: offpolicy_trainer() got an unexpected keyword argument 'task'

### ISSUE THREAD

**Issue by chauncygu** [thu-ml/tianshou#271]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

**Comment by Trinkle23897** [comment]
Could you please provide the relevant code snippets here?
