### ISSUE TITLE
test_reward doesn't change in example

### ISSUE THREAD

**Issue by LovelyBuggies** [thu-ml/tianshou#272]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
I am using tianshou 0.3.0 post1. When I'm trying to run the pong_ppo.py in examples (python `pong_ppo.py`), in the 100 epochs, the test_reward never change. Thus, the pong cannot play in the final Collector.collect().

Am I mistaking something?

**Comment by Trinkle23897** [comment]
Oops, the scripts under `runnable/` folder have not been tuned. Sorry about that.

**Comment by LovelyBuggies** [comment]
Keep watching on this issue.

So what's the ideal final test_reward for this game. As I'm generating the pong_a2c policy model as well. The rewards fall into `test_reward: -10.000000 ± 1.224745, best_reward: -8.625000 ± 1.576190` currently.

**Comment by Trinkle23897** [comment]
See https://github.com/thu-ml/tianshou/blob/master/examples/atari/README.md

**Comment by heartInsert** [comment]
I  also   want  to   adapt  PPO  in  discrete   ,  but  I failed .
