### ISSUE TITLE
save the info

### ISSUE THREAD

**Issue by ChenyangRan** [thu-ml/tianshou#28]
Hi, the info includes a flag which represents succ or fail to grasp.
How can I save the info by tensorboard?
I don't see the env.step and save the info.

**Comment by Trinkle23897** [comment]
Here it is: I add a `log_fn` in both collector and trainer. This hook receives each step's env info.
```python3
class Logger(object):
    def __init__(self, writer):
        self.cnt = 0
        self.writer = writer

    def log(self, info):
        self.writer.add_scalar('key', info['key'], global_step=self.cnt)
        self.cnt += 1
```
and in trainer (or collector, if you don't use trainer), add an argument `log_fn=logger.log`.

**Comment by ChenyangRan** [comment]
> 
> 
> Here it is: I add a `log_fn` in both collector and trainer. This hook receives each step's env info.
> 
> ```python
> class Logger(object):
>     def __init__(self, writer):
>         self.cnt = 0
>         self.writer = writer
> 
>     def log(self, info):
>         self.writer.add_scalar('key', info['key'], global_step=self.cnt)
>         self.cnt += 1
> ```
> 
> and in trainer (or collector, if you don't use trainer), add an argument `log_fn=logger.log`.

Thanks, I'll try it.
