### ISSUE TITLE
Stricter requirement for Numpy

### ISSUE THREAD

**Issue by duburcqa** [thu-ml/tianshou#281]
[Numpy 1.20](https://github.com/numpy/numpy/releases/tag/v1.20.0) has been released a few minutes ago and it is breaking some stuff, especially the `np.core.umath` API is not more, and many Numpy methods are features typing. On my side, it is breaking `pylint` / `mypy` check (in a good way, because it catches "errors" not detected before). The issue with this release is that it is NOT compatible with Python3.6, so it may be hard to support it and fix type checking for both.

So I suggest explicitly restricting `Numpy` to prio versions for now as a quick fix, just changing this [line](https://github.com/thu-ml/tianshou/blob/f0129f4ca774e89f0def2c7ec0d14791ab98f22e/setup.py#L50).

**Comment by Trinkle23897** [comment]
> So I suggest explicitly restricting `Numpy` to prio versions for now as a quick fix, just changing this [line](https://github.com/thu-ml/tianshou/blob/f0129f4ca774e89f0def2c7ec0d14791ab98f22e/setup.py#L50).

I think it doesn't matter because we have to correct the type-checking with this new version. I'll take for that.

**Comment by duburcqa** [comment]
Yes but correct the type-checker for numpy 1.20 may break it for olders ones, making quite annoying to develop on Ubuntu 18, as I am x) But yes, have a look and we will see how it goes !

**Comment by Trinkle23897** [comment]
Interesting, I found another potential bug: different version of numpy will get different result, here I use 1.19.5:
```python
import numpy as np
import networkx as nx
v = nx.Graph()

In [5]: np.array([v,v,v])
Out[5]: array([], shape=(3, 0), dtype=float64)

In [7]: np.array([v,v,v, None], dtype=np.object)
Out[7]: 
array([<networkx.classes.graph.Graph object at 0x7f1017926358>,
       <networkx.classes.graph.Graph object at 0x7f1017926358>,
       <networkx.classes.graph.Graph object at 0x7f1017926358>, None],
      dtype=object)

In [8]: np.array([v,v,v], dtype=np.object)
Out[8]: array([], shape=(3, 0), dtype=object)
```
The original behavior is that `np.asanyarray` will keep nx.Graph() as an object, as stated in the 5th block in https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation

BTW, pr 280 is ready!
