### ISSUE TITLE
New docs for `tianshou`

### ISSUE THREAD

**Issue by StevenJokess** [thu-ml/tianshou#282]
https://github.com/d2l-ai/d2l-book
This package helps you build and publish a book with Python code, or Python package documents with tutorials.
If you want to make RL more popular, it would help you.
I don't have lots of RL experiences. Would you teach me?

**Comment by Trinkle23897** [comment]
Looks great but actually I don't have extra time to deal with it. Sorry.
Also, I have written Chinese version of documents at [https://github.com/thu-ml/tianshou-docs-zh_CN](https://github.com/thu-ml/tianshou-docs-zh_CN), could you please check it out? Maybe that would help you.
