### ISSUE TITLE
Action constraint

### ISSUE THREAD

**Issue by Thunder-Fire** [thu-ml/tianshou#283]
I would like to add some action constraints using DDPG such as the sum of actions must be one.
Could you please tell me what should I do?

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/blob/f0129f4ca774e89f0def2c7ec0d14791ab98f22e/tianshou/policy/modelfree/ddpg.py#L146-L147
How about here, add a line with `actions = actions / actions.sum(dim=-1, keepdim=True)`

**Comment by Thunder-Fire** [comment]
> https://github.com/thu-ml/tianshou/blob/f0129f4ca774e89f0def2c7ec0d14791ab98f22e/tianshou/policy/modelfree/ddpg.py#L146-L147
> 
> 
> How about here, add a line with `actions = actions / actions.sum(dim=-1, keepdim=True)`

Thank you very much ! I checked it working.
