### ISSUE TITLE
BaseVectorEnv is not working when "lambda: gym.make(task) for _ in range(train_num)])"

### ISSUE THREAD

**Issue by StevenJokess** [thu-ml/tianshou#285]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
I read https://tianshou.readthedocs.io/zh/latest/docs/5-example.html

![image](https://user-images.githubusercontent.com/71307974/107115959-31da0480-68ab-11eb-877a-6995ad5a3b61.png)

https://github.com/thu-ml/tianshou/blob/master/tianshou/env/venvs.py
https://github.com/StevenJokess/d2l-en-read/blob/moreme/RL/tianshou-DQN.ipynb

![image](https://user-images.githubusercontent.com/71307974/107116005-749bdc80-68ab-11eb-8084-d65304ce6143.png)
![image](https://user-images.githubusercontent.com/71307974/107115997-6ea5fb80-68ab-11eb-8df3-ed2186c741f9.png)
![image](https://user-images.githubusercontent.com/71307974/107115953-28509c80-68ab-11eb-9cf8-3e37e49edb7a.png)

**Comment by Trinkle23897** [comment]
Sorry about that, I haven't updated this section.
It is because we changed VectorEnv to DummyVectorEnv, and created an abstract class `BaseVectorEnv` to describe APIs. As you can see, BaseVectorEnv cannot work because all its methods are not implemented.
I'll update it now. Thanks!

**Comment by StevenJokess** [comment]
If you use docs like http://preview.d2l.ai/d2l-en/master/chapter_linear-networks/softmax-regression-scratch.html, it will alarm you if you don't update.
