### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by xiaoyong** [thu-ml/tianshou#286]
Hello,

When running some of the test code, I met the following error:
```python
% python test/discrete/test_sac.py                                                                                                                               (git)-[master]-
tianshou/data/buffer.py:348: UserWarning: ListReplayBuffer will be replaced in version 0.4.0.
  warnings.warn("ListReplayBuffer will be replaced in version 0.4.0.")
Epoch #1:   0%|                                                                                                                                         | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test/discrete/test_sac.py", line 121, in <module>
    test_discrete_sac()
  File "test/discrete/test_sac.py", line 104, in test_discrete_sac
    result = offpolicy_trainer(
  File "tianshou/trainer/offpolicy.py", line 92, in offpolicy_trainer
    result = train_collector.collect(n_step=collect_per_step)
  File "tianshou/data/collector.py", line 270, in collect
    self.data.act = to_numpy(result.act)
  File "tianshou/data/utils/converter.py", line 18, in to_numpy
    return x.detach().cpu().numpy()
RuntimeError: CUDA error: an illegal memory access was encountered
```

The same error shows for `test/discrete/test_ppo.py`. However, it works well for some other RL algorithms, such as DQN (`test/discrete/test_dqn.py`).

Here is my environment:
- tianshou: 0.3.1 (commit  f0129f4ca774e89f0def2c7ec0d14791ab98f22e)
- pytorch: v1.6.0
- python: v3.8.5
- OS: Ubuntu 16.04

**Comment by Trinkle23897** [comment]
Could you please upgrade pytorch version to >=1.7.0? As people discussed in https://github.com/pytorch/pytorch/issues/21819, it seems like this issue can be resolved by upgrading pytorch version.
I tested with 1.7.0 and 1.7.1 and py3.8, everything looks fine. (Indeed 1.6.0 will raise this error)

**Comment by xiaoyong** [comment]
It seems that this error is caused by the MLP head in Actor and Critic.

https://github.com/thu-ml/tianshou/blob/master/tianshou/utils/net/discrete.py#L49
https://github.com/thu-ml/tianshou/blob/master/tianshou/utils/net/discrete.py#L100

MLP expects a `device` argument, which was not given. By passing this argument, I succeeded to train SAC on a GPU.

Maybe the latest pytorch version adds the `device` attribute for nn.Module, which can be set correctly by net.to(device)?

**Comment by Trinkle23897** [comment]
Woo, that's a pretty nice feature! I'll take it.

**Comment by ChenDRAG** [comment]
> Maybe the latest pytorch version adds the `device` attribute for nn.Module, which can be set correctly by net.to(device)?

Seems so, but we still pass in args.device by hand for now. Bug is fixed, thanks a lot.
