### ISSUE TITLE
OSError: [WinError 1455] The paging file is too small for this operation to complete

### ISSUE THREAD

**Issue by wenzhoulyu** [thu-ml/tianshou#297]
OSError: [WinError 1455] The paging file is too small for this operation to complete
Error loading "E:\Anaconda\envs\Python37\lib\site-packages\torch\lib\cudnn_cnn_train64_8.dll" or one of its dependencies.

**Comment by Trinkle23897** [comment]
It seems like a pytorch-related issue. Could you please run a pytorch hello-world example with cuda and cudnn enabled to test if it works?

**Comment by wenzhoulyu** [comment]
```python
import torch
from torch.backends import cudnn
print(cudnn.is_available())
print(cudnn.is_acceptable(a.cuda()))
```

This code works well and all things return `True`, so that it means both cuda and cudnn are working perfectly.

**Comment by Trinkle23897** [comment]
Could you please paste your env version (pytorch/cuda/cudnn) and the full traceback info? I can barely tell what happened according to the above information.

**Comment by shengxiang19** [comment]
I think this issue is because of too many vector env launched, which may cause oom.

**Comment by Trinkle23897** [comment]
Also you can refer to this SO question: https://stackoverflow.com/questions/64837376/how-to-efficiently-run-multiple-pytorch-processes-models-at-once-traceback

**Comment by gembul999** [comment]
if not what should i do

runfile('E:/Anto/belajar/untitled0.py', wdir='E:/Anto/belajar')
True
False

**Comment by mf093087** [comment]
I have the same question

**Comment by ANABUR920** [comment]
Meet similar problem
