### ISSUE TITLE
Question about Batch.cat

### ISSUE THREAD

**Issue by FYYFU** [thu-ml/tianshou#301]
In Section `Aggregation of Heterogeneous Batches` of `Understand Batch`, the dimension result of `Batch.cat` in the figure doesn't match the actual behavior:

![图片](https://user-images.githubusercontent.com/37999885/109466030-09a58600-7aa4-11eb-9615-f086fb153c32.png)

As you can see, the result of `name.shape` is `(6, 6)` instead of `(7, 6)`, same as `name2.shape`.

**Comment by Trinkle23897** [comment]
This follows numpy's behavior, you can have a try:
```python
In [1]: import numpy as np

In [2]: a=np.zeros((3,6))

In [3]: np.concatenate([a,a]).shape
Out[3]: (6, 6)

In [4]: a=np.zeros((3,7))

In [5]: np.concatenate([a,a]).shape
Out[5]: (6, 7)
```

**Comment by FYYFU** [comment]
> This follows numpy's behavior, you can have a try:
> 
> ```python
> In [1]: import numpy as np
> 
> In [2]: a=np.zeros((3,6))
> 
> In [3]: np.concatenate([a,a]).shape
> Out[3]: (6, 6)
> 
> In [4]: a=np.zeros((3,7))
> 
> In [5]: np.concatenate([a,a]).shape
> Out[5]: (6, 7)
> ```
so the shape in the picture should be (6, 6) and (6, 7)?
![图片](https://user-images.githubusercontent.com/37999885/109467823-b6810280-7aa6-11eb-95ca-1dab1db99cf2.png)

**Comment by Trinkle23897** [comment]
oops, thank for pointing out, that's a typo @youkaichao

**Comment by Trinkle23897** [comment]
wait a second, this figure is correct:
```python
In [1]: from tianshou.data import Batch

In [2]: import numpy as np

In [3]: a=Batch(a=np.zeros([3, 5]), b=Batch(b1=np.zeros([3, 6]), b2=np.zeros([3, 7])), c=np.zeros([3, 8]))

In [4]: b=Batch(a=np.zeros([4, 5]), b=Batch(), c=np.zeros([4, 8]))

In [5]: c=Batch.cat([a, b])

In [6]: c.b.b1.shape
Out[6]: (7, 6)

In [7]: c.b.b2.shape
Out[7]: (7, 7)
```

The issue is, in your script, `len(batch2) == 3` but in the figure `len(batch2) == 4`

**Comment by FYYFU** [comment]
> wait a second, this figure is correct:
> 
> ```python
> In [1]: from tianshou.data import Batch
> 
> In [2]: import numpy as np
> 
> In [3]: a=Batch(a=np.zeros([3, 5]), b=Batch(b1=np.zeros([3, 6]), b2=np.zeros([3, 7])), c=np.zeros([3, 8]))
> 
> In [4]: b=Batch(a=np.zeros([4, 5]), b=Batch(), c=np.zeros([4, 8]))
> 
> In [5]: c=Batch.cat([a, b])
> 
> In [6]: c.b.b1.shape
> Out[6]: (7, 6)
> 
> In [7]: c.b.b2.shape
> Out[7]: (7, 7)
> ```
> 
> The issue is, in your script, `len(batch2) == 3` but in the figure `len(batch2) == 4`

Ok. I find an example under the picture. thanks. 
it is a little hard to understand. so it is something like  'broadcast'?

**Comment by Trinkle23897** [comment]
yep
