### ISSUE TITLE
action mask is not used in 'compute_nstep_return'

### ISSUE THREAD

**Issue by ArthurWang10086** [thu-ml/tianshou#309]
It leads to unexpected results when the max q-value of the next state is calculated based on illegal actions.

**Comment by Trinkle23897** [comment]
Do you mean in `_target_q` below, the target_q isn't masked? https://github.com/thu-ml/tianshou/blob/5c53f8c1f8aa0f4ed68ce9ea8455a89518db619c/tianshou/policy/modelfree/dqn.py#L74-L83

**Comment by ArthurWang10086** [comment]
> Do you mean in `_target_q` below, the target_q isn't masked?
> 
> https://github.com/thu-ml/tianshou/blob/5c53f8c1f8aa0f4ed68ce9ea8455a89518db619c/tianshou/policy/modelfree/dqn.py#L74-L83
> 
> That's indeed a bug, thanks for pointing out!

only the action mask of obs is considered while the action mask of obs_next  not.

**Comment by Trinkle23897** [comment]
Exactly. And would you like to make a pull request to fix it?
