### ISSUE TITLE
mistake in tutorials about replaybuffer

### ISSUE THREAD

**Issue by CarlDegio** [thu-ml/tianshou#315]
page: [Basic concepts in Tianshou](https://tianshou.readthedocs.io/en/master/tutorials/concepts.html)

In the second part, demo code give an example about `ReplayBuffer`

```
>>> import pickle, numpy as np
>>> from tianshou.data import ReplayBuffer
>>> buf = ReplayBuffer(size=20)
>>> for i in range(3):
...     buf.add(obs=i, act=i, rew=i, done=0, obs_next=i + 1, info={})
```

However, `buf.add(obs=i, act=i, rew=i, done=0, obs_next=i + 1, info={})` will throw an exception `TypeError: add() got an unexpected keyword argument 'obs'`

the right way to use replaybuffer is  `buf.add(Batch(obs=i, act=i, rew=i, done=0, obs_next=i + 1, info={}))` ? I think this may be a mistake of tutorials.

**Comment by Trinkle23897** [comment]
oops, thanks for pointing out!

**Comment by Trinkle23897** [comment]
@CarlDegio please have a check at #316, much appreciated!
