### ISSUE TITLE
Can collector/venv be aware of the environment state?

### ISSUE THREAD

**Issue by ultmaster** [thu-ml/tianshou#322]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

```
0.4.0 1.8.0 3.8.8 (default, Feb 24 2021, 21:46:12) 
[GCC 7.3.0] linux
```

Hi there, thanks for this great project.

I want to know whether it's possible that collector can be aware of the environment state. For example, when environment depends on some generator that could run out (e.g., streaming data, one-epoch data, countable gaming scenario), after some episodes, the env cannot be reset anymore. Therefore, we cannot always know how many episodes in total collectors need to collect. In fact, in such cases, when collector should stop fully depends on when env runs out itself.

Actually, in our use case, we are testing our agent on a fixed dataset, where each sample in the dataset is an episode for the agent. And we split the dataset to do parallel sampling in venv. The problem here is, collector cannot accurately stop those envs that need to be stopped. Even with `n_episode`, collector could wrongly stop those envs that are still with more samples but keep envs with zero samples.

I can propose a design for this feature, but it involves at least env, venv and collector and will be a pretty large change. Therefore, I think it's worth a discussion to make sure whether people believe it is a valid use case.

**Comment by Trinkle23897** [comment]
Basically, our assumption is, the environment can be reset infinitely.
So, IMHO, you can write a `gym.Wrapper` that maintains global information -- which episode is still available for the next env.reset, and from this approach it can convert a "finite reset" env to an "infinite reset" env. Once all of the episodes are sampled and no env can be reset, you can simply catch the error outside the trainer.

**Comment by ultmaster** [comment]
@Trinkle23897 Thanks for your advice. As I found that collector does not take a `gym.Wrapper`, I improvised a little bit. Note that the `DistributedSampler` that use a predefined shard split can be easily replaced with a more efficient consumer-producer sampler.

I'll post a dummy example here in case anyone has a similar question. *If you want me to add the snippet into tests, I'm happy to do that.*

```python
import copy
import random
from collections import Counter
from typing import Callable, Optional, Union, List

import numpy as np
import torch
from gym import Env
from tianshou.data import Collector, Batch
from tianshou.env import BaseVectorEnv, DummyVectorEnv, SubprocVectorEnv
from tianshou.policy import BasePolicy
from torch.utils.data import Dataset, DataLoader, DistributedSampler


class DummyDataset(Dataset):
    def __init__(self, length):
        self.length = length
        self.episodes = [3 * i % 5 + 1 for i in range(self.length)]

    def __getitem__(self, index):
        assert 0 <= index < self.length
        return index, self.episodes[index]

    def __len__(self):
        return self.length


class FiniteEnv(Env):
    def __init__(self, dataset, num_replicas, rank):
        self.dataset = dataset
        self.num_replicas = num_replicas
        self.rank = rank
        self.loader = DataLoader(dataset, sampler=DistributedSampler(dataset, num_replicas, rank), batch_size=None)
        self.iterator = None

    def reset(self):
        if self.iterator is None:
            self.iterator = iter(self.loader)
        try:
            self.current_sample, self.step_count = next(self.iterator)
            self.current_step = 0
            return self.current_sample
        except StopIteration:
            self.iterator = None
            return None

    def step(self, action):
        self.current_step += 1
        assert self.current_step <= self.step_count
        return 0, 1.0, self.current_step >= self.step_count, {'sample': self.current_sample, 'action': action, 'metric': 2.0}


class FiniteEpisodeVectorEnv(BaseVectorEnv):
    def __init__(
        self,
        env_fns: List[Callable[[], Env]],
        wait_num: Optional[int] = None,
        timeout: Optional[float] = None,
    ):
        super().__init__(env_fns, wait_num, timeout)
        self._alive_env_ids = set()
        self._reset_stopped_envs()
        self._default_obs = self._default_info = None

    def _reset_stopped_envs(self):
        if not self._alive_env_ids:
            # starting or running out
            self._alive_env_ids = set(range(self.env_num))

    ### To workaround with tianshou's buffer and batch ###
    def _set_default_obs(self, obs):
        if obs is not None and self._default_obs is None:
            self._default_obs = copy.deepcopy(obs)

    def _set_default_info(self, info):
        if info is not None and self._default_info is None:
            self._default_info = copy.deepcopy(info)

    def _get_default_obs(self):
        return copy.deepcopy(self._default_obs)

    def _get_default_info(self):
        return copy.deepcopy(self._default_info)
    ### END ###

    def reset(self, id: Optional[Union[int, List[int], np.ndarray]] = None):
        id = self._wrap_id(id)
        self._reset_stopped_envs()

        request_id = list(filter(lambda i: i in self._alive_env_ids, id))
        obs = [None] * len(id)
        id2idx = {i: k for k, i in enumerate(id)}
        if request_id:
            for i, o in zip(request_id, super().reset(request_id)):
                obs[id2idx[i]] = o
        for i, o in zip(id, obs):
            if o is None and i in self._alive_env_ids:
                self._alive_env_ids.remove(i)

        for o in obs:
            self._set_default_obs(o)
        for i in range(len(obs)):
            if obs[i] is None:
                obs[i] = self._get_default_obs()

        if not self._alive_env_ids:
            self.reset()
            raise StopIteration

        return np.stack(obs)

    def step(self, action: np.ndarray, id: Optional[Union[int, List[int], np.ndarray]] = None):
        id = self._wrap_id(id)
        id2idx = {i: k for k, i in enumerate(id)}
        request_id = list(filter(lambda i: i in self._alive_env_ids, id))
        result = [[None, 0., False, None] for _ in range(len(id))]

        if request_id:
            valid_act = np.stack([action[id2idx[i]] for i in request_id])
            for i, r in zip(request_id, zip(*super().step(valid_act, request_id))):
                result[id2idx[i]] = r

        # logging
        for i, r in zip(id, result):
            if i in self._alive_env_ids:
                print(*r)
                tracker.log(*r)

        for _, __, ___, i in result:
            self._set_default_info(i)
        for i in range(len(result)):
            if result[i][0] is None:
                result[i][0] = self._get_default_obs()
            if result[i][3] is None:
                result[i][3] = self._get_default_info()

        return list(map(np.stack, zip(*result)))


class FiniteDummyVectorEnv(FiniteEpisodeVectorEnv, DummyVectorEnv):
    pass


class FiniteSubprocVectorEnv(FiniteEpisodeVectorEnv, SubprocVectorEnv):
    pass


class AnyPolicy(BasePolicy):
    def forward(self, batch, state=None):
        return Batch(act=np.stack([1] * len(batch)))

    def learn(self, batch):
        pass


def _finite_env_factory(dataset, num_replicas, rank):
    return lambda: FiniteEnv(dataset, num_replicas, rank)


class MetricTracker:
    def __init__(self):
        self.counter = Counter()
        self.finished = set()

    def log(self, obs, rew, done, info):
        assert rew == 1.
        index = info['sample']
        if done:
            assert index not in self.finished
            self.finished.add(index)
        self.counter[index] += 1

    def validate(self):
        assert len(self.finished) == 100
        for k, v in self.counter.items():
            assert v == k * 3 % 5 + 1


if __name__ == '__main__':
    seed = 999

    random.seed(seed)
    torch.manual_seed(seed)
    np.random.seed(seed)

    dataset = DummyDataset(100)
    envs = FiniteSubprocVectorEnv([_finite_env_factory(dataset, 5, i) for i in range(5)])
    policy = AnyPolicy()
    test_collector = Collector(policy, envs, exploration_noise=True)

    for epoch in range(3):
        tracker = MetricTracker()
        try:
            test_collector.collect(n_step=10 ** 18)
        except StopIteration:
            tracker.validate()
```

**Comment by Trinkle23897** [comment]
Definitely a cool solution! And my previous thought is that there's no need to rewrite vector env -- just wrap another layer for existing envs by gym.Wrapper, and this layer (like a factory method) handles all of the env states by some kinds of lock. But yes, happy to see that.

**Comment by ultmaster** [comment]
Just for discussion, what I implemented actually is that all env workers are reading and serving data from a single dataset. Therefore, just to be clear, in each epoch of *this dataset*, there are three stages:

1. All workers have data, and are happy to reset.
2. Some workers still can reset, while others cannot reset because there is no more data (I call them dead).
3. All workers are dead.

Note that in the second case, since vector env have no idea that some envs are dead, it will keep asking those envs to reset and step. I think it works by wrapping the original envs with `gym.Wrapper`, but it will become more messy as these wrappers will be run in different process (with subprocworker) and I didn't see obvious solutions that exceptions throw by subprocworkers be catched and processed by venv or collector.

Moreover, if I want to keep track of metrics (other than rewards) and aggregate them immediately for other purposes (e.g., earlystopping), syncing between `gym.Wrapper` looks another tons of workload to me.

**Comment by Trinkle23897** [comment]
> I think it works by wrapping the original envs with `gym.Wrapper`, but it will become more messy as these wrappers will be run in different process (with subprocworker)

Yeah, that's a big issue. If only use dummy, that's fine, though.

> Moreover, if I want to keep track of metrics (other than rewards) and aggregate them immediately for other purposes (e.g., earlystopping), syncing between `gym.Wrapper` looks another tons of workload to me.

Can't agree more :)

BTW, when others find this issue, they can choose the method they want to develop their requirements efficiently.
