### ISSUE TITLE
fail to run example code in docs

### ISSUE THREAD

**Issue by cutebomb** [thu-ml/tianshou#326]
- [ ] I have marked all applicable categories:
    + [*] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
0.4.0 1.7.0 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] win32

code in https://tianshou.readthedocs.io/en/master/tutorials/dqn.html

result in simple exception like:

  File "D:\Anaconda3\lib\site-packages\tianshou\trainer\offpolicy.py", line 88, in offpolicy_trainer
    best_reward, best_reward_std = test_result["rew"], test_result["rew_std"]

KeyError: 'rew'

**Comment by Trinkle23897** [comment]
Remove `logger=None` should work. I'll fix it now.

**Comment by cutebomb** [comment]
> Remove `logger=None` should work. I'll fix it now.

thanks, works fine :)
