### ISSUE TITLE
`max_episode_steps` has no effects in Atari

### ISSUE THREAD

**Issue by gohsyi** [thu-ml/tianshou#33]
https://github.com/thu-ml/tianshou/blob/4fd826761c9884457928da9dac52d7ee1c51443a/tianshou/env/atari.py#L98

The variable `self.terminal` that contains the information of whether `max_episode_steps` is exceeded is not used. Please check the above link.

**Comment by Trinkle23897** [comment]
@Mehooz

**Comment by Trinkle23897** [comment]
@gohsyi see #34
