### ISSUE TITLE
Tensorboard warning

### ISSUE THREAD

**Issue by wlpku123** [thu-ml/tianshou#336]
If I directly import tianshou in Windows, it will raise the following errors:

```python
E:\anaconda\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: 
    FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. np_resource = np.dtype([("resource", np.ubyte, 1)]))
```

Though sometimes it won't raise such an error, I'm wondering if you could provide the solution to resolve this issue. BTW, some code presented in the online documentation can't successfully run in my previous experience.

![image](https://user-images.githubusercontent.com/47173027/114494636-48a42b00-9c4f-11eb-8663-17ec07afecd6.png)

**Comment by Trinkle23897** [comment]
This is generated by numpy 1.20 and you can just ignore that. A possible way is to install "numpy<=1.19.5".
It is because tensorboard hasn't adapted to the newest numpy version.

> BTW, some code presented in the online documentation can't successfully run in my previous experience.

What do you mean?

**Comment by wlpku123** [comment]
I mean where can I find the baseline model? Is it in https://tianshou.readthedocs.io/en/latest/tutorials/dqn.html?
I want to try SAC but several days ago I use the code in the docs, it raises error.

**Comment by Trinkle23897** [comment]
Hmm... it should be fine now. It is because we only secure the code in documentation can perfectly running on the corresponding master version. If you installed an old version from PyPI and run the newest script, we don't guarantee it work.

BTW, you can have a try at [examples](https://github.com/thu-ml/tianshou/tree/master/examples) and [test](https://github.com/thu-ml/tianshou/tree/master/test). I guess those are what you're looking for.

**Comment by wlpku123** [comment]
Thank you and I'll have a try.

**Comment by wlpku123** [comment]
I'm wondering if there's any documentation that explains how can we use tianshou with customized environments, like `make_vec_env` in stable_baselines:

```python
from stable_baselines.common import make_vec_env
env = make_vec_env(lambda: dl_game_gym, n_envs=1) 
env = gym.make(lambda: dl_game_gym, n_envs=1)
```

**Comment by Trinkle23897** [comment]
https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation
