### ISSUE TITLE
invalid combination of arguments when using Discrete SAC algorithm

### ISSUE THREAD

**Issue by ccdxh** [thu-ml/tianshou#343]
Hello, thanks for providing such an efficient and concise tool.
I 'm trying to use the Discrete SAC algorithm in this library with custom environment. I uses the example structure from the examples in the document, and reported the following error. Do you have any idea about it? Thank you!

TypeError: min() received an invalid combination of arguments - got (tuple, tuple), but expected one of:
 * (Tensor input)
 * (Tensor input, name dim, bool keepdim, *, tuple of Tensors out)
 * (Tensor input, Tensor other, *, Tensor out)

```python
    def _target_q(
        self, buffer: ReplayBuffer, indice: np.ndarray
    ) -> torch.Tensor:
        batch = buffer[indice]  # batch.obs: s_{t+n}
        obs_next_result = self(batch, input="obs_next")
        dist = obs_next_result.dist
        target_q = dist.probs * torch.min(
            self.critic1_old(batch.obs_next),
            self.critic2_old(batch.obs_next),
        )
        target_q = target_q.sum(dim=-1) + self._alpha * dist.entropy()
        return target_q`
```

**Comment by Trinkle23897** [comment]
What's your critic network and what's your action space? It seems like the critic network outputs a tuple instead of a tensor of Q value (s -> Q(s), documented in the docstring params).

**Comment by ccdxh** [comment]
self.action_space = Discrete(9)

self.observation_space = Box(low=0, high=1000, shape=(1,107))

actor_net = Net(state_shape=state_shape, action_shape=action_shape, hidden_sizes=[128, 128, 128])
critic_net1 = Net(state_shape=state_shape, action_shape=action_shape, hidden_sizes=[128, 128, 128])
critic_net2 = Net(state_shape=state_shape, action_shape=action_shape, hidden_sizes=[128, 128, 128])

**Comment by Trinkle23897** [comment]
Please refer here:
https://github.com/thu-ml/tianshou/blob/a57503c0aa6d40a0c939b37f4ae3c3a83bb2e126/test/discrete/test_sac.py#L64-L78
critic1 is an instance of `Critic` instead of `Net`. Same as actor and critic2.
