### ISSUE TITLE
Loss of PG 

### ISSUE THREAD

**Issue by yingchengyang** [thu-ml/tianshou#35]
I'd like to ask about the loss about policy gradient:
    -(action_prob * r).sum()
where action_prob = dist.log_prob(a) is the probability of each action, in my opinion. And what's the meaning of r?
I think the meaning of r may be reward by the algorithm of PG. However, in CartPole-v0, I print r[i] and find it is like 0.3532, -1.7669 and so on, but the reward in CartPole-v0 each step should be 1 or loss. So I'd ask about the meaning of r.  And if r isn't the reward, how can we get the reward?  Thanks :)

**Comment by Trinkle23897** [comment]
Yes, you are right, that's the discounted returns.
Btw, before training the policy, it performs a reward scaling:
https://github.com/thu-ml/tianshou/blob/205698dd666e2ac915ea0fd270cfd6eb7dbe682f/tianshou/policy/modelfree/pg.py#L74
I'll add an argument `--rew-norm` later in test_pg.py.

**Comment by yingchengyang** [comment]
Thanks for your reply:).
So does r[i] mean the discounted reward after one action?
And in the training stage of PG, we can update the parameters with the datas of different trajectorys. So how can we get the total reward(maybe discounted) of each trajectory in the training stage? 
Thanks a lot :)

**Comment by yingchengyang** [comment]
Thanks a lot! :)

**Comment by Trinkle23897** [comment]
Assume we have a trajectory with 4 timesteps: s0, s1, s2, s3
| timestep | 0 | 1 | 2 | 3 |
| --- | --- | --- | --- | --- |
|reward| r0 | r1 | r2 | r3 |
|done| 0 | 0 | 0 | 1| |

Once we have a discount factor g (in test_pg.py it is 0.9), we compute the returns as:
G3 = r3
G2 = r2 + r3 * g
G1 = r1 + r2 * g + r3 * g^2
G0 = r0 + r1 * g + r2 * g^2 + r3 * g^3
The `compute_episodic_return` does this thing, in other words, `batch.returns` == `G`.

Tianshou collects different trajectories but stores them chronologically. You can check out the Collector's documentation for more details.

**Comment by yingchengyang** [comment]
Thanks! So are all elements of  batch.returns the discounted reward of a trajectory, like G0?  Or may some elements of  batch.returns   be the discounted reward of a part of trajectory, like G1,G2,G3?

What's more, I'd like to ask about why using rew-norm?  I try to not use rew-norm and find pg will converge much more slowly than using rew-norm.  Thanks a lot!

**Comment by Trinkle23897** [comment]
len(G) == len(r)
If the trajectory has T timesteps, the G_i is computed over r_i, r_{i+1}, r_{i+2}, ..., r_{T-1}
The network training procedure is quite unstable under no-norm input. This is just a code-level trick, many papers do not openly mention it.

**Comment by yingchengyang** [comment]
Thanks a lot!
