### ISSUE TITLE
Conservative Q-Learning (CQL) for offline/batch reinforcement learning

### ISSUE THREAD

**Issue by nuance1979** [thu-ml/tianshou#358]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
I would like to contribute an implementation of the discrete version of [Conservative Q-Learning (CQL)](https://arxiv.org/pdf/2006.04779.pdf), which claims to be better than prior works in some offline/batch tasks. I mostly used the authors' [code](https://github.com/aviralkumar2907/CQL) as reference and tried to follow the contributing guidelines.

A PR will be created soon. Your feedback is highly appreciated.

**Comment by Trinkle23897** [comment]
Thank you very much! I'll take a look after I finish my final exam tomorrow...

**Comment by nuance1979** [comment]
> BTW, are you interested in contributing continuous version CQL? I can provide Mujoco environment (any linux machine) for you if you want.

Sorry but I don't have much experience with continuous control problems so I'm not confident enough to take it on.
