### ISSUE TITLE
collector--239--self.env.render()

### ISSUE THREAD

**Issue by invisilmk** [thu-ml/tianshou#36]
TypeError: render() missing 1 required positional argument: 'mode'

**Comment by Trinkle23897** [comment]
It is related to your environment. Could you please tell me the environment name you use?

**Comment by Trinkle23897** [comment]
This is because the atari env wrapper doesn't have the default parameter in render. @Mehooz your unittest ???!!!

**Comment by invisilmk** [comment]
thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "n+e"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 晚上10:07
收件人: "thu-ml/tianshou"<tianshou@noreply.github.com&gt;; 
抄送: "李孟珂"<2662102609@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thu-ml/tianshou] collector--239--self.env.render() (#36)





 
This is because the atari env wrapper doesn't have the default parameter in render. @Mehooz your unittest ???!!!
