### ISSUE TITLE
One small question about the usage of torch.distribution on PG-like algorithm

### ISSUE THREAD

**Issue by lastditch222** [thu-ml/tianshou#360]
Hello, my question is that why transpose is needed in the usage of torch.distribution on PG-like algorithm. For example, in computing the log prob for action a, the code is
`log_prob = dist.log_prob(a).reshape(len(ret), -1).transpose(0, 1)`.  To my knowledge dist.log_prob(a) already has batch_size as its first dimension. I am not clear about this point. Thanks.

**Comment by Trinkle23897** [comment]
Because we need to support both continuous action space (Gaussian distribution) and discrete action space (Categorical distribution). This code snippet can do both of them.

**Comment by lastditch222** [comment]
What is the difference between continuous and categorical distribution? @Trinkle23897

**Comment by Trinkle23897** [comment]
```python
In [8]: import torch

In [9]: d = torch.distributions.Normal(torch.rand([bsz, 3]), torch.rand([bsz, 3]))

In [10]: d.log_prob(d.sample()).shape
Out[10]: torch.Size([32, 3])

In [11]: d = torch.distributions.Categorical(torch.rand([bsz, 3]))

In [12]: d.log_prob(d.sample()).shape
Out[12]: torch.Size([32])
```
