### ISSUE TITLE
What is the old version of numpy and networkx so the nx.Graph() can be saved as obs

### ISSUE THREAD

**Issue by yangysc** [thu-ml/tianshou#362]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [X] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [X] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  0.4.1 1.8.1+cpu 1.20.2 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] win32
  ```

Hi, @Trinkle23897 
 From the usage here, it seems the nx.Graph() cannot be used as before.  May I ask that, how canI still use this feature, since directly saving the graph object is more efficient, instead of the edge_list array.

Maybe in the future, tianshou can support the dgl.graph object. It stores the tensor internally. 

Thanks!
> 这个例子可能现在不太能work，因为numpy升级了，以及nx.Graph重写了__getitem__，导致np.array([nx.Graph()])会出来空的> 数组……
> 不过正常的自定义class应该没啥问题
>    import networkx as nx
>   b = ReplayBuffer(size=3)
>  b.add(obs=nx.Graph(), act=0, rew=0, done=0)
> print(b)

**Comment by Trinkle23897** [comment]
That's kind of weird.
```python
In [3]: import numpy as np

In [4]: np.array(example_graph())
Out[4]: array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 12,  7, 11, 10, 13, 14])

In [5]: list(example_graph())
Out[5]: [0, 1, 2, 3, 4, 5, 6, 8, 9, 12, 7, 11, 10, 13, 14]

In [6]: G=example_graph()

In [7]: G
Out[7]: <networkx.classes.graph.Graph at 0x7efbcc6eab50>

In [8]: np.asanyarray(G)
Out[8]: array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 12,  7, 11, 10, 13, 14])
```

It is because https://github.com/thu-ml/tianshou/blob/84f58636eb3895413c82cc3a991bf0f0e5b043ad/tianshou/data/batch.py#L51-L60

In L57 we use `np.asanyarray` to automatically convert any potential object to a numpy-compatible array. For example, if you define a class that is not overwrite `__getitem__`:

```python
In [9]: class A:
   ...:     pass
   ...: 

In [10]: np.asanyarray(A())
Out[10]: array(<__main__.A object at 0x7efbccf7a340>, dtype=object)
```

you can see `np.asanyarray` works fine, but if it overwrites `__getitem__`:

```python
In [13]: class A:
    ...:     def __len__(self):
    ...:         return 3
    ...:     def __getitem__(self, k):
    ...:         return "123"[k]
    ...: 

In [14]: np.asanyarray(A())
Out[14]: array(['1', '2', '3'], dtype='<U1')
```

In fact, nx.Graph() does the exact same thing, so that even the basic `np.array(G)` will be converted into a float array by numpy.

> what if we use other approaches instead of np.asanyarray?

Do you have any better idea to differentiate `v=nx.Graph()`, `v=[nx.Graph(), nx.Graph()]`, `v=[nx.Graph(), 1]`, `v=[2.0, 3.0]`, `v=2`, `v=np.array([1,2,3])`, `v=np.array(3)`, `v=np.array([1, "s"], dtype=object)`, `v=torch.Tensor([1, 2, 3])` without using `np.asanyarray`?

> May I ask that, how canI still use this feature, since directly saving the graph object is more efficient, instead of the edge_list array.

I just tried the old version but cannot reproduce the result I've gotten previously. I also tried py36+nx==2.2+np==1.16.6 :(

**Comment by Trinkle23897** [comment]
Just a temporary fix: you can use a gym.wrapper to split your data in the original graph into several (nested) arrays and tensors, and that would be quicker. I'll fix this issue later.

**Comment by yangysc** [comment]
> > Do you mean different types data are used as obs？ Maybe users can declare an observation space, like rllib did.
> 
> No, `Batch` is designed for general purpose.

Yes, being more general means being more flexible.

But for a specific application, why the batch should expect different types of input data? I think the ob space for one task is fixed.
It is very nice for `Batch` to support `nx.Graph()` if the user declares the observation as `nx.Graph`. Other libraries, like rllib cannot support non-tensor/non-array types.

**Comment by yangysc** [comment]
> No, Batch is designed for general purpose.

I see, thanks

**Comment by yangysc** [comment]
> Just a temporary fix: you can use a gym.wrapper to split your data in the original graph into several (nested) arrays and tensors, and that would be quicker. I'll fix this issue later.

Just to ask, should I still split the data into arrays or I should wait for fixing the issue?  I just never use nx.Graph before directly as observation for RL :),

**Comment by Trinkle23897** [comment]
the former

**Comment by yangysc** [comment]
> the former

Got it. Thanks

**Comment by yangysc** [comment]
> Just a temporary fix: you can use a gym.wrapper to split your data in the original graph into several (nested) arrays and tensors, and that would be quicker. I'll fix this issue later.

Sorry for bothering you again. Similar to this [issue](https://github.com/thu-ml/tianshou/issues/351), I tried to store the edges and node features for a `nx.Graph` as below. The state is a dict, so I borrowed the usage from [here](https://tianshou.readthedocs.io/en/latest/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation). But it seems the `ReplayBuffer` do not support variable-length obs. In my view, the state has to be stored in the buffer internally. Did I miss out something?

```python
from tianshou.data import Batch, ReplayBuffer
import networkx as nx
import numpy as np
# import dgl
import gym
from tianshou.env import DummyVectorEnv, SubprocVectorEnv



class GraphEnv(gym.Env):
    def __init__(self, size):
        self.size = size
        self.feat_dim = 32
        # generate a random graph with size number of nodes
        self.graph = nx.random_regular_graph(2, size)


    def reset(self):

        # node feats
        node_feats = np.random.rand(self.size, self.feat_dim)

        edge_list = list(self.graph.edges())
        return {"edge_list": np.asarray(edge_list, dtype=object), "node_feats": node_feats}

    def step(self, action):

        node_feats = np.random.rand(self.size, self.feat_dim)
        edge_list = list(self.graph.edges())
        return {"edge_list": np.asarray(edge_list, dtype=object), "node_feats": node_feats}, 1, False, {}

    def seed(self, seed=None):
        pass


if __name__ == '__main__':

    # train_envs = SubprocVectorEnv([lambda: GraphEnv(i) for i in [5, 10, 15]])
    train_envs = DummyVectorEnv([lambda i=x: GraphEnv(size=i) for x in [5, 10, 15]])

    env_obs = train_envs.reset()
    b = ReplayBuffer(size=3)

    for i in range(env_obs.size):
        b.add(Batch(obs=env_obs[i], act=0, rew=0, done=0))
    print(b)
```

The error is:
```
Traceback (most recent call last):
  File "E:\tianshou-master\tianshou\data\buffer\base.py", line 224, in add
    self._meta[ptr] = batch
  File "E:\tianshou-master\tianshou\data\batch.py", line 258, in __setitem__
    self.__dict__[key][index] = value[key]
  File "E:\tianshou-master\tianshou\data\batch.py", line 258, in __setitem__
    self.__dict__[key][index] = value[key]
ValueError: shape mismatch: value array of shape (10,2)  could not be broadcast to indexing result of shape (1,5,2)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "E:\tianshou-master\tianshou\data\batch.py", line 258, in __setitem__
    self.__dict__[key][index] = value[key]
  File "E:\tianshou-master\tianshou\data\batch.py", line 258, in __setitem__
    self.__dict__[key][index] = value[key]
ValueError: shape mismatch: value array of shape (10,2)  could not be broadcast to indexing result of shape (1,5,2)
python-BaseException
```

Thank you

**Comment by Trinkle23897** [comment]
It seems like previous solution (#352) does not address nested observation with various length of arrays. I'll try to deal with it ~~tomorrow~~ this weekend :(

**Comment by yangysc** [comment]
If so, I really appreciate for your help. Hope you can fix it tomorrow, since I really need it to speed up the experiments. Padding with zeros for different observations like rllib/sb3 is really time-costly :(

**Comment by Trinkle23897** [comment]
Could you please have a try with #375? Thanks!

**Comment by yangysc** [comment]
> Could you please have a try with #375? Thanks!

I have test it on my task. It is fine to run. Thanks!

**Comment by Trinkle23897** [comment]
That's cool, but I want to make sure this works in more general cases. Do you have any other tests on more complicated batch operations?

**Comment by yangysc** [comment]
I think the `dict` input with the variable shape is quite complicated... I would try test more cases tomorrow.

**Comment by Trinkle23897** [comment]
How about this https://github.com/thu-ml/tianshou/issues/369#issuecomment-847845988?
