### ISSUE TITLE
test_a2c_with_il.py error

### ISSUE THREAD

**Issue by cutebomb** [thu-ml/tianshou#364]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
0.4.1 1.7.0 1.19.5 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] win32

run test_a2c_with_il.py
with AssertionError: array([0.5068939, 0.4931061], dtype=float32) (<class 'numpy.ndarray'>) invalid
seem no rounding in map_action?

**Comment by Trinkle23897** [comment]
Could you please provide the full traceback result instead of only a single line?

**Comment by cutebomb** [comment]
ok with updated github code. thanks

**Comment by Trinkle23897** [comment]
I mean the detailed error message, not the code ;)
Because I cannot reproduce the same error in win10 64bit

**Comment by Trinkle23897** [comment]
No response, close now :(
