### ISSUE TITLE
Retro enviroement?

### ISSUE THREAD

**Issue by hlsafin** [thu-ml/tianshou#365]
Anyone was able to run any of the models in a retro environment? Sorry if this is too vague or to general, i'm just looking for some guidance .

**Comment by Trinkle23897** [comment]
It's the same as running other customized gym environments. In short, you need to use observation_space and action_space to build your network and policy, and other staff is the same as examples we provided. See #50, #69, or https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation
