### ISSUE TITLE
Why does `compute_episodic_return` uses returns + advantage?

### ISSUE THREAD

**Issue by drozzy** [thu-ml/tianshou#372]
I'm trying to implement a simple PG algorithm in tianshou.
Currently I'm looking at the function below.
What I don't understand is how this line results in computing returns: `returns = advantage + v_s`?
Also, is there a non-gae return function somewhere? 

Thank you very much.

Source: https://github.com/thu-ml/tianshou/blob/655d5fb14fe85ea9da86b441456286fa1f078384/tianshou/policy/base.py#L272
```python
def compute_episodic_return(
        batch: Batch,
        buffer: ReplayBuffer,
        indice: np.ndarray,
        v_s_: Optional[Union[np.ndarray, torch.Tensor]] = None,
        v_s: Optional[Union[np.ndarray, torch.Tensor]] = None,
        gamma: float = 0.99,
        gae_lambda: float = 0.95,
    ) -> Tuple[np.ndarray, np.ndarray]:
        
        rew = batch.rew
        if v_s_ is None:
            assert np.isclose(gae_lambda, 1.0)
            v_s_ = np.zeros_like(rew)
        else:
            v_s_ = to_numpy(v_s_.flatten())  # type: ignore
            v_s_ = v_s_ * BasePolicy.value_mask(buffer, indice)
        v_s = np.roll(v_s_, 1) if v_s is None else to_numpy(v_s.flatten())

        end_flag = batch.done.copy()
        end_flag[np.isin(indice, buffer.unfinished_index())] = True
        advantage = _gae_return(v_s, v_s_, rew, end_flag, gamma, gae_lambda)
        returns = advantage + v_s
        # normalization varies from each policy, so we don't do it here
        return returns, advantage
```

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/blob/655d5fb14fe85ea9da86b441456286fa1f078384/tianshou/policy/modelfree/pg.py#L75-L76

set gae_lambda=1.0 will use reward-to-go, which is exactly the non-gae version. You can have a try with the following examples:

https://github.com/thu-ml/tianshou/blob/655d5fb14fe85ea9da86b441456286fa1f078384/test/base/test_returns.py#L21-L35

**Comment by araffin** [comment]
> What I don't understand is how this line results in computing returns: returns = advantage + v_s?

You will find an answer in the discussion here ;) : 
https://github.com/DLR-RM/stable-baselines3/pull/375#issuecomment-812742850

**Comment by drozzy** [comment]
Thanks so much guys. You are awesome.
