### ISSUE TITLE
Atari example for policy-based method like A2C, PPO

### ISSUE THREAD

**Issue by FastWind123** [thu-ml/tianshou#374]
Is there any example using A2C, PPO to train atari ?

**Comment by Trinkle23897** [comment]
will do in the next few weeks @ChenDRAG @yingchengyang

**Comment by FastWind123** [comment]
> will do in the next few weeks @ChenDRAG @yingchengyang

OK, thank you!

**Comment by Syzygianinfern0** [comment]
Any updates on this? It would be really helpful.

**Comment by Syzygianinfern0** [comment]
https://gist.github.com/Syzygianinfern0/63d6b2b2ec5342865510da861eb97938
This is my attempt at it, but the agent does not converge.

**Comment by Syzygianinfern0** [comment]
![image](https://user-images.githubusercontent.com/31875325/126896380-b7860045-f25f-486f-a356-8a79c5397777.png)

🔶 => [DQN](https://github.com/thu-ml/tianshou/blob/c19876179a52acdc4d2e7dcb10dfbb4557adca86/examples/atari/atari_dqn.py) 
🔷 => DiscreteSAC

Environment: PongNoFrameskip-v4

**Comment by Syzygianinfern0** [comment]
@Trinkle23897 do you have any script for hyperparam search for agents?

**Comment by Trinkle23897** [comment]
I'll take a look this weekend, but usually sac-discrete cannot achieve good performance on atari games.

**Comment by destinyyzy** [comment]
The performance of PPO (implemented by tianshou) can hardly improve in Atari.

**Comment by Trinkle23897** [comment]
I know but I have already find the bug, it is because list(param) + list(param) will cause undefined behavior and should be changed with set(param).union(param). After fixing this bug, I can train Pong within 10 mins in my laptop:
![2021-08-24 18-11-02屏幕截图](https://user-images.githubusercontent.com/8189182/130599034-6152626b-e5f2-4569-be9f-e052fb7f09d8.png)

I'll push the code after finishing benchmarking.

**Comment by destinyyzy** [comment]
> I know but I have already find the bug, it is because list(param) + list(param) will cause undefined behavior and should be changed with set(param).union(param). After fixing this bug, I can train Pong within 10 mins in my laptop:
> ![2021-08-24 18-11-02屏幕截图](https://user-images.githubusercontent.com/8189182/130599034-6152626b-e5f2-4569-be9f-e052fb7f09d8.png)
> 
> I'll push the code after finishing benchmarking.

Can you share me the code by email?
I change the list + list in PPO, but I do not find the improvement in performance.

**Comment by Trinkle23897** [comment]
I'll make a pull request, but these two days I have no time because I'm going to fly to America from Singapore (which takes a long time though...)

**Comment by bingykang** [comment]
Hi @destinyyzy,  

Please find the demo [code](https://github.com/thu-ml/tianshou/files/7059884/atari_ppo.zip) by @Trinkle23897. 

Besides, you also need to replace https://github.com/thu-ml/tianshou/blob/291be08d43235c7dc930444174ed7c8824f1c43b/tianshou/policy/modelfree/ppo.py#L142 with 
```py 
set(self.actor.parameters()).union(self.critic.parameters()),
```
Hope you find it helpful. 

ps. please change `Pong-v5` to `PongNoFrameskip-v4`

**Comment by GongYanfu** [comment]
so is there any example using A2C to train atari games?
