### ISSUE TITLE
The performance upper bound of Mujoco Tasks

### ISSUE THREAD

**Issue by GoingMyWay** [thu-ml/tianshou#378]
- [x] I have marked all applicable categories:
    + [x] documentation request (i.e. "X is missing from the documentation.")
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates

Hi, there are many Mujoco tasks, I wonder can you provide the best performance (upper bound) of Mujoco tasks in the Doc.?

**Comment by Trinkle23897** [comment]
All we know are in https://github.com/thu-ml/tianshou/blob/master/examples/mujoco/README.md, including numerical results.
In fact, "performance upper bound" is not a clear term in this setting. Maybe the next year someone proposes an algorithm better than SAC, whose score is much higher than our current best result.

**Comment by GoingMyWay** [comment]
> All we know are in https://github.com/thu-ml/tianshou/blob/master/examples/mujoco/README.md, including numerical results.
> In fact, "performance upper bound" is not a clear term in this setting. Maybe the next year someone proposes an algorithm better than SAC, whose score is much higher than our current best result.

Thanks. The "performance upper bound" I think is the best performance of the environment designed for RL.  For example, the best speed for an ordinary car can be 180km/h.

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/blob/master/examples/mujoco/README.md#sac
SAC can achieve most of the env's best result, however, some environments like swimmer-v3 cannot (DDPG is the best).
https://tianshou.readthedocs.io/en/master/tutorials/benchmark.html <-- this interactive graph can give you some insights

**Comment by GoingMyWay** [comment]
> https://github.com/thu-ml/tianshou/blob/master/examples/mujoco/README.md#sac
> SAC can achieve most of the env's best result, however, some environments like swimmer-v3 cannot (DDPG is the best).
> https://tianshou.readthedocs.io/en/master/tutorials/benchmark.html <-- this interactive graph can give you some insights

Thanks.
