### ISSUE TITLE
How to save ReplayBuffer?

### ISSUE THREAD

**Issue by c4cld** [thu-ml/tianshou#379]
I want to do some experiments about offline RL, which need a large amount of state-action(distribution)-reward-next state-next action(distribution)  tuple. How to save ReplayBuffer?

**Comment by Trinkle23897** [comment]
https://tianshou.readthedocs.io/en/master/tutorials/concepts.html#buffer

![2021-06-10 14-50-13屏幕截图](https://user-images.githubusercontent.com/8189182/121478115-3e0dd400-c9fb-11eb-8b11-97337280513f.png)

```python
...
>>> # save to file "buf.pkl"
>>> pickle.dump(buf, open('buf.pkl', 'wb'))
>>> # save to HDF5 file
>>> buf.save_hdf5('buf.hdf5')

...

>>> buf = pickle.load(open('buf.pkl', 'rb'))  # load from "buf.pkl"
>>> len(buf)
3
>>> # load complete buffer from HDF5 file
>>> buf = ReplayBuffer.load_hdf5('buf.hdf5')
>>> len(buf)
3
```

**Comment by c4cld** [comment]
Thank you for your prompt reply and selfless help  ^_^
