### ISSUE TITLE
ReplayBuffer With Key Different from Reserved Key

### ISSUE THREAD

**Issue by liziniu** [thu-ml/tianshou#380]
Hello, I want to know how to store data that is different from reserved keys like obs and act.

Thanks

**Comment by Trinkle23897** [comment]
You can use nested dict such as `Batch(obs={"orig_obs": obs, "key1": value1, ...})`. And in the network side, use `s.key1` or `s["key1"]` to extract them from dict obs.
Also you can store others in `info` (using out of network) or `policy` (data generated from `policy.forward`).

**Comment by liziniu** [comment]
I get it. Thanks!
