### ISSUE TITLE
How to get the output of hidden layers?

### ISSUE THREAD

**Issue by c4cld** [thu-ml/tianshou#382]
I want to get the output of hidden layers of SAC actor network and critic networks, to do something such as knowledge distillation, but I do not know how to change SACpolicy or other code to achieve this goal. Could you give me some hints? Thank you very much

**Comment by Trinkle23897** [comment]
You can overwrite the original forward function and pass extra result from the network side, e.g.,
```python
# modify the network, just an example
class MyNetwork(nn.Module):
  ...
  def forward(self, s, state=None, info={}, **kwargs):
    result_hidden1 = self.model1(s)
    result_hidden2 = self.model2(result_hidden1)
    result_final_mu, result_final_sigma = self.model3(result_hidden2)
    return (result_final_mu, result_final_sigma, result_hidden1, result_hidden2), None

# then pass the network into policy, overwrite `policy.forward`:
class MyPolicy(XXXPolicy):
  def __init__(self, ..., my_model, ...):
    super().__init__(...)
    self.actor = my_model
  ...
  def forward(self, batch, state=None, ...):
    obs = batch[input]
    (mu, sigma, hidden1, hidden2), h = self.actor(obs, state=state, info=batch.info)
    ...
    return Batch(act=act, policy=Batch(hidden1=hidden1, hidden2=hidden2))
```

By using the key `policy`, it can store the intermediate result from `policy.forward` into ReplayBuffer. The rest of the thing is to use Collector plus this customized policy to gather tons of transitions from environments, and you'll find the hidden layers' result in `buffer.policy.hidden1` and `buffer.policy.hidden2`, both of them are `torch.Tensor`.

**Comment by c4cld** [comment]
Thank you for your prompt reply and selfless help. I'll follow your advice.
