### ISSUE TITLE
questions about log_tools

### ISSUE THREAD

**Issue by caimingxue** [thu-ml/tianshou#383]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
It seems that the some data, such like the actor loss, critic loss, can not be shown via tensorboard. I see that the log_tools has no functions to save these data OR these data is not written by "writer.add_scalars"?

**Comment by Trinkle23897** [comment]
Could you please point out the related algorithm that you use? Maybe there's an inconsistent modification.

**Comment by caimingxue** [comment]
> Could you please point out the related algorithm that you use? Maybe there's an inconsistent modification.

I use the SAC (test_sac_with_il),  then I use the tensorboard to show the events, just generate curves of the tag: train/rew.

**Comment by Trinkle23897** [comment]
I just run on my local computer:
![2021-06-22 16-13-59屏幕截图](https://user-images.githubusercontent.com/8189182/122888939-ec5b3700-d374-11eb-833a-d9ddf858ec1b.png)

**Comment by caimingxue** [comment]
Yes, So, why there are no curves for loss, test, and alpha

**Comment by Trinkle23897** [comment]
Because in Logger the update_interval is set to 1000 by default. You can set it to 1 and get the following curves:
![2021-06-22 16-21-22屏幕截图](https://user-images.githubusercontent.com/8189182/122890020-e580f400-d375-11eb-96c3-26130bf18c9e.png)

```python
    logger = BasicLogger(writer, update_interval=1)
```

**Comment by caimingxue** [comment]
Ok, It works. Thanks!
