### ISSUE TITLE
`preprocess_fn` called two times per step when one env is done

### ISSUE THREAD

**Issue by externalsupplierstaff** [thu-ml/tianshou#389]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  >>> for pkg in [tianshou, torch, numpy]: print(pkg.__name__, pkg.__version__)
   ... 
   tianshou 0.4.2
   torch 1.9.0
   numpy 1.20.2
   >>> sys.version, sys.platform
   ('3.9.5 (default, Jun  4 2021, 12:28:51) \n[GCC 7.5.0]', 'linux')
   ```

Hey, thanks for the package. I like it, is intuitive and much more transparent than SB3.

My problem is the following:
- My RL environment has as state one image.
- I would like to provide the agent with image features (extracted using a fixed network) instead of with the whole image. 
- I also want to compute other features.
- As NNs work faster with batched data, I intend to wrap the env into some Vectorized Environment (so far using `DummyVectorEnv`)

I tried to use `preprocess_fn` to forward pass the batch of images over the network.
However, I found that when one environment returns `done=True` and there is a call to `reset()` for one or more of the "parallel" environments, after that there is another call to `preprocess_fn`, this time using only a smaller batch. If episodes are short (like in my case), then this is costly.

Maybe it would be good to call `preprocess_fn` after resetting, but I understand it could break other flows (rendering, etc.). Now I'm moving the network to the agent side. But it could be cool if a solution to this is found. It will probably imply ignoring the last observation of an episode.

**Comment by Trinkle23897** [comment]
But I don't think there's another way we can do it more efficiently. 

reset - preprocess(obs)
step 1 - preprocess(obs_next), reuse last step obs
step 2 - preprocess(obs_next), reuse last step obs
...
done - reset, preprocess(obs)
step 1 - ... (same as above)
...

**Comment by Trinkle23897** [comment]
![image](https://user-images.githubusercontent.com/8189182/124282874-e25be400-db7d-11eb-95d7-ab288c6525a5.jpeg)

A clearer figure

**Comment by externalsupplierstaff** [comment]
Thanks for your kind answer. As I said, I solved this by moving to the agent side. However, let me explain this further to see if it makes sense for you (or not).

For a single env the current method works and makes sense. And probably it's not slow at all. The thing is that in collector we are roughly calling (order as in the `collect()` while loop):
```python
policy(data)  # (with preprocessed data)
obs_next = step(action_remap)
data.update(obs_next)
preprocess_fn(obs_next)
if done:
  obs = reset()
  obs_next = preprocess_fn(obs)
```
which is two calls to preprocess when `done`. 
But we could do:
```python
policy(data)  # (with preprocessed data)
obs_next = step(action_remap)
data.update(obs_next)
if done:
  obs = reset()
  update_obs_next_with_obs()
  obs_next = preprocess_fn(obs_next)
```

Of course, there are some drawbacks: the last observation won't be considered for the buffer nor the rendering and `preprocess_fn` should not change the `done` flag for this to work. It is just an idea motivated by the performance loss of a `preprocess_fn` that enjoys great speedups when given a batch of data (e.g. CNN) if we give frequently pass little batches (each time an environment is reset).

In any case, if we move to the agent side, this can be solved in `forward` (at least that's how I'm doing it). 

I hope this helps at least to have the idea in mind. Feel free to close the issue :)

**Comment by Trinkle23897** [comment]
Actually if we change the semantic of `env.step` a little bit to "automatically reset when done=True", this annoying issue would be gone. (in fact, that's [dm_env](https://github.com/deepmind/dm_env/) API).
