### ISSUE TITLE
`preprocess_fn` does not receive env index

### ISSUE THREAD

**Issue by externalsupplierstaff** [thu-ml/tianshou#390]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:

 I want to compute one feature per environment only at reset time and persist it. I can not do it inside `preprocess_fn` because although I know when environments are reset, I don't know which one it is and I can not save that value as an attribute. The other solution is to implement this on the environment itself or in the agent. Is this the idea?

**Comment by Trinkle23897** [comment]
I'll do it today. It needs to change some code in collector.

**Comment by Trinkle23897** [comment]
@externalsupplierstaff could you please check #391? Thanks!

**Comment by externalsupplierstaff** [comment]
Thank you! 
I'm sorry I moved on and implement it on the environment side. But your enhancement speed is incredible and hopefully this will useful for the future. I will let you know if I refactor my code again to the old way (using `preprocess_fn`). I'm happy to be using this library 😄
