### ISSUE TITLE
It seems to be wrong equation (but does not matter)

### ISSUE THREAD

**Issue by Triple-ROCK** [thu-ml/tianshou#393]
https://github.com/thu-ml/tianshou/blob/c19876179a52acdc4d2e7dcb10dfbb4557adca86/tianshou/policy/modelfree/qrdqn.py#L82

mean(-1).sum(1)

**Comment by Trinkle23897** [comment]
@nuance1979

**Comment by nuance1979** [comment]
I think it really doesn't matter. The shape of `u` is (batch_size, num_quantiles, num_quantiles).

As a reference, see https://github.com/ku2482/fqf-iqn-qrdqn.pytorch/blob/11d70bb428e449fe5384654c05e4ab2c3bbdd4cd/fqf_iqn_qrdqn/utils.py#L47-L48
