### ISSUE TITLE
optimizer double update ? deprecation soon

### ISSUE THREAD

**Issue by externalsupplierstaff** [thu-ml/tianshou#395]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
Hey, I just want to say it may be needed a `set()` wrapping the list of params in
https://github.com/thu-ml/tianshou/blob/c19876179a52acdc4d2e7dcb10dfbb4557adca86/test/discrete/test_ppo.py#L79

this is related to the warining

```
UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information                                                                                     super(Adam, self).__init__(params, defaults)                                                    
```

The current version of the PPO test is updating some parameters twice, which could be the intended behavior but it won't be possible in the future.

**Comment by Trinkle23897** [comment]
You can use `set(actor.parameters()).union(critic.parameters())`
