### ISSUE TITLE
why the warning in `save_fn`?

### ISSUE THREAD

**Issue by externalsupplierstaff** [thu-ml/tianshou#396]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:

From what I understand of the trainer code, `save_fn` saves the best model and `save_checkpoint_fn` saves the last model. I don't understand then why one is suggested over the other, if they do different things

**Comment by Trinkle23897** [comment]
Hmm okay, will remove this warning soon.
