### ISSUE TITLE
RayVectorEnv only starts Env processes on head node

### ISSUE THREAD

**Issue by xmzzyo** [thu-ml/tianshou#398]
- [ ] I have marked all applicable categories:
    + [X] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

Hi, I created a distributed Envs with the `RayVectorEnv`. But it seems that all the Env processes are started on the head node instead of in a distributed manner.

Here is my cluster info (one head node with two work nodes) with `ray status`:
```
======== Cluster status: 2021-07-13 16:29:50.367358 ========
Node status
------------------------------------------------------------
 1 node(s) with resources: {'node:10.1.21.216': 1.0, 'memory': 18901922612.0, 'object_store_memory': 9450961305.0, 'accelerator_type:GTX': 1.0, 'GPU': 2.0, 'CPU': 8.0}
 1 node(s) with resources: {'memory': 11445928346.0, 'CPU': 16.0, 'object_store_memory': 4905397862.0, 'node:10.0.0.41': 1.0}
 1 node(s) with resources: {'node:10.0.0.39': 1.0, 'CPU': 16.0, 'memory': 9745902388.0, 'object_store_memory': 4176815308.0}

Resources
------------------------------------------------------------
Usage:
 0.0/40.0 CPU
 0.0/2.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/37.340 GiB memory
 0.00/17.260 GiB object_store_memory

Demands:
 (no resource demands)
```

 
And this is my test code:

```
import gym
import socket
from tianshou.env import RayVectorEnv


class MyTestEnv(gym.Env):
    def __init__(self):
        print(socket.gethostbyname(socket.gethostname()))
        pass

    def seed(self, seed=0):
        pass

    def reset(self, state=0):
        pass

    def step(self, action):
        pass


def test_rayenv():
    env_fns = [lambda: MyTestEnv() for _ in range(30)]
    venv = RayVectorEnv(env_fns)  # DummyVectorEnv, ShmemVectorEnv, or RayVectorEnv, whichever you like.
    venv.reset()


if __name__ == "__main__":
    test_rayenv()
```

I print the IP address of each Env process, and it shows that all the processes are working on the head node.

```
2021-07-13 16:28:49,764	INFO services.py:1274 -- View the Ray dashboard at http://127.0.0.1:8266
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
2021-07-13 16:29:00,165	WARNING worker.py:1123 -- WARNING: 24 PYTHON workers have been started on a node of the id: fbb4f92e1518c21a9da0507c3f6ffb0c36e3cb5874f15c0f2c2e2ed5 and address: 10.1.21.216. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
127.0.1.1
```

Can you please check the `RayVectorEnv` or provide a usage example for me?

Thank you very much.

**Comment by Trinkle23897** [comment]
I'll check it tonight.

**Comment by Trinkle23897** [comment]
BTW could you please share how you configure the nodes (bash script) and a minimal pure python script that can use ray to call remote actors? (Because this part of code doesn't change for almost one year and I'm not an expert of ray) Thanks!

**Comment by xmzzyo** [comment]
Hi, I am sorry that I am new to ray and did not use a bash script or YAML file to configure the cluster, instead, I start the cluster manually. Specifically, I first execute `ray start --head` on the head node, and then execute `ray start --address='<head node ip>:6379' --redis-password='5241590000000000'` on work nodes. 
And I run my code on the head node.

Thank you!

**Comment by Trinkle23897** [comment]
Okay, so could you please help me figure out how a python script can use a remote ray node to execute (instead of localhost)?

**Comment by xmzzyo** [comment]
Hi, [This line](https://github.com/thu-ml/tianshou/blob/master/tianshou/env/venvs.py#L368) should be change to `ray.init(address='<head node IP>:<redis port>')` to connect the remote ray cluster.

Thank you.

**Comment by Trinkle23897** [comment]
So could you please add `ray.init(address='<head node IP>:<redis port>')` at the beginning of `test_rayenv()` and see the result?

**Comment by xmzzyo** [comment]
Hi, I had modified the `ray.init()` in tianshou's source code and import the modified tianshou in my project, which occurred the issue I reported above. 

Besides, I also tried to add `ray.init(address='<head node IP>:<redis port>')` in `test_rayenv` , and it still has the same issue.

Thank you.

**Comment by xmzzyo** [comment]
Thank you for your explanation! I have fixed my code.
