### ISSUE TITLE
Missing sum over log_prob in SAC

### ISSUE THREAD

**Issue by nicoguertler** [thu-ml/tianshou#40]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x]  I have searched through the [issue categories] for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
yields
```
0.2.2 1.5.0 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] linux
```
When running `halfcheetahBullet_v0_sac.py` I get the pytorch warning:
```
tianshou/tianshou/policy/modelfree/sac.py:111: UserWarning: Using a target size (torch.Size([128, 6])) that is different to the input size (torch.Size([128, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
```
This is caused by target_q having the wrong shape which in turn stems from log_prob. In order to fix this, log_prob should be summed over dimension 1 in the forward method:
```python
log_prob = dist.log_prob(x) - torch.log(
            self._action_scale * (1 - y.pow(2)) + self.__eps)
log_prob = torch.unsqueeze(torch.sum(log_prob, 1), 1)
```
This should be correct because dist.log_prob(x) gives log_prob for a univariate Gaussian for each action dimension. As the covariance matrix is diagonal, the probability density factorizes and the log of the multivariate Gaussian is the sum of the individual log_probs.
Code as it is now:
https://github.com/thu-ml/tianshou/blob/959955fa2afac799943991f4735940f6c94f5f04/tianshou/policy/modelfree/sac.py#L80-L92

Let me know if you agree and if I should make a pull request.

By the way, I really like the modularity of Tianshou! Thank you for your work.

**Comment by Trinkle23897** [comment]
Yes, PR is quite welcome!!!

**Comment by nicoguertler** [comment]
Thank you for your quick reaction!

**Comment by huiwenzhang** [comment]
Why this PR haven't been merged to the master branch?

**Comment by Trinkle23897** [comment]
> Why this PR haven't been merged to the master branch?

This is merged a month ago. I don't know what you mean.

![2020-06-10 19-33-23 的屏幕截图](https://user-images.githubusercontent.com/8189182/84263015-4bc31c00-ab51-11ea-9354-3b3ac50fdf50.png)

**Comment by danagi** [comment]
> > Why this PR haven't been merged to the master branch?
> 
> This is merged a month ago. I don't know what you mean.
> 
> ![2020-06-10 19-33-23 的屏幕截图](https://user-images.githubusercontent.com/8189182/84263015-4bc31c00-ab51-11ea-9354-3b3ac50fdf50.png)

No, #49 added a new bug. Now it misses sum over log_prob in 
> https://github.com/thu-ml/tianshou/blob/3774258cc7887f858025650662169c691a4784e2/tianshou/policy/modelfree/sac.py#L103-L104

which should be
`        
log_prob = dist.log_prob(x) - torch.log(
            self._action_scale * (1 - y.pow(2)) + self.__eps).sum(-1, keepdim=True)
`

See that, `dist.log_prob(x)` has already summed over log_prob in `DiagGaussian`, so only the latter part misses summing.

**Comment by Trinkle23897** [comment]
@imoneoi

**Comment by Trinkle23897** [comment]
@danagi fixed and many thanks for pointing out!
