### ISSUE TITLE
Distribution erorrs at PPO

### ISSUE THREAD

**Issue by kiwi-sherbet** [thu-ml/tianshou#400]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

Hi, I am currently running PPO with version 0.4.1 and getting the following errors.  Has anyone experienced a similar issue?

```

Traceback (most recent call last):
  File "src/train.py", line 173, in <module>
    train()
  File "src/train.py", line 163, in train
    result = onpolicy_trainer(
  File "/home/user/.pyenv/versions/ppoenv/lib/python3.8/site-packages/tianshou-0.4.1-py3.8.egg/tianshou/trainer/onpolicy.py", line 151, in onpolicy_trainer
  File "/home/user/.pyenv/versions/ppoenv/lib/python3.8/site-packages/tianshou-0.4.1-py3.8.egg/tianshou/policy/base.py", line 241, in update
  File "/home/user/.pyenv/versions/ppoenv/lib/python3.8/site-packages/tianshou-0.4.1-py3.8.egg/tianshou/policy/modelfree/ppo.py", line 110, in learn
  File "/home/user/.pyenv/versions/ppoenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/.pyenv/versions/ppoenv/lib/python3.8/site-packages/tianshou-0.4.1-py3.8.egg/tianshou/policy/modelfree/pg.py", line 107, in forward
  File "src/train.py", line 117, in dist
    return Independent(Normal(*logits), 1)
  File "/home/user/.pyenv/versions/ppoenv/lib/python3.8/site-packages/torch/distributions/normal.py", line 50, in __init__
    super(Normal, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/user/.pyenv/versions/ppoenv/lib/python3.8/site-packages/torch/distributions/distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter loc has invalid values

```

The below is my environment:
0.4.1 1.8.1+cu111 1.20.3 3.8.5 (default, May 12 2021, 03:26:47) 
[GCC 9.3.0] linux

**Comment by Trinkle23897** [comment]
Could you please provide the training script (how do you use PPOPolicy)?

**Comment by kiwi-sherbet** [comment]
Thank you for your reply. I am trying to running the PPO implementation with my own gym-style environment (PyBullet).

The training script I am using is based on the example code `test/continuous/test_ppo.py`. The parameters I am using are the followings:

```
self.seed: int = 0
self.buffer_size:int = 4096
self.lr: float= 3e-4 
self.gamma:float =0.99
self.epoch:int =3000
self.step_per_epoch:int =50000
self.step_per_collect:int =2048*4
self.repeat_per_collect:int =10
self.batch_size:int = 256*32
self.training_num:int = 64
self.test_num:int = 10
self.rew_norm:int = True
self.vf_coef:float = 0.25
self.ent_coef:float = 0.0 #0.0
self.gae_lambda:float = 0.95
self.bound_action_method:str = "clip"
self.lr_decay:int = True
self.max_grad_norm:float = 0.5
self.eps_clip:float = 0.2
self.dual_clip:float = None
self.value_clip:int = 0
self.norm_adv:int = 0
self.recompute_adv:int = 1
```

**Comment by Trinkle23897** [comment]
could you please replace the `dist` function with the following and paste the result?
```python
    # replace DiagGuassian with Independent(Normal) which is equivalent
    # pass *logits to be consistent with policy.forward
    def dist(*logits):
        try:
            return Independent(Normal(*logits), 1)
        except ValueError as e:
            print(logits)
            print(logits[0].shape, logits[1].shape)
            raise ValueError from e
```

**Comment by kiwi-sherbet** [comment]
Would it okay to continue with errors?

**Comment by Trinkle23897** [comment]
No, but I want to know what causes this error, thus print it out. Just paste and run it.

**Comment by Trinkle23897** [comment]
No further response, consider closing now.

**Comment by Trinkle23897** [comment]
One possible reason: maybe your network is too deep -> unstable numeric result in value -> it generates nan after one policy.forward -> cause this error

**Comment by kiwi-sherbet** [comment]
I am sorry for late reply. You are right, there seem to be unstable simulation behavior. When I replaced it, I do not see the error anymore. Thank you!

**Comment by hedy14** [comment]
hi，I meet the same problem.  What's your solution to this problem?
1、Replace dist function as @Trinkle23897  said?
2、Decay the layer of network？

I try solution1:
Logits is all nan. I print b.adv and find out b.adv is increasing gradually. Finally b.adv is bigger than 1e36 and going to nan.
ps: b is input(batch) of tianshou/policy/modelfree/ppo.py: 104 learn.py.
