### ISSUE TITLE
Collecting demonstrations.

### ISSUE THREAD

**Issue by caozhangjie** [thu-ml/tianshou#402]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

After training a policy, is there any code in tianshou that I can use to collect demonstrations? I want to create some rollouts with the trained policy. I see that tianshou use some normalization on the states in the default examples. Do I need to pay attention to this when I use the policy to generate a trajectory?

**Comment by Trinkle23897** [comment]
You can refer here: https://github.com/thu-ml/tianshou/blob/c19876179a52acdc4d2e7dcb10dfbb4557adca86/test/discrete/test_dqn.py#L136-L142

> Do I need to pay attention to this when I use the policy to generate a trajectory?

Yes, you need to use the same normalization parameters. 

@ChenDRAG this is an issue for a long time, could you please fix it if you have time?

**Comment by caozhangjie** [comment]
Thanks. And the current examples do not save the normalization parameters. This may cause some problems.

**Comment by Trinkle23897** [comment]
Yeah you need to manually extract from vecenv.obs_rms, but this is only a must in on-policy algorithms because they use observation normalization.

**Comment by caozhangjie** [comment]
Thanks
