### ISSUE TITLE
Questions about stack_num/RNN in ReplayBuffer

### ISSUE THREAD

**Issue by drozzy** [thu-ml/tianshou#413]
In ReplayBuffer, I'm having difficulty understanding how `self.done` array field is set.
There is never a call to modify it in the ReplayBuffer class:
https://github.com/thu-ml/tianshou/blob/master/tianshou/data/buffer/base.py#L10

Any hints?

**Comment by drozzy** [comment]
I also can't figure out what these lines do here:
https://github.com/thu-ml/tianshou/blob/bba30f83d15106a73d673b0f7e2b9f988713b392/tianshou/data/buffer/base.py#L259-L261

I'm using stack_number = 10 with cart-pole and I'm trying to understand how stacking works.

**Comment by drozzy** [comment]
Ok, I see `prev` basically checks if the previous index was the end of the episode - and if so, it returns the same index. Otherwise it subtracts 1 from the current index.
Similarly `next` adds 1 to the current index and subtracts 1 if the current index was the end of the episode.

So line 261 says select all indicies that are some `stack_num - 2` steps into the past.

**Comment by drozzy** [comment]
I am still not sure what stack_num has to do with recurrent network.

**Comment by Trinkle23897** [comment]
take a look at this example:

```
index 0 1 2 3 4 5 6 7 8 9
done  F F T F T F F F T F
```

if we set stack_num==3, here are all available sample choices:

```
0 0 0
0 0 1
0 1 2
3 3 3
3 3 4
5 5 5
5 5 6
5 6 7
6 7 8
9 9 9
```

**Comment by Trinkle23897** [comment]
> There is never a call to modify it in the ReplayBuffer class:

`self.done` is set in `buffer.add`. It is exactly the same as gym's env.step 3rd return value.

**Comment by drozzy** [comment]
> > There is never a call to modify it in the ReplayBuffer class:
> 
> `self.done` is set in `buffer.add`. It is exactly the same as gym's env.step 3rd return value.

But I only see it being read in four places - and it is never assigned to:
https://github.com/thu-ml/tianshou/blob/master/tianshou/data/buffer/base.py#L119
https://github.com/thu-ml/tianshou/blob/master/tianshou/data/buffer/base.py#L127
https://github.com/thu-ml/tianshou/blob/master/tianshou/data/buffer/base.py#L135
https://github.com/thu-ml/tianshou/blob/master/tianshou/data/buffer/base.py#L343

**Comment by Trinkle23897** [comment]
Oh maybe you miss one thing: done is stored in self._meta, and self.done equals to self._meta.done or self._meta["done"] where self._meta is a Batch. This is defined in `__getattr__`.

Changing self.done will not affect self._meta.done, but changing self._meta.done will change self.done correspondly.

**Comment by drozzy** [comment]
Ooooh I see. Thanks that makes sense.

**Comment by drozzy** [comment]
> take a look at this example:
> 
> ```
> index 0 1 2 3 4 5 6 7 8 9
> done  F F T F T F F F T F
> ```
> 
> if we set stack_num==3, here are all available sample choices:
> 
> ```
> 0 0 0
> 0 0 1
> 0 1 2
> 3 3 3
> 3 3 4
> 5 5 5
> 5 5 6
> 5 6 7
> 6 7 8
> 9 9 9
> ```

How is this processed in the Recurrent network?
I see this bit here: https://github.com/thu-ml/tianshou/blob/dd4a01132cbb7fd70b2906619a05b187c91a41a7/tianshou/utils/net/common.py#L243

```
if len(s.shape) == 2:
            s = s.unsqueeze(-2)
        s = self.fc1(s)
        self.nn.flatten_parameters()
```

But I was expecting some sort of loop - that goes over the stack of `5 5 5` values.

**Comment by Trinkle23897** [comment]
If `stack_num` set to >1, buffer.sample will return with data shape [B, stack_num, ...] and it will pass to `policy.learn()`; meanwhile, in the collecting phase, the data pass to `policy.forward()` has the shape of [B, ...]. #19

**Comment by drozzy** [comment]
Of course, I see now.
Basically only during learning is the shape `L,N,H` (if we use [Pytorch LSTM convention](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html).) But during rollouts or evaluation the shape is just `L,H`. (Ref [this comment](https://github.com/thu-ml/tianshou/issues/19#issuecomment-619769590)).

And what this line does, is checks for the `L,H` case and converts the state to be single element sequence `L,1,H` so we can pass it into LSTM:
https://github.com/thu-ml/tianshou/blob/dd4a01132cbb7fd70b2906619a05b187c91a41a7/tianshou/utils/net/common.py#L243
