### ISSUE TITLE
preprocess_fn

### ISSUE THREAD

**Issue by fentuoli** [thu-ml/tianshou#415]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
tianshou.__version__: 0.4.2 
torch.__version__: 1.8.1+cu111 
numpy.__version__: 1.20.1 
sys.version: 3.8.8 (default, Apr 13 2021, 19:58:26)
sys.platform: [GCC 7.3.0] linux

I found during training at some point the data with batch format was changed, from owning six keys: obs, env_id, rew, done,obs_next,info,policy to owning 10 keys, the extra keys were adv,v_s, logp_old and returns, and the demension of obs was also changed. I don't know what happened. Could you please give me some advice on debugging?

**Comment by Trinkle23897** [comment]
could you please provide your training script?

btw, you can just ignore the extra arguments.

**Comment by fentuoli** [comment]
I copied your test_ppo.py，and modified Actor file.

```python
import os
import gym
import torch
import pprint
import argparse
import numpy as np
from torch.utils.tensorboard import SummaryWriter

# from tianshou.policy import PPOPolicy
from Policy.ppo import PPOPolicy
from tianshou.utils import BasicLogger
from tianshou.env import DummyVectorEnv
from net import Net
from tianshou.trainer import onpolicy_trainer
from Collector import Collector
from tianshou.data import VectorReplayBuffer
from tianshou.utils.net.discrete import Critic
from Actor import Actor


def test_ppo():
    task='Placement-v0'
    seed=0
    buffer_size=20000
    lr=1e-3
    gamma=0.99
    epoch=10
    step_per_epoch=50000
    episode_per_collect=20
    repeat_per_collect=2
    batch_size=64
    hidden_sizes=[64, 64]
    training_num=1
    test_num=1
    logdir='log'
    device='cuda' if torch.cuda.is_available() else 'cpu'
    # ppo special
    vf_coef=0.5
    ent_coef=0.0
    eps_clip=0.2
    max_grad_norm=0.5
    gae_lambda=0.95
    rew_norm=1
    dual_clip=None
    value_clip=1
    
    torch.set_num_threads(1)  # for poor CPU
    env = gym.make(task)
    env.reset()
    state_shape = env.observation_space.shape
    action_shape = env.action_space.shape
    train_envs = DummyVectorEnv(
        [lambda: gym.make(task) for _ in range(training_num)])
    test_envs = DummyVectorEnv(
        [lambda: gym.make(task) for _ in range(test_num)])
    # seed
    np.random.seed(seed)
    torch.manual_seed(seed)
    train_envs.seed(seed)
    test_envs.seed(seed)
    # model
    net = Net(state_shape, action_shape,128,device)
    actor = Actor(net, action_shape, device=device).to(device)
    critic = Critic(net, device=device).to(device)
    # orthogonal initialization
    for m in list(actor.modules()) + list(critic.modules()):
        if isinstance(m, torch.nn.Linear):
            torch.nn.init.orthogonal_(m.weight)
            torch.nn.init.zeros_(m.bias)
    optim = torch.optim.Adam(
        list(actor.parameters()) + list(critic.parameters()), lr=lr)
    dist = torch.distributions.Categorical
    policy = PPOPolicy(
        actor, critic, optim, dist,
        discount_factor=gamma,
        max_grad_norm=max_grad_norm,
        eps_clip=eps_clip,
        vf_coef=vf_coef,
        ent_coef=ent_coef,
        gae_lambda=gae_lambda,
        reward_normalization=rew_norm,
        dual_clip=dual_clip,
        value_clip=value_clip,
        action_space=env.action_space,
        deterministic_eval=True)
    # collector
    train_collector = Collector(
        policy, train_envs,
        VectorReplayBuffer(buffer_size, len(train_envs)))
    test_collector = Collector(policy, test_envs)
    # log
    log_path = os.path.join(logdir, task, 'ppo')
    writer = SummaryWriter(log_path)
    logger = BasicLogger(writer)

    def save_fn(policy):
        torch.save(policy.state_dict(), os.path.join(log_path, 'policy.pth'))

    def stop_fn(mean_rewards):
        return mean_rewards >= env.spec.reward_threshold

    # trainer
    result = onpolicy_trainer(
        policy, train_collector, test_collector, epoch,
        step_per_epoch, repeat_per_collect, test_num, batch_size,
        episode_per_collect=episode_per_collect, save_fn=save_fn,
        logger=logger)
    # assert stop_fn(result['best_reward'])

    if __name__ == '__main__':
        pprint.pprint(result)
        # Let's watch its performance!
        env = gym.make(task)
        policy.eval()
        collector = Collector(policy, env)
        result = collector.collect(n_episode=1, render=True)
        rews, lens = result["rews"], result["lens"]
        print(f"Final reward: {rews.mean()}, length: {lens.mean()}")


if __name__ == '__main__':
    test_ppo()

**Comment by fentuoli** [comment]
Before changing, the obs' dim should be 1\*25\*2, after changing, it became into 96\*25\*2, 32\*25\*2 and 120\*25\*2

**Comment by Trinkle23897** [comment]
It is because `episode_per_collect` argument in onpolicy-trainer. Every `collector.collect` will collect exactly this number of episodes and use this data to update policy. So that if your environment is not fix-length, say `Pendulum-v0` is always 200 steps per episode but `CartPole-v0` does not, the `policy.forward` function will receive various of batch-size input observation:
```
env 1 F F F F T
env 2 F T
env ...
env n F F F T
bsz   n n-1 ... 1
```

**Comment by Trinkle23897** [comment]
> to owning 10 keys, the extra keys were adv,v_s, logp_old and returns

Just ignore it.

**Comment by fentuoli** [comment]
Thanks for your quick reply. I didn't give you feedback immediately for I got flu two days ago.
My environment has fix-length which is 8. I try to give up using parameter `episode_per_collect` and choose to use `step_per_collect` . I set `step_per_collect` to 8.
At last, the same error appeared. This time, the dimension of obs and obs_next changed from (1,25,2) to (8,25,2), the dimension of rew and act changed from (1,) to (8,)

**Comment by Trinkle23897** [comment]
You can add an assert in preprocess_fn: once its shape is not what you want, it can directly throw an error and let you figure out the traceback. Hope this will help.

**Comment by fentuoli** [comment]
If you are not too troublesome, maybe you can check this file. I print `batch` before the `batch.obs` was passed into `self.actor` in `pg.py`.
Drag the file to the back, you will find how the batch change.
[output_obs.txt](https://github.com/thu-ml/tianshou/files/6997032/output_obs.txt)

**Comment by fentuoli** [comment]
> You can add an assert in preprocess_fn: once its shape is not what you want, it can directly throw an error and let you figure out the traceback. Hope this will help.

I will have a try,the main problem is that the setting of `step_per_collect` and `episode_per_collect` will affect the speed of error reporting. It makes me so confused! When I set `step_per_collect large enough , the program could run for more time and then report an error.

**Comment by Trinkle23897** [comment]
You can send the files (including customized ppo/actor/collector) to my email if you do not feel comfortable putting them here so that I can check what goes wrong. Currently, I can't run the script.

**Comment by fentuoli** [comment]
> You can send the files (including customized ppo/actor/collector) to my email if you do not feel comfortable putting them here so that I can check what goes wrong. Currently, I can't run the script.

It's very kind of you! I just send my code to your gmail, the title is `#issue 415`, I hope this won't cost you too much time!
Best wishes to you!
Oh, I forgot add an `__init__.py` in the folder, it may report an error !

**Comment by Trinkle23897** [comment]
resolved offline
