### ISSUE TITLE
PyTorch Lightning backend ?

### ISSUE THREAD

**Issue by tchaton** [thu-ml/tianshou#417]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [X] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:

Dear people from `thu-ml`, @Trinkle23897 @ChenDRAG @#2Trinkle23897

I wondered if there were any blockers to use PyTorch Lightning as the training engine within this library.

Best,
T.C

**Comment by Trinkle23897** [comment]
I personally don't want to use because I want it keep cleaning with pure pytorch. But if you'd like to integrate with the awesome pytorch-lightning, welcome pr!

**Comment by drozzy** [comment]
Found an example of possible integration here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/domain_templates/reinforce_learn_Qnet.py

But it just seems to remove all the nice tianshou concepts and replace them with pytorch ones - and I'm not sure wrapping replay Buffer with Dataset is very helpful.
