### ISSUE TITLE
batched env wrapper

### ISSUE THREAD

**Issue by ChenyangRan** [thu-ml/tianshou#42]
Hi, could you tell me how to save the episode?
I want to save the sate-action pairs, which are stored in ReplayBuffer. Because I want to use these pairs to update another model.

Thanks.

**Comment by Trinkle23897** [comment]
What does **sate**-action mean? Do you mean state-action pair?
The [replay buffer](https://tianshou.readthedocs.io/en/latest/api/tianshou.data.html#tianshou.data.ReplayBuffer) has a function [add](https://tianshou.readthedocs.io/en/latest/api/tianshou.data.html#tianshou.data.ReplayBuffer.add). You can click the hyperlink for digging it out.

**Comment by Trinkle23897** [comment]
"add one compare the new reward of (s, a, r, s')" where is it from? E.g. computed in policy.forward()?

**Comment by ChenyangRan** [comment]
> 
> 
> "add one compare the new reward of (s, a, r, s')" where is it from? E.g. computed in policy.forward()?

Such as when one epsiode has done, I want to compare the reward of this epsiode with the mean reward of other epsiodes in Buff.

**Comment by Trinkle23897** [comment]
So, do you think with another function `buffer.stat()` will help you do this thing better? Or maybe add some other APIs if you want. We can discuss here.

**Comment by ChenyangRan** [comment]
> 
> 
> So, do you think with another function `buffer.stat()` will help you do this thing better? Or maybe add some other APIs if you want. We can discuss here.

Yes, it maybe help. But I want to know how to use the api of buffer in collector？
Because I want to control each interaction with the env.
Could you please help me?
Thanks.

**Comment by Trinkle23897** [comment]
Aha, does it mean that a function hook before the `buffer.add` operation can meet your expectations?
```
batch_data = preprocess_fn(batch_data)
buffer.add(batch_data)
```

![a](https://user-images.githubusercontent.com/8189182/80941673-a01e0200-8e15-11ea-81eb-353f556a5ba9.jpg)

You can store and maintain the related variables in your own processor.

**Comment by Trinkle23897** [comment]
@ChenyangRan I add the draft implementation. Now you can pass your `preprocess_fn` to the collector.
This function receives typically 7 keys, as listed [here](https://tianshou.readthedocs.io/en/latest/api/tianshou.data.html#tianshou.data.Batch), and returns the modified part within a dict or a Batch. For example, you can write your hook as:
```python
import numpy as np
from collections import deque
class MyProcessor:
    def __init__(self, size=100):
        self.episode_log = None
        self.main_log = deque(maxlen=size)
        self.main_log.append(0)
        self.baseline = 0
    def preprocess_fn(**kwargs):
        """change reward to zero mean"""
        if 'rew' not in kwargs:
            # means that it is called after env.reset(), it can only process the obs
            return {}  # none of the variables are needed to be updated
        else:
            n = len(kwargs['rew'])  # the number of envs in collector
            if self.episode_log is None:
                self.episode_log = [[] for i in range(n)]
            for i in range(n):
                self.episode_log[i].append(kwargs['rew'][i])
                kwargs['rew'][i] -= self.baseline
            for i in range(n):
                if kwargs['done']:
                    self.main_log.append(np.mean(self.episode_log[i]))
                    self.episode_log[i] = []
                    self.baseline = np.mean(self.main_log)
            return Batch(rew=kwargs['rew'])
            # you can also return with {'rew': kwargs['rew']}
```
And finally, 
```python
test_processor = MyProcessor(size=100)
collector = Collector(policy, env, buffer, test_processor.preprocess_fn)
```
Some examples are in [test/base/test_collector.py](https://github.com/thu-ml/tianshou/blob/master/test/base/test_collector.py).

**Comment by mtaohuang** [comment]
This could be achieved via environment wrapper. Hope the framework to be simple and clean.

**Comment by Trinkle23897** [comment]
@edieson Yes, I know. In #25, #27 I mention gym.Wrapper as a universal solution.
The motivation I add this feature is that, the gym.wrapper cannot handle the data across different environments easily.

**Comment by mtaohuang** [comment]
It's just I don't think the preprocess_fn could (or should) do much, don't have much experience :)

**Comment by ChenyangRan** [comment]
> @ChenyangRan I add the draft implementation. Now you can pass your `preprocess_fn` to the collector.
> This function receives typically 7 keys, as listed [here](https://tianshou.readthedocs.io/en/latest/api/tianshou.data.html#tianshou.data.Batch), and returns the modified part within a dict or a Batch. For example, you can write your hook as:
> 
> ```python
> import numpy as np
> from collections import deque
> class MyProcessor:
>     def __init__(self, size=100):
>         self.episode_log = None
>         self.main_log = deque(maxlen=size)
>         self.main_log.append(0)
>         self.baseline = 0
>     def preprocess_fn(**kwargs):
>         if 'rew' not in kwargs:  # means that it is called after env.reset(), we can only process the obs
>             return {}  # none of the variables are needed to be updated
>         else:
>             n = len(kwargs['rew'])  # the number of envs in collector
>             if self.episode_log is None:
>                 self.episode_log = [[] for i in range(n)]
>             for i in range(n):
>                 self.episode_log[i].append(kwargs['rew'][i])
>                 kwargs['rew'][i] -= self.baseline
>             for i in range(n):
>                 if kwargs['done']:
>                     self.main_log.append(np.mean(self.episode_log[i]))
>                     self.episode_log[i] = []
>                     self.baseline = np.mean(self.main_log)
>             return Batch(rew=kwargs['rew'])
>             # you can also return with {'rew': kwargs['rew']}
> ```
> 
> And finally,
> 
> ```python
> test_processor = MyProcessor(size=100)
> collector = Collector(policy, env, buffer, test_processor.preprocess_fn)
> ```
> 
> Some examples are in [test/base/test_collector.py](https://github.com/thu-ml/tianshou/blob/master/test/base/test_collector.py).

Thanks，I will try it. You help me a lot.

**Comment by Trinkle23897** [comment]
> It's just I don't think the preprocess_fn could (or should) do much, don't have much experience :)

It can do more things. Instead of processing with batch-images (for atari), it can also save the log into the tensorboard / modify the reward with given info from env before inserting into the buffer / get stats in both training and test data (same preprocess_fn in different collectors). It just depends on what you want.

**Comment by flint-xf-fan** [comment]
Do you have an example for the purpose of re-training using Batch or Collector?

For example, I trained one policy A and now my train_collector contains the replay. How do I use the replay to train another policy B such that B only sees transition pairs of A without interacting with the env?

**Comment by Trinkle23897** [comment]
> Do you have an example for the purpose of re-training using Batch or Collector?
> 
> For example, I trained one policy A and now my train_collector contains the replay. How do I use the replay to train another policy B such that B only sees transition pairs of A without interacting with the env?

It is very similar to imitation learning (behavior cloning). I implemented the Dagger (the advance behavior cloning) in `test/discrete/test_a2c_with_il.py` and `test/continuous/test_sac_with_il.py`. You can simply play with it.

Here is a more simple version:

```python
collector_A = Collector(policy_A, env, buf)
...  # policy A is well-trained
for i in range(num_B_step):
    batch, indice = buf.sample(batch_size)
    policy_B.learn(batch)
# test policy_B
collector_B = Collector(policy_B, env)
collector_B.collect(n_episode=1)
```

**Comment by flint-xf-fan** [comment]
is learning from batch restricted to certain policy or applicable to all policies? I got the issue while using DQN:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
 in 
      4 for j in range(num_G_step):
      5     batch, indice = train_collectors[0].buffer.sample(batch_size)
----> 6     global_policy.learn(batch)
      7 

~/anaconda3/envs/ByzantineRL/lib/python3.6/site-packages/tianshou/policy/modelfree/dqn.py in learn(self, batch, **kwargs)
    160         q = self(batch).logits
    161         q = q[np.arange(len(q)), batch.act]
--> 162         r = to_torch_as(batch.returns, q)
    163         if hasattr(batch, 'update_weight'):
    164             td = r - q

AttributeError: 'Batch' object has no attribute 'returns'
```

I was trying to use tianshou for my research experiments where I want to do something similar to Dagger but not exactly. Basically I want to collect experiences from some agents. augment those experiences and use the augmented experiences to train a new agent.
```
# take collector 0's buffer for training the new policy
num_G_step = 1000
batch_size = 128
for j in range(num_G_step):
    batch, indice = train_collectors[0].buffer.sample(batch_size)
    # a new policy initialized the same way
    global_policy.learn(batch)
```

would appreciate a working example for demonstration.

**Comment by Trinkle23897** [comment]
Oh, I forgot to add a line before `learn`. Sorry.
```python
batch, indice = buf.sample(bsz)
batch = policy.process_fn(batch, buf, indice)  # <--
policy.learn(batch)
```

**Comment by flint-xf-fan** [comment]
> Oh, I forgot to add a line before `learn`. Sorry.
> 
> ```python
> batch, indice = buf.sample(bsz)
> batch = policy.process_fn(batch, buf, indice)  # <--
> policy.learn(batch)
> ```

cool, thanks
