### ISSUE TITLE
Diagram missing "learn()"?

### ISSUE THREAD

**Issue by drozzy** [thu-ml/tianshou#420]
On the [tutorial page](https://tianshou.readthedocs.io/en/master/tutorials/concepts.html) it seems like the Policy object is missing the `learn` call:
![image](https://user-images.githubusercontent.com/140710/129988006-20d45c0e-4cd5-4f97-9a84-42cf749c60d2.png)

I think I understand why it's left out - it would have to call itself?

**Comment by Trinkle23897** [comment]
It is in policy.update() so I decided to not put it here.

**Comment by drozzy** [comment]
Yeah that's what I figured.
