### ISSUE TITLE
Suggestion: sample_index -> sample_indices?

### ISSUE THREAD

**Issue by drozzy** [thu-ml/tianshou#421]
Just a suggestion. Feel free to close it if it's just bikeshedding.

I think it would be clearer if buffer's `sample_index` was called `sample_indices`, otherwise it makes it seems like it is only a single index that is sampled, whereas the return value is always a list.

https://github.com/thu-ml/tianshou/blob/728b88b92db94c4bbe095e6ad2cc3d331f8f9c8b/tianshou/data/buffer/base.py#L252

**Comment by Trinkle23897** [comment]
You can change if you want. This is an internal method. I'll help check the PR.
