### ISSUE TITLE
Support on Atari RAM

### ISSUE THREAD

**Issue by caozhangjie** [thu-ml/tianshou#423]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
I see that tianshou support training with the atari with visual image but does not support training with the RAM version of Atari games. Is there any plan for implementing this?

**Comment by Trinkle23897** [comment]
Feel free to make a pr if you have preliminary result.
