### ISSUE TITLE
A way to disable the testing in onpolicy?

### ISSUE THREAD

**Issue by drozzy** [thu-ml/tianshou#424]
Just curious, for the case of on-policy algorithms, is there a way to disable passing the `test_collector` argument into the `onpolicy_trainer`?

Because, for example, in the case of REINFORCE, I don't actually need to test the algorithm separately. My training performance *is* the test.

I'm just curious where in on-policy is testing different from training? 

Forgive my naive question, maybe I'm missing something

**Comment by Trinkle23897** [comment]
> My training performance is the test.

Usually it is biased because of moving average. You can simply set `--test-num 0` to see if it works I guess.

**Comment by drozzy** [comment]
Ended up using testing, the plots are more accurate.

Didn't try setting it to 0.
