### ISSUE TITLE
PPO value_clip unable to find reference paper

### ISSUE THREAD

**Issue by drozzy** [thu-ml/tianshou#429]
On this line in PPO algorithm:
https://github.com/thu-ml/tianshou/blob/e4f4f0e144b357885eb515dc3b25d854f6c98099/tianshou/policy/modelfree/ppo.py#L25

it says that:
```python
 :param bool value_clip: a parameter mentioned in arXiv:1811.02553 Sec. 4.1.
        Default to True.
```

I pull up the referenced paper: https://arxiv.org/abs/1811.02553
and there is no section 4.1.

Maybe this is a wrong paper reference?

**Comment by Trinkle23897** [comment]
https://arxiv.org/pdf/1811.02553v3.pdf

**Comment by drozzy** [comment]
Wow, how did you find that? And why did they remove it in latest version haha.

I guess we should link to v3 specifically.

**Comment by Trinkle23897** [comment]
don't know why but I actually referenced in April 2020... so I check previous version
