### ISSUE TITLE
sac example tensor size miss-match warning

### ISSUE THREAD

**Issue by mtaohuang** [thu-ml/tianshou#43]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue categories] for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
- version numbers:
```bash
0.2.2 1.4.0 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] linux
```
- problem:
`UserWarning: Using a target size (torch.Size([128, 4])) that is different to the input size (torch.Size([128, 1]))`
Seems the shape of current_q1 and current_q2 is not correct.
```bash
python3 examples/halfcheetahBullet_v0_sac.py --task BipedalWalkerHardcore-v3 --run-id train
Epoch #1:   0%|                                                                                                                                                                    | 0/1000 [00:00<?, ?it/s]
/usr/local/lib/python3.6/site-packages/tianshou/policy/modelfree/sac.py:111: UserWarning: Using a target size (torch.Size([128, 4])) that is different to the input size (torch.Size([128, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  critic1_loss = F.mse_loss(current_q1, target_q)
/usr/local/lib/python3.6/site-packages/tianshou/policy/modelfree/sac.py:117: UserWarning: Using a target size (torch.Size([128, 4])) that is different to the input size (torch.Size([128, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  critic2_loss = F.mse_loss(current_q2, target_q)

```
  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2

**Comment by Trinkle23897** [comment]
This is fixed in #41. I have just updated the issue categories.
