### ISSUE TITLE
Option to update policy with accumulated gradients

### ISSUE THREAD

**Issue by Aceticia** [thu-ml/tianshou#437]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [X] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
Recently I've been running sub-policies in a wrapper. To keep maximum modularity in my code and make it easier to sub for different sub-policies, the ideal behavior is that the wrapper simply calls the learn() function of the sub-policies. However, they can't be updated simultaneously, since learn() does the gradient step by default. This might be slightly problematic in use cases such as mine, where sub-policies need to be updated simultaneously. (I can still get this behavior by wrapping yet another policy class on top of the Tianshou built-in policy classes, but this losses the modularity)

I propose a very simple additional feature: User can pass flags such as "accumulate_grad=True" as keyword arguments to learn() or update() method calls, and optimizer steps are not executed if this flag is checked to be true. The user now only need to make sure all update() calls are accumulating gradient, and do a final optimizer step in their own wrapper class.

**Comment by Trinkle23897** [comment]
Could you plz submit a pr so that I can review it accordingly?

**Comment by Aceticia** [comment]
Currently, I'm adding this check for all policy classes. Do you think in consideration of modularity, we should further encapsulate the gradient steps in a class method in BasePolicy? After all, these updates are all identical for different policies.

**Comment by Trinkle23897** [comment]
> User can pass flags such as "accumulate_grad=True" as keyword arguments to learn() or update() method calls,

I think it can only do this. For off-policy, your approach is totally fine; but for on-policy, each `learn()` contains multiple accumulate_grad and how do you split into a single function call?

**Comment by Aceticia** [comment]
You are right about that...

On a separate note, I've trying to create a pull request. This is the first time I've done this, so it's taken pretty long. It seems that the new code consistently fail the `cpu-extra (macos-latest, 3.8)` test, on the "test_collector_with_async" test. I'm trying to reproduce this error on my workstation, but for some reasons pytest always runs into segfault. Is there any other way to debug this?

**Comment by Trinkle23897** [comment]
Don't worry, I'll fix that. Just open pull request

**Comment by Aceticia** [comment]
Thank you. Submitted pull request #438 .

**Comment by Trinkle23897** [comment]
closed as it can handle through how we define optimizer (pass dummy optim into different policy class)
