### ISSUE TITLE
Atari CNN Input Scale Issue

### ISSUE THREAD

**Issue by liziniu** [thu-ml/tianshou#440]
Hello,

It seems that the input of the CNN network does not be normalized by dividing 255 in the given examples. This is quite different from several public implementations. Any explanation for this?

Thanks,
Ziniu

**Comment by Trinkle23897** [comment]
> This is quite different from several public implementations.

Could you please provide the link? We follow openai baselines setting here: https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/atari_wrappers.py#L283-L284
https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/deepq/__init__.py#L8

PS. AMCE/dqn_zoo/dopamine all scale to 0~1.

**Comment by liziniu** [comment]
The environment preprocessing is okay. But the network input preprocessing is different.

https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/models.py#L19

That is, OpenAI Baselines tackles this issue when feeding the image into the network.

**Comment by Trinkle23897** [comment]
hmm okay, it's my fault.

**Comment by liziniu** [comment]
I have tested several algorithms with the Tianshou framework. The results show that this scaling issue does not matter too much in practice. Indeed, I do not observe this "bug" changes the comparison implications over algorithms. 

To understand this issue, recall that we use the Adam optimizer, which helps us normalize the scale for gradient update. In theory,  optimizing a modified objective function $c f(x)$ with the diagonalized gradient descent, where $c$ is a positive constant, is nothing different from the original case, in which we optimize $f(x)$ with the vanilla gradient descent. 

Anyhow, I think this "bug" does not hurt the performance. But it is better to mention this implementation difference.

**Comment by Trinkle23897** [comment]
Yeah I agree with you, but how about other RL algorithms that don't use Adam...?

**Comment by liziniu** [comment]
I think RMSProp can also work but SGD could not work due to a bad condition number.

**Comment by Trinkle23897** [comment]
~~From preliminary experiments of ppo (#374), this conclusion is not always true. After scaling (/255), the reward curve is much lower than previous version.~~
~~We observe the same phenomenon with other people’s ppo implementation.~~ this only happens in some (2 over 7) atari games, not all

**Comment by vwxyzjn** [comment]
Hello, I have recently made a tutorial on matching SB3's PPO performance in Atari (obtaining episodic return of ~400 in 10M steps), See 

https://youtu.be/MEt6rrxH8W4
https://youtu.be/05RMTj-2K_Y

And the source code here https://github.com/vwxyzjn/PPO-Implementation-Deep-Dive

Hope the implementation displayed in these videos will be helpful to you all :) 

Also, this [draft blog post](https://ppo-details.cleanrl.dev//2021/11/05/ppo-implementation-details/) contains the permanent links to `openai/baselines`, showing where the ~20 implementation details are originally defined.
