### ISSUE TITLE
How to implement continual learning experiment in Tianshou?

### ISSUE THREAD

**Issue by huang-fuxian** [thu-ml/tianshou#448]
Hello, I want to do something as in "Experience Replay for Continual Learning". 
Simply, it needs start one policy in several different game environment. At any time,  the policy is training on only one task(game env), but it alos test on other task(game env). And this situation dynamicly changing. For example: at time 1, train on Task 1, test on Task2; at time 2, train on Task 2, test on Task 1.... 

 So I wonder if it is possible to do it? How?

Thanks a lot for your reply.

**Comment by Trinkle23897** [comment]
Need to change the replay buffer's sample() function:

1. VectorEnv contains [env0, env1, env2, ...]
2. buffer.sample() only samples data from the given buffer id:

```python
class CustomizedBuffer(VectorReplayBuffer):
  def __init__(time_fn, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.time_fn = time_fn
  def sample_indices(self, batch_size):
    return self.buffers[self.time_fn()].sample_indices(batch_size)


cnt = 0
def time_fn():  
  # just an example, change when calling sample()
  # you can manually setup the interval
  global cnt
  cnt += 1
  return cnt % numenv
```

**Comment by huang-fuxian** [comment]
Thank you. I will try it.
