### ISSUE TITLE
state encoder for PG methods?

### ISSUE THREAD

**Issue by mtaohuang** [thu-ml/tianshou#45]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [ ] I have visited the [source website], and in particular read the [known issues]
- [ ] I have searched through the [issue categories] for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
As of version 0.2.2, it seems only the hidden state of polciy net are stored and used, how to train rnn critic nets(for POMDP problem)?
Maybe a state encoder should be added so policy and critic can share this encoder.
Are there any discussion groups? Really like this project :)
  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2

**Comment by Trinkle23897** [comment]
Thanks! You can refer to #19

**Comment by Trinkle23897** [comment]
> Are there any discussion groups?

You can directly comment on the related issues or join the gitter chat (shown in the top of readme, but almost none of the people joined ...)

**Comment by Trinkle23897** [comment]
Closed as the same issue exists.
