### ISSUE TITLE
Error with max_grad_norm in A2C Policy

### ISSUE THREAD

**Issue by zleonhe** [thu-ml/tianshou#46]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue categories] for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2

Versions:
0.2.2 1.5.0 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] linux

A2C policy cannot deal with max_grad_norm correctly. For example:

```
python test/discrete/test_a2c_with_il.py --max-grad-norm 1
Epoch #1:   0%|                                                                                                                                                                                                      | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test/discrete/test_a2c_with_il.py", line 137, in <module>
    test_a2c()
  File "test/discrete/test_a2c_with_il.py", line 98, in test_a2c
    writer=writer)
  File "/research/dept6/zlhe/miniconda3/envs/fp/lib/python3.7/site-packages/tianshou/trainer/onpolicy.py", line 89, in onpolicy_trainer
    train_collector.sample(0), batch_size, repeat_per_collect)
  File "/research/dept6/zlhe/miniconda3/envs/fp/lib/python3.7/site-packages/tianshou/policy/modelfree/a2c.py", line 101, in learn
    self.model.parameters(), max_norm=self._grad_norm)
AttributeError: 'NoneType' object has no attribute 'parameters'
```

This is due to the messed up variable names, as the following:
https://github.com/thu-ml/tianshou/blob/134f787e24d4fdb562d6c1ab81160d72db7a14ae/tianshou/policy/modelfree/a2c.py#L104-L106
However there should be `self.actor` and `self.critic` instead of `self.model`, which causes the error.

**Comment by Trinkle23897** [comment]
Thanks for pointing out! I fixed it.
