### ISSUE TITLE
How to add time limitation in my environment?

### ISSUE THREAD

**Issue by M1ddlzh** [thu-ml/tianshou#47]
In tianshou.data.collector.py, you note that "Please make sure the given environment has a time limitation.", which troubled me. I wonder how to add it.

In tianshou/test/continuous/test_ppo.py, the environment is "Pendulum-v0". After each step, it always return "done=False", I wonder the way of judging the terminal of one episode.

Thanks!

**Comment by Trinkle23897** [comment]
You can use gym.wrapper.
Btw, the limitation of Pendulum-v0 defaults to be 200 frames. So what's your gym version? (0.17.1 for me and works fine, at 200th timestep it returns `done=True`)

**Comment by Trinkle23897** [comment]
The reference code:
```python
In [14]: import gym 
    ...: print(gym.__version__) 
    ...: e = gym.make('Pendulum-v0') 
    ...: e.reset() 
    ...: i, d = 0, False 
    ...: while not d: 
    ...:     _, _, d, _ = e.step([0.1]) 
    ...:     i += 1 
    ...: print(i)
0.17.1
200
```

**Comment by M1ddlzh** [comment]
I see "done=False“ in sourcecode pendulum.py, you mean "gym.Wrapper" does extra work ( 200th timestep) on Pendulum?

**Comment by Trinkle23897** [comment]
No, I mean the default `gym.make('Pendulum-v0')` will not cause this problem. Manually adding gym.wrapper is the last choice.

**Comment by M1ddlzh** [comment]
I think setting "done=True" after 200 steps is added by "gym.Wrapper".

In your code above, I add "e.unwrapped" after "e = gym.make('Pendulum-v0')", it will not break the while loop.

**Comment by M1ddlzh** [comment]
In my one Env, using tianshou.ppo to train the agent always warning "'There are already many steps in an episode. You should add a time limitation to your environment!", but Pendulum doesn't warning. At first I think you did something magic in tianshou's code so I open a issue. Sorry for taking your time, Thanks!

**Comment by Trinkle23897** [comment]
Yes, `unwrapped` action will remove the time limit added by the gym.wrapper.
