### ISSUE TITLE
action space and state space

### ISSUE THREAD

**Issue by kikikio** [thu-ml/tianshou#48]
how to customize the state space and action space?
for example:
state = np.array([ a, b ,c ] ,dtype=int)
action space ={ 0 , 1 }

**Comment by Trinkle23897** [comment]
Do you mean the state is a list of int and the action is either zero or one?

**Comment by kikikio** [comment]
yes

**Comment by Trinkle23897** [comment]
Or do you mean the state's and action's shape is changing through timestep?

**Comment by Trinkle23897** [comment]
> yes

Just directly use tianshou, following the test code. You don't need to modify anything. If there's something wrong, put it here and let me know :)

**Comment by kikikio** [comment]
I want to use Tianshu to train an agent to detect abnormal traffic. In my scenario, we read in a package ——（key，value). And then we calculate some parameters. we use this parameters as state. After getting the state, we pass the state to the agent, and the agent will returns the action. Then, based on the value of action (0 or 1), we will proceed to the next step (detect abnormal traffic
).

**Comment by kikikio** [comment]
the space shape will change per step. And  the agent return action shape(0 or 1) every 5000 steps.

**Comment by kikikio** [comment]
My question now is:
1) How to customize state (a list of int), action (0 or 1) ？
2) How to update state？
3) How to get the action value returned by the agent？

**Comment by Trinkle23897** [comment]
Sure, according to your description, that's almost the same as what the current codebase supports. 

> In my scenario, we read in a package ——（key，value). And then we calculate some parameters. we use this parameters as state.

You could build your own env and add this procedure in `__init__` or `reset`. I prefer in `reset`.

> the space shape will change per step
> How to customize state (a list of int)

Find the maxsize of your state. Fill with 0 for shorter state shape to make them with same size.

> the agent return action shape(0 or 1) every 5000 steps.
> How to get the action value returned by the agent？

You can maintain the last valid action of your agent in your own env. I think this can be done at env side.

**Comment by kikikio** [comment]
Thank you very much.

**Comment by Trinkle23897** [comment]
Does this reply address all your concerns? Any more questions are welcomed.

**Comment by kikikio** [comment]
I will try it according to your suggestion. If I have any questions, I'll ask you again. Thank you very much
