### ISSUE TITLE
 support for other environments?

### ISSUE THREAD

**Issue by Niuniu331** [thu-ml/tianshou#50]
> * [x]  I have marked all applicable categories:
>   
>   * [ ]  exception-raising bug
>   * [ ]  RL algorithm bug
>   * [x]  documentation request
>   * [x]  new feature request
> * [x]  I have visited the [source website], and in particular read the [known issues]
> * [x]  I have searched through the [issue tracker] for duplicates
> * [ ]  I have mentioned version numbers, operating system and environment, where applicable:
> 

Hello, I'm using the DDPG algorithm to solve the network optimization problem, so the state of the environment is defined as the data from the network simulator in my model.Could you please provide some examples on how to interacte with environments other than gym Libraries? Thanks!

**Comment by Trinkle23897** [comment]
What's your data format?
Current github master version supports the environment that the observation is a dict. For example, you can refer to #38.

**Comment by Trinkle23897** [comment]
Now the state can be any type of data structure, e.g. a self-defined class such as networkx.Graph()
See #69 for more details.

**Comment by Trinkle23897** [comment]
I summarized in https://tianshou.readthedocs.io/en/latest/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation.
