### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by Trinkle23897** [thu-ml/tianshou#51]
- [x] DQN/DDPG/TD3/SAC with n-step return, in `process_fn`
- [x] PER interface
- [x] Batch over batch: do not copy

**Comment by mtaohuang** [comment]
maybe the n-step return can be moved into sample method of collector, with n-step parameter?
In this way the policy doesn't need access to the buffer or indices in the buffer.
I think this should be the way to do it, can you think of any drawbacks?

**Comment by Trinkle23897** [comment]
No, I think it is a part of the algorithm, like GAE.
