### ISSUE TITLE
Why is dqn playing breakout so bad? I trained 400 epochs and the final result did not exceed 6 points.

### ISSUE THREAD

**Issue by invisilmk** [thu-ml/tianshou#54]
I trained 400 epochs and the final result did not exceed 6 points. What parameters need to be adjusted?

**Comment by Trinkle23897** [comment]
Could you please provide your configuration? (e.g. network architecture, hyperparam, ...)

**Comment by invisilmk** [comment]
It was run on the original code, but increased to 400 epochs.

**Comment by Trinkle23897** [comment]
It's our fault that we have no time to provide the tuned code example in the `examples` folder currently.
A better solution is to change the example code's hyperparameter and network arch to the DQN paper's setting.
You can refer to https://github.com/thu-ml/tianshou/issues/31#issuecomment-616373342 for more details.

**Comment by Trinkle23897** [comment]
@Mehooz

**Comment by invisilmk** [comment]
Thanks a lot.

**Comment by duburcqa** [comment]
@Trinkle23897 Closing ?

**Comment by Trinkle23897** [comment]
> @Trinkle23897 Closing ?

Nope. It hasn’t been finished yet.

**Comment by davide97l** [comment]
I'm waiting for this too.

**Comment by Trinkle23897** [comment]
Here it is: we now provide a DQN script which can solve Pong in 1M environment step (about 2000 seconds wall time in my computer). #187 
The main issue of the previous version is that it doesn't use the wrapper provided by Deepmind. This is quite crucial.
Many thanks to @davide97l
