### ISSUE TITLE
Batch class wrapper missing 'values' method

### ISSUE THREAD

**Issue by duburcqa** [thu-ml/tianshou#56]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

0.2.2 (master commit de556fd22d59cd40115be24ab8f686501831b155) 1.5.0+cu101 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] linux

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

_______________

The [Batch](https://github.com/thu-ml/tianshou/blob/de556fd22d59cd40115be24ab8f686501831b155/tianshou/data/batch.py#L7) class implements `keys` method but `values` is missing. It is not a major issue but it would be nice to add it, both for convenience and consistency with the `dict` API.

**Comment by Trinkle23897** [comment]
Thanks! I'll add it in the next commit.

**Comment by duburcqa** [comment]
Nice ! Thank you :+1:
