### ISSUE TITLE
Collector `preprocess_fn` inconsistent input types

### ISSUE THREAD

**Issue by duburcqa** [thu-ml/tianshou#57]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

0.2.2 (master commit de556fd22d59cd40115be24ab8f686501831b155) 1.5.0+cu101 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] linux

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

_______________

When using a custom preprocessor `preprocess_fn`, the Collector is not converting the observation in `Batch` before calling it, while it is the case for the action. I think it would be better the convert it in `Batch` systematically, even when a custom preprocessor is defined. So that the final user only has to handle `Batch`, not an ugly numpy array of dict.

**Comment by Trinkle23897** [comment]
Could you please point out the lines of the code? Thanks!

**Comment by Trinkle23897** [comment]
ping again

**Comment by duburcqa** [comment]
Forget it, I'm not trying to use this feature anymore. Thanks anyway!
