### ISSUE TITLE
Bugs in collector.sample

### ISSUE THREAD

**Issue by brantbzhang** [thu-ml/tianshou#59]
```python
       if self._multi_buf:
            if batch_size > 0:
                lens = [len(b) for b in self.buffer]
                total = sum(lens)
                batch_index = np.random.choice(
                    total, batch_size, p=np.array(lens) / total)  # 
            else:
                batch_index = np.array([])
```
should be 
```python
batch_index = np.random.choice(
                   len(self.buffer]), batch_size, p=np.array(lens) / total)
```

**Comment by Trinkle23897** [comment]
我的multibuf是在self.buffer是个list的情况下才为True，指multi-agent多个policy匹配多个buffer
比如有四个buffer：
0：存了[0, 1000]
1：存了[0, 2000]
2：存了[0, 3000]
3：存了[0, 4000]
每个buffer size=10000
那么按照现有代码，total是1000+2000+3000+4000=10000，在10000个sample里面采样，然而改成你那样的话就只会在4个sample采样，因为len(self.buffer)==4

**Comment by brantbzhang** [comment]
```python
batch_index = np.random.choice(
    total, batch_size, p=np.array(lens) / total)
```
This code is for sampling from multiple buffers. `p` is the weight for each buffer.
If we have 4 buffer with batch_size=8, the `batch_index` should be something like `0, 0, 1, 2, 3, 0, 1, 2`, which means each sample is from which buffer.

`p` is the length of self.buffer. The range of `batch_index` should be equal to `p`, otherwise it will raise an exception.

**Comment by Trinkle23897** [comment]
You are right. I fix it.
