### ISSUE TITLE
Refactoring of Batch class

### ISSUE THREAD

**Issue by duburcqa** [thu-ml/tianshou#60]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable.

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

___________

I just reviewed your implementation of [Batch](https://github.com/thu-ml/tianshou/blob/master/tianshou/data/batch.py) class. It is nice, but you are always accessing the value of the stored objects using key instead of iterators. I think it would be both clearer and more efficient to rely on iterators everywhere, since it would no longer access the hashing table every time you want to get an item.

If you want, I can do it by myself and open a PR.

**Comment by Trinkle23897** [comment]
Sure! PRs are welcome.
