### ISSUE TITLE
What does the estimation_step parameter in sac do? 

### ISSUE THREAD

**Issue by jaried** [thu-ml/tianshou#629]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.7 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```

Excuse me, what does the `estimation_step: the number of steps to look ahead` parameter in sac do? 

SAC defaults to 3, what does it mean?

**Comment by Trinkle23897** [comment]
It's for n-step target return computation. For example, this is a 2-step return: https://tianshou.readthedocs.io/en/master/tutorials/concepts.html#policy-process-fn

**Comment by jaried** [comment]
Thanks for your answer.
