### ISSUE TITLE
How can I use a self-defined state in tianshou?

### ISSUE THREAD

**Issue by mrbeann** [thu-ml/tianshou#69]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

I was wondering if it's possible for me to add some self-defined states, e.g., a nexworkx graph? Thanks!

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

**Comment by Trinkle23897** [comment]
Do you mean https://github.com/networkx/networkx?

**Comment by Trinkle23897** [comment]
You could possibly hack the code. If your state is 
```
{'graph': nx.Graph()}
```
then change this line https://github.com/thu-ml/tianshou/blob/1fce527c776a26749178dd70597bc5820cd2233f/tianshou/data/buffer.py#L156
 to 
```python
if name in ['info', 'obs', 'obs_next']:
```
This is to enable the dict storage in np.ndarray. And in your network side, 
```
class NN(nn.Module):
    def __init__(self, ...):
        ...
    def forward(self, state, ...):
        graph = state['graph']
        (other operations)
```

**Comment by mrbeann** [comment]
great idea! I'll try it.

**Comment by Trinkle23897** [comment]
I’ll add a commit tomorrow so that you could use nx state without hacking the codebase.

**Comment by Trinkle23897** [comment]
@mrbeann You can have a try with the current master codebase. The state could be either a dict `{'g': nx.Graph()}` or directly a graph `nx.Graph()`.

**Comment by mrbeann** [comment]
Yeah, it works now. Thanks!

**Comment by Trinkle23897** [comment]
Btw, the state stored in the buffer may be a shallow copy. To make sure each of your graphs stored in the buffer is distinct, return the deep-copy version of your state in your env.
```python
def reset():
    return copy.deepcopy(self.graph)
def step(a):
    ...
    return copy.deepcopy(self.graph), reward, done, {}
```

**Comment by mrbeann** [comment]
Thanks for the reminder.
