### ISSUE TITLE
Does it support cuda10.0 and torch1.12?

### ISSUE THREAD

**Issue by LoveDLWujing** [thu-ml/tianshou#72]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website], and in particular read the [known issues]
- [ ] I have searched through the [issue tracker] and [issue categories] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

**Comment by Trinkle23897** [comment]
Currently, the latest version of PyTorch is 1.5.0. 1.12 should be a year away...
1.5.0 is with CUDA10.x. I run with CUDA 10.0 locally.
