### ISSUE TITLE
env problem

### ISSUE THREAD

**Issue by M1nHuan** [thu-ml/tianshou#75]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website], and in particular read the [known issues]
- [ ] I have searched through the [issue tracker] and [issue categories] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

Hey， Tianshou's DRL algorithm is implemented on gym’environment ，if I want to implement tianshou on my own RL environment，what rules should I follow to define a RL environment ？ I haven't found related solutions in tianshou' tutorial

**Comment by Trinkle23897** [comment]
Just follow the Gym's API.
- reset() -> state
- step(action) -> state, reward, done, info
- seed(s) -> None
- render(mode) -> None
- close() -> None

**Comment by Trinkle23897** [comment]
I'll add the hint later on.

**Comment by M1nHuan** [comment]
GOT IT , THANK YOU

**Comment by Trinkle23897** [comment]
Added in https://tianshou.readthedocs.io/en/latest/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation
