### ISSUE TITLE
the target of critic in sac

### ISSUE THREAD

**Issue by invisilmk** [thu-ml/tianshou#76]
Why didn't the critical target of sac join the strategy probability?

**Comment by Trinkle23897** [comment]
Sorry, I didn't get it. What does it mean?

**Comment by invisilmk** [comment]
This is the target of critic in spinningup,：
            backup = r + gamma * (1 - d) * (q_pi_targ - alpha * logp_a2)
yours is
           target_q = (rew + (1. - done) * self._gamma * target_q)

**Comment by Trinkle23897** [comment]
Yes, that's the same. 
https://github.com/thu-ml/tianshou/blob/52be533d062f0f3565b6c0cd503e4d9199532e9e/tianshou/policy/modelfree/sac.py#L116-L119
This is `(q_pi_targ - alpha * logp_a2)`

**Comment by invisilmk** [comment]
Sorry, I was blind.
