### ISSUE TITLE
Pytorch version requirement

### ISSUE THREAD

**Issue by yizhengzhang1** [thu-ml/tianshou#77]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [x] I have mentioned version numbers, operating system and environment
Tianshou can not install successfully.
1.1.0 3.7.7
[GCC 7.3.0] linux

Hi,
 I'm using `Cuda 9.0`, so the torch version I installed is `1.1.0`. It seems that tianshou's requirement is `torch>=1.4.0`. Is it possible to install tianshou with `torch 1.1.0`?

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

**Comment by Trinkle23897** [comment]
Hmm...I have not tested and maybe you can have a try?
Run `pytest test/ --cov tianshou -s --durations 0 -v` and see its behavior.
Install pytest: `pip3 install pytest`

**Comment by Trinkle23897** [comment]
If your Nvidia driver version is greater than 418, you can self-install cuda10 without root (through anaconda).

**Comment by yizhengzhang1** [comment]
Emmm... My Nvidia driver version is 384.
I set the install_requries in the `setup.py` to be `torch>=1.1.0`. Then I do install it. But when I run the `python3 test/discrete/test_pg.py`. 
It raises a error: `RuntimeError: expected backend CUDA and dtype Double but got backend CUDA and dtype Float`

**Comment by Trinkle23897** [comment]
Try `python3 test/discrete/test_pg.py --device cpu` ?

**Comment by yizhengzhang1** [comment]
It raises the same error~~~

**Comment by Trinkle23897** [comment]
I update the code and now it should not raise the same error. Remove the dependency "torch>=1.4" in setup.py and reinstall tianshou.

**Comment by yizhengzhang1** [comment]
Cool !!!
 It works now.
