### ISSUE TITLE
Maybe a bug in the evaluation of DDPG

### ISSUE THREAD

**Issue by danagi** [thu-ml/tianshou#81]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

Hi, I created a pull request and got merged last night. I'm sorry that I forgot to report a bug fix in that commit.
I noticed a bug(maybe) in ddpg when I was modifying the code about adding noise to action.

In previous implementation, collector would pass `eps = None` to `forward()` both in training and evaluating.

> https://github.com/thu-ml/tianshou/blob/dc451dfe888a99abec99fe8373fa15a874007374/tianshou/policy/modelfree/ddpg.py#L121-L126

Then the `eps`  would be set to `self._eps`, so a noise would be added to action. But why should a noise be added to action in evaluation?

> https://github.com/thu-ml/tianshou/blob/dc451dfe888a99abec99fe8373fa15a874007374/tianshou/policy/modelfree/ddpg.py#L145-L152

So I added a line in ddpg (also in sac) to avoid a noise addition in evaluation.

> https://github.com/thu-ml/tianshou/blob/c59ad40aef02e5fe4f072f0f3193f4a7be86e2d6/tianshou/policy/modelfree/ddpg.py#L146-L147

Let me know if this is really a bug or not. Thank you.

**Comment by Trinkle23897** [comment]
From my previous experience, (in Q-learning based algorithms) if using an eps in the training phase but zero eps in the test phase, the performance would drop down; but with smaller eps but greater than zero, it works well.
Sorry for the late reply. I'm busy with my graduation these days (and Tsinghua U is in Beijing :(

**Comment by danagi** [comment]
> From my previous experience, (in Q-learning based algorithms) if using an eps in the training phase but zero eps in the test phase, the performance would drop down; but with smaller eps but greater than zero, it works well.
> Sorry for the late reply. I'm busy with my graduation these days (and Tsinghua U is in Beijing :(

Oh, poor you.
Maybe it should leave an interface to users, so that they could decide whether to add an action noise in evaluation?
Hope you guys are fine.

**Comment by Trinkle23897** [comment]
Yes, I agree with you. Maybe you can submit another pull request once you come up with the interface design.

**Comment by danagi** [comment]
Sorry for the late replay. I've submitted a pull request with the interface design.

**Comment by Ethanwl** [comment]
Is it necessary to decrease noise as the training process goes on (in ddpg policy)? Can I do this in tianshou?
在ddpg中有必要将噪声衰减吗？在天授框架中可以这样做吗？

**Comment by Trinkle23897** [comment]
> Is it necessary to decrease noise as the training process goes on (in ddpg policy)? Can I do this in tianshou?

As you wish. Just modify the Gaussian Noise class and add a counter, each `__call__` will increase the counter and decrease sigma a little.
