### ISSUE TITLE
here in BasePolicy.compute_episodic_return() lacks a dtype=np.float, when gae_lamda=0 it will cause batch.returns in problem

### ISSUE THREAD

**Issue by jedz5** [thu-ml/tianshou#85]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:

https://github.com/thu-ml/tianshou/blob/a655334d00a07c42d7d413a0c1dd60697bdaf6a5/tianshou/policy/base.py#L126-L128

  [source website]: https://github.com/thu-ml/tianshou
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

**Comment by Trinkle23897** [comment]
I think it is because your reward type is int. 
I have fixed it and thanks for pointing out!
