### ISSUE TITLE
Batch to Numpy compatibility

### ISSUE THREAD

**Issue by duburcqa** [thu-ml/tianshou#90]
The current implementation of `__len__` and `__getitem__` is kind of weird because it is infinitely recursive: one can do `Batch()[0]` and it does not throw an exception but rather return the same object `Batch()`. This is an issue because it breaks the compatibility with standard numpy methods such as `np.mean`, `np.max` ... which should work otherwise. It would be easy to change this behavior, but many policy algorithm relies on it.  Calling such a numpy method simply hangs infinitely, for example using `np.asarray(Batch())`, and so does `[o for o in Batch(a=[1.0])]` which is even worst.

I opened a PR implementing the desired behavior, but I need help to update accordingly the policy algorithms.

______

Here is what you get using the proposed implementation.

Input:
```
np.mean(Batch(a=np.array([[1.0, 2.0], [3.0, 4.0]]), b=np.array([5.0, 6.0])))
```
Output:
```
Batch(
    a: array([2., 3.]),
    b: 5.5,
)
```

**Comment by duburcqa** [comment]
`Batch` class itself is ready, but many tests are failing. I would be grateful if someone could take a look since I'm only used by `data` submodules.

**Comment by Trinkle23897** [comment]
It seems like it
- fails get the length of Batch(a=1), where the `r` is empty and `min(r)` would throw an error
- fails to slice

**Comment by duburcqa** [comment]
Yes, to be consistent with numpy API, getting the length of 0-dim array must fail (for instance you can try `len(np.array(0.0))`), which means that `len(Batch(a=1))` is expected to throw an error. Similarly, such a `Batch` must not be slice-able, based on the same reasoning.

I propose to implement a `shape` method, having the same behavior than numpy `shape` method. It returns an empty list if the array/Batch is 0-dim instead of throwing an exception.

**Comment by duburcqa** [comment]
@Trinkle23897 Added `shape` method, though it is not ideal since it is difficult to define the notion of shape properly for a complex heterogeneous object such as Batch. It would be better if we could get rid of it.

Edit: I'll implement `size` instead, which is way more appropriate than `shape`.

**Comment by Trinkle23897** [comment]
How about `Batch(a=[1,2,3], b=1, c=[1,2,3,4])`?
I mean that if slicing a Batch, we can automatically ignore those variables which do not have `__len__` attribute.

The expected output should be
```python
>>> a = Batch(a=[1,2,3], b=1, c=[1,2,3,4])
>>> len(a)
3
# or 4, but it doesn't matter too much
>>> a[0]
Batch(
    a=1,
    c=1,
)
```

**Comment by duburcqa** [comment]
I see your point, but such a behavior is not "expected" from a numpy point of view. Indeed, in this case, your slicing behavior may remove some items that were original present, in your example 'b' disappears after slicing, and therefore it is not revertible (the result of stacking every slices is different from the original Batch). There is not way to make this behavior compatible with numpy.

In your example, numpy is expected to get an exception when getting the length of `a`, since it is not slice-able without loss of information (slicing cannot be reverted).

**Comment by Trinkle23897** [comment]
`a = Batch(a=[1,2,3], b=Batch(), c=[1,2,3,4])`
The `a.b` should be ignored because it reserves some keys:

```python
ReplayBuffer(
    act: array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]),
    done: array([False, False, False, False,  True, False, False, False, False,
                 False, False, False, False, False, False, False, False, False,
                 False, False]),
    info: Batch(
              key: array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]),
              env: array([<env.MyTestEnv object at 0x7ff8909a52b0>,
                          <env.MyTestEnv object at 0x7ff8909a52b0>,
                          <env.MyTestEnv object at 0x7ff8909a52b0>,
                          <env.MyTestEnv object at 0x7ff8909a52b0>,
                          <env.MyTestEnv object at 0x7ff8909a52b0>, None, None, None, None,
                          None, None, None, None, None, None,
                          <env.MyTestEnv object at 0x7ff8909a52b0>,
                          <env.MyTestEnv object at 0x7ff8909a52b0>,
                          <env.MyTestEnv object at 0x7ff8909a52b0>,
                          <env.MyTestEnv object at 0x7ff8909a52b0>,
                          <env.MyTestEnv object at 0x7ff8909a52b0>], dtype=object),
          ),
    obs: array([5, 6, 7, 8, 9, 5, 4, 3, 2, 1, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4]),
    obs_next: array([ 6,  7,  8,  9, 10,  4,  3,  2,  1,  0,  0,  0,  0,  0,  0,  1,  2,
                      3,  4,  5]),
    policy: Batch(),
    rew: array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
)
```
here, none of the elements are saved in `policy`.

Another possible solution is to change the `policy`'s saving behavior as `info`: create `np.array([None] * self._size)` if the policy's argument in _add_to_buffer is None in the first time.

**Comment by duburcqa** [comment]
Yes, we could simply 'ignore' it, i.e. add it to the result but do not perform any computation on it, to actually only reserve the key. I'll implement something and I let you know when it's working.

**Comment by duburcqa** [comment]
Done ! here is the expected behavior I implemented:

```
>>> a = Batch(a=[1,2,3], b=Batch(), c=[1,2,3,4])
>>> len(a)
3
>>> a[0]
Batch(
    a=1,
    b=Batch(),
    c=1
)
```

As it is revertible, it is now perfectly compatible with numpy.

I also added a new `size` method that can be used to check the emptyness of a Batch.

**Comment by duburcqa** [comment]
Unfortunately, my implementation does not the issue you mention since you are actually doing `Batch()[0]` instead of `Batch(a=[1.0], b=Batch())`, which is actually forbidden. But it looks like `ReplayBuffer` is doing stuff very similar to `Batch`, so maybe it could simply inherit for it, which you be clearer, shorter and simpler to implement. I'll have a look at it.

**Comment by Trinkle23897** [comment]
> maybe it could simply inherit for it, which you be clearer, shorter, and simpler to implement. I'll have a look at it.

Yes. Much appreciated!

**Comment by duburcqa** [comment]
I managed to fix the issue without refactoring `ReplayBuffer`. Everything is working as expected and I implemented unit tests for the new features. Ready to be merged if you are ok with it :+1:
