### ISSUE TITLE
Exception-raising in PrioritizedReplayBuffer

### ISSUE THREAD

**Issue by Ethanwl** [thu-ml/tianshou#91]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```
Version: tianshou=0.2.3, torch=1.5.1. 
raise ValueError("batch_size should be less than len(self)")
When ''collect_per_step'' is less than ''batch_size'' in ''offpolicy_trainer'', the exception is always raised at the begin of the trianing process.

**Comment by Trinkle23897** [comment]
@rocknamx8

**Comment by rocknamx8** [comment]
PrioritizedReplayBuffer sampling without repeat by default, so the exception will be raised when the number of transitions in the buffer is less than the batch size. Please make sure there are enough transitions in the buffer.

**Comment by Ethanwl** [comment]
However, in the first epoch of the trianing process, collector collects ''collect_per_step'' data and then trainer ''batch_size'' samples from buffer. So the only solution without changing source code is that make sure ''collect_per_step'' larger than or equal to ''batch_size''. Right? Are there any other solutions?

**Comment by rocknamx8** [comment]
@Ethanwl Sorry, I will try to fix it, and add the feature of sampling repeatedly as soon as possible tomorrow.
