### ISSUE TITLE
Batch & Buffer profiling

### ISSUE THREAD

**Issue by Trinkle23897** [thu-ml/tianshou#96]
Related to #95

**Comment by Trinkle23897** [comment]
Create a unit test which includes:

- profile many 3d np.ndarray ([84, 84, 3]) storage
- profile dict_state storage
- profile \_\_setitem\_\_ and \_\_getattr\_\_ (e.g. compare batch[i] = xxx and batch.key = xxx)
- profile multi-level \_\_getattr\_\_ (e.g. batch.a.b.c.d = 3)

More to be added.

**Comment by duburcqa** [comment]
Profiling of `test_ppo.py`

![output](https://user-images.githubusercontent.com/17752950/85727146-1133b480-b6f7-11ea-9646-e0459b73733b.png)

**Comment by duburcqa** [comment]
Buffer `update` is taking 55% of the Collector `collect` calls. It seems unacceptable even on toy environment. Buffer `__getitem__` since to be a bottleneck.

**Comment by Trinkle23897** [comment]
I ran through all of the tests on my computer: 4 mins (previous) to 6 mins (now).
Could you please profile the previous version?

**Comment by duburcqa** [comment]
yes I'll do.

**Comment by Trinkle23897** [comment]
For example, ebc551a

**Comment by duburcqa** [comment]
Right now I'm profiling 506cc97ba56a7567f8a1e68d73f4cb063cf2fb33

![output_old](https://user-images.githubusercontent.com/17752950/85730534-029acc80-b6fa-11ea-8f68-e9487b0fd6f4.png)

That's it, Batch `update` is twice slower now.

**Comment by duburcqa** [comment]
In the meantime, I'm implementing a simple fix. I think most of the overhead comes from relying on `getattr` and `__getitem__` instead of direct access. It is more elegant and easy to maintain but significantly slower. I'll let you now, it should be quick.

**Comment by duburcqa** [comment]
I made some progress. Now it takes less than 6min30 on github. #97 

![output_new](https://user-images.githubusercontent.com/17752950/85737221-7d1a1b00-b6ff-11ea-9348-55ac0e7b32a8.png)

Still merging for improvement: 55% -> 39% (27% before)

**Comment by duburcqa** [comment]
I think I have identified the problem. I'm fixing it. Hopefully the original performances will be (almost) recovered.

**Comment by duburcqa** [comment]
Done ! The performances are slightly better than before at least for PPO: 55% -> 24% (27% before)

![output_new_9](https://user-images.githubusercontent.com/17752950/85834019-f57dec00-b792-11ea-894b-7a42ceb4f297.png)

I ran through all of the tests on github now takes about 5min30. Let me know if you see any difference on your side.

**Comment by duburcqa** [comment]
Running all the tests on my computer: 5m50 for #97 , 5m30 for ebc551a25edc4034f36f440cb25e9b32c3ce6910

I don't think there is still any margin for improvement, apart from refactor Buffer `update` method to avoid relying on high level API `add` and `__getitem__`. But I think right now it is a good compromise between clarity and efficiency.

**Comment by ChenDRAG** [comment]
> Profiling of `test_ppo.py`
> 
> ![output](https://user-images.githubusercontent.com/17752950/85727146-1133b480-b6f7-11ea-9646-e0459b73733b.png)

hi, could you tell me which tool you use to profile the script? Intend to compare latest commit with an older one in detail.

**Comment by duburcqa** [comment]
https://github.com/jrfonseca/gprof2dot#python-profile

**Comment by ChenDRAG** [comment]
> https://github.com/jrfonseca/gprof2dot#python-profile

thanks a lot
