### ISSUE TITLE
ActorProb has redundant activation function in SAC examples

### ISSUE THREAD

**Issue by danagi** [thu-ml/tianshou#98]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

In examples/continuous_net.py, the `ActorProb` adds a `tanh` to `mu` while this is needed for other actor-critic algorithm but redundant for sac. The reason is that sac uses a reparameterization trick in implementation which bases on an unbounded gaussian distribution in original paper.

**Comment by Trinkle23897** [comment]
Thanks for pointing out!
