### ISSUE TITLE
support for multiple updates in one step

### ISSUE THREAD

**Issue by danagi** [thu-ml/tianshou#99]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

I think it would be great if tianshou support for multiple network updates in one step. Acctually I found this need was often met and supported in other libraries. If you agree, I would like to submit a pull request to add this feature.

**Comment by Trinkle23897** [comment]
I haven't got the meaning of `multiple network updates in one step`. Could you please give a simple explanation?
Does it mean more than one network needs to be updated or a single network needs to be updated by many times in one step?

**Comment by danagi** [comment]
Well,  the trainer currently works like it would collect some frames (`collect_per_step`) then do one policy network update and then collect some frames and go on and on.
If this feature is added, it could work like it would collect some frames then do some policy network update (`update_per_step`) and then collect some frames and go on and on.

**Comment by danagi** [comment]
> a single network needs to be updated by many times in one step?

Yes, the latter.

**Comment by Trinkle23897** [comment]
Okay. Welcome PR!

**Comment by danagi** [comment]
Alright, I'll achieve this today or tomorrow

**Comment by Trinkle23897** [comment]
I'm suffering from CMU's summer course midterm and homework so that I could only review the code :(

**Comment by Trinkle23897** [comment]
By the way, do you mean that the `repeat_per_collect` argument in on-policy trainer is not enough? It will use the `repeat` argument in `policy.learn`. Is it necessary for off-policy algorithm?

**Comment by danagi** [comment]
Yeah, I've found out that the repeat_per_collect argument is already enough for on-policy trainer, so I just changed the off-policy trainer. You can check out the hyperparams of off-policy in baselines-zoo, there has a hyperparam called gradient-steps that works in this way. Also, there are some algorithms that use off-policy algorithms but works in on-policy style. For example, intrinsic reward.

**Comment by danagi** [comment]
I am very sorry. The support for #99 is actually has a bug that it should update policy network in a local step rather than in a global step. And now I am considering that this feature is prefered to be implement by users rather than supported by tianshou. So you could delete this feature if you want. Sorry for any inconvenience caused.

**Comment by Trinkle23897** [comment]
I think you can further change some interface and fully support this feature. No need to delete and self-blame.
Here is what I think: I will not reject any of feature requests and related PR. Because other people may have the same needs as you.

**Comment by danagi** [comment]
Thanks :). That really makes me feel better. I'll perfect this feature.

**Comment by Trinkle23897** [comment]
Finally, I decide to keep the current definition of `step`: a step in trainer means a policy network update. I add some comments in #180.
